# 03 — Preprocessing and Model Training

**Purpose.** Build the two parallel corpora that the whole study rests on, then
train both architectures on each of them.

The experimental design is a **controlled two-track ablation**. One preprocessing
pipeline is built and forked at exactly one operation:

* **Track A — `text_no_emoji`** — every emoji is deleted.
* **Track B — `text_with_emoji`** — every emoji is replaced by its Unicode description.

Upstream and downstream of that fork both tracks are treated identically, so the
only systematic difference between the two corpora is whether emoji content
survives as text. Each track then trains both architectures under an identical
protocol, giving four comparable conditions.

| | |
|---|---|
| **Input**  | `data/interim/{train,dev,test}_raw.csv` |
| **Output** | `data/processed/*_cleaned.csv`, `models/*.keras`, `results/thresholds.json`, `results/best_configs.json`, `results/hyperparameter_search.csv` |
| **Next**   | `04_evaluation.ipynb` |

> **Note.** The attention model is a Transformer encoder trained **from scratch**.
> It is stored as `bert_*.keras` for continuity with the original notebook, but it
> is not pretrained BERT and should not be described as such.

In [ ]:
# emoji  -> Track A (deletion)   demoji -> Track B (verbalisation)
try:
    import emoji, demoji
except ImportError:
    !pip install -q emoji demoji
    import emoji, demoji

In [ ]:
import os
from pathlib import Path

ON_KAGGLE = os.path.exists("/kaggle/working")

if ON_KAGGLE:
    PROJECT = Path("/kaggle/working")
    RAW_CANDIDATES = [Path("/kaggle/input")]
else:
    # notebooks/ lives one level below the project root
    PROJECT = Path.cwd()
    if PROJECT.name == "notebooks":
        PROJECT = PROJECT.parent
    RAW_CANDIDATES = [PROJECT / "data" / "raw"]

INTERIM   = PROJECT / "data" / "interim"
PROCESSED = PROJECT / "data" / "processed"
MODELS    = PROJECT / "models"
RESULTS   = PROJECT / "results"
FIGURES   = PROJECT / "figures"
for d in (INTERIM, PROCESSED, MODELS, RESULTS, FIGURES):
    d.mkdir(parents=True, exist_ok=True)

EMOTION_LABELS = [
    "anger", "anticipation", "disgust", "fear", "joy", "love",
    "optimism", "pessimism", "sadness", "surprise", "trust",
]
TRACKS = [
    ("no_emoji",   "text_no_emoji",   "Without Emoji"),
    ("with_emoji", "text_with_emoji", "With Emoji"),
]

print("project root :", PROJECT)
print("on kaggle    :", ON_KAGGLE)

In [21]:
import json, re, string
import numpy as np
import pandas as pd
import tensorflow as tf
import nltk
from nltk.tokenize import TweetTokenizer
from nltk.stem import WordNetLemmatizer
from sklearn.metrics import f1_score

for pkg in ("punkt", "wordnet", "omw-1.4"):
    nltk.download(pkg, quiet=True)

SEED = 42
np.random.seed(SEED)
tf.keras.utils.set_random_seed(SEED)

print("TensorFlow:", tf.__version__)

MAX_TOKENS      = 20000
SEQUENCE_LENGTH = 128
SEARCH_EPOCHS   = 5
FINAL_EPOCHS    = 10

[nltk_data] Error loading punkt: <urlopen error [Errno -3] Temporary
[nltk_data]     failure in name resolution>

[nltk_data] Error loading wordnet: <urlopen error [Errno -3] Temporary
[nltk_data]     failure in name resolution>

TensorFlow: 2.20.0

[nltk_data] Error loading omw-1.4: <urlopen error [Errno -3] Temporary
[nltk_data]     failure in name resolution>

## 3.1 The preprocessing pipeline

Five stages. Stage 2 is the fork and is the **only** operation that differs
between the tracks.

> These functions are the single source of truth for what the models were trained
> on. `app/preprocessing.py` is a deliberate copy for serving — if you change
> anything here, change it there too, or every prediction the UI makes becomes
> invalid.

In [22]:
tweet_tokenizer = TweetTokenizer(preserve_case=False, strip_handles=True, reduce_len=True)
lemmatizer = WordNetLemmatizer()

slang_map = {
    "u": "you", "ur": "your", "r": "are", "lol": "laugh", "omg": "surprise",
    "im": "i am", "cant": "cannot", "dont": "do not", "gonna": "going to",
}


def clean_text(text):
    """Stage 1 - strip URLs, @mentions and the # symbol (keeping the word)."""
    text = str(text)
    text = re.sub(r"http\S+|www\.\S+", "", text)
    text = re.sub(r"@\w+", "", text)
    text = re.sub(r"#(\w+)", r"\1", text)
    return re.sub(r"\s+", " ", text).strip()


def handle_emoji_no(text):
    """Stage 2a - TRACK A: delete every emoji."""
    return emoji.replace_emoji(str(text), replace="")


def handle_emoji_yes(text):
    """Stage 2b - TRACK B: replace each emoji with its Unicode description."""
    return demoji.replace_with_desc(str(text), sep=" ")


def normalize_text(text):
    """Stage 3 - lowercase, strip non-alphanumerics."""
    text = text.lower()
    text = re.sub(r"[^a-z0-9\s]", " ", text)
    return re.sub(r"\s+", " ", text).strip()


def tokenize_text(text):
    """Stage 4 - TweetTokenizer, dropping bare punctuation."""
    return [t for t in tweet_tokenizer.tokenize(text) if t not in string.punctuation]


def lemmatize_tokens(tokens):
    """Stage 5 - slang expansion then WordNet lemmatisation."""
    tokens = [slang_map.get(t, t) for t in tokens]
    return [lemmatizer.lemmatize(t) for t in tokens]


def build_text(text, emoji_mode="no"):
    """Full pipeline. emoji_mode='no' -> Track A, 'yes' -> Track B."""
    text = clean_text(text)
    text = handle_emoji_no(text) if emoji_mode == "no" else handle_emoji_yes(text)
    text = normalize_text(text)
    return " ".join(lemmatize_tokens(tokenize_text(text)))

### Worked example — where the two tracks diverge

Run on a constructed sentence rather than a real tweet, so no corpus text is
reproduced.

In [23]:
sample = "I'm so happy today \U0001F602\U0001F62D u cant believe it!! #joy @friend http://x.com"

s1 = clean_text(sample)
a2, b2 = handle_emoji_no(s1), handle_emoji_yes(s1)
a3, b3 = normalize_text(a2), normalize_text(b2)
a5 = " ".join(lemmatize_tokens(tokenize_text(a3)))
b5 = " ".join(lemmatize_tokens(tokenize_text(b3)))

stages = pd.DataFrame([
    {"stage": "0. input",                    "Track A": sample, "Track B": sample},
    {"stage": "1. noise removal",            "Track A": s1,  "Track B": s1},
    {"stage": "2. emoji handling  <- FORK",  "Track A": a2,  "Track B": b2},
    {"stage": "3. normalisation",            "Track A": a3,  "Track B": b3},
    {"stage": "5. slang + lemmatisation",    "Track A": a5,  "Track B": b5},
])
pd.set_option("display.max_colwidth", 100)
display(stages)

print("\nTrack B recovered these extra tokens from the emoji:")
print(" ", sorted(set(b5.split()) - set(a5.split())))

,stage,Track A,Track B
0,0. input,I'm so happy today 😂😭 u cant believe it!! #joy @friend http://x.com,I'm so happy today 😂😭 u cant believe it!! #joy @friend http://x.com
1,1. noise removal,I'm so happy today 😂😭 u cant believe it!! joy,I'm so happy today 😂😭 u cant believe it!! joy
2,2. emoji handling <- FORK,I'm so happy today u cant believe it!! joy,I'm so happy today face with tears of joy loudly crying face u cant believe it!! joy
3,3. normalisation,i m so happy today u cant believe it joy,i m so happy today face with tears of joy loudly crying face u cant believe it joy
4,5. slang + lemmatisation,i m so happy today you cannot believe it joy,i m so happy today face with tear of joy loudly cry face you cannot believe it joy

Track B recovered these extra tokens from the emoji:
  ['cry', 'face', 'loudly', 'of', 'tear', 'with']

## 3.2 Apply the pipeline to every split

In [24]:
splits = {s: pd.read_csv(INTERIM / f"{s}_raw.csv") for s in ("train", "dev", "test")}

for name, df in splits.items():
    df["text_no_emoji"]   = df["text"].apply(lambda t: build_text(t, "no"))
    df["text_with_emoji"] = df["text"].apply(lambda t: build_text(t, "yes"))
    print(f"{name:6s} preprocessed  ({len(df)} rows)")

train_df, dev_df, test_df = splits["train"], splits["dev"], splits["test"]

train  preprocessed  (6838 rows)

dev    preprocessed  (886 rows)

test   preprocessed  (3259 rows)

### Did preprocessing damage anything?

Two failure modes matter: rows reduced to an empty string (the model would receive
nothing), and the two tracks accidentally coming out identical (which would mean
the fork did nothing).

In [25]:
check = []
for name, df in splits.items():
    a, b = df["text_no_emoji"], df["text_with_emoji"]
    check.append({
        "split": name,
        "mean length A": round(a.str.len().mean(), 1),
        "mean length B": round(b.str.len().mean(), 1),
        "empty A": int((a.str.strip() == "").sum()),
        "empty B": int((b.str.strip() == "").sum()),
        "rows where tracks differ": int((a != b).sum()),
        "% differing": round(100 * (a != b).mean(), 1),
    })
quality = pd.DataFrame(check)
display(quality)

print("The '% differing' column is the share of rows the manipulation can act on;")
print("it should track the emoji density measured in notebook 02.")

# Rows that became empty are almost always emoji-only tweets stripped by Track A.
empty_a = train_df[train_df["text_no_emoji"].str.strip() == ""]
if len(empty_a):
    print(f"\n{len(empty_a)} training rows are empty on Track A (emoji-only tweets).")
    display(empty_a[["text", "text_with_emoji"]].head(3))

,split,mean length A,mean length B,empty A,empty B,rows where tracks differ,% differing
0,train,82.4,86.4,0,0,825,12.1
1,dev,81.5,89.6,0,0,230,26.0
2,test,81.4,89.6,0,0,853,26.2

The '% differing' column is the share of rows the manipulation can act on;
it should track the emoji density measured in notebook 02.

In [26]:
SAVE_COLS = ["text", "text_no_emoji", "text_with_emoji"] + EMOTION_LABELS

for name, df in splits.items():
    out = PROCESSED / f"{name}_cleaned.csv"
    df[SAVE_COLS].to_csv(out, index=False, encoding="utf-8")
    print("saved", out)

# A small fixture so the serving copy of the pipeline can be checked for drift.
fixture = {"cases": [{"input": s,
                      "track_a": build_text(s, "no"),
                      "track_b": build_text(s, "yes")}
                     for s in [sample,
                               "waiting to hear back \U0001F630 fingers crossed",
                               "absolutely gutted about the result today"]]}
(RESULTS / "pipeline_fixture.json").write_text(
    json.dumps(fixture, indent=2, ensure_ascii=False), encoding="utf-8")
print("saved", RESULTS / "pipeline_fixture.json")

saved /kaggle/working/data/processed/train_cleaned.csv
saved /kaggle/working/data/processed/dev_cleaned.csv

saved /kaggle/working/data/processed/test_cleaned.csv
saved /kaggle/working/results/pipeline_fixture.json

## 3.3 Class imbalance

Notebook 02 established that positive instances differ by roughly an order of
magnitude across labels. An unweighted objective is minimised most efficiently by
predicting the negative class for rare emotions, so each label is weighted by its
own negative-to-positive ratio.

In [27]:
pos_counts = train_df[EMOTION_LABELS].sum().values.astype(np.float32)
pos_weight_values = (len(train_df) - pos_counts) / np.maximum(pos_counts, 1.0)
POS_WEIGHT = tf.constant(pos_weight_values, dtype=tf.float32)

display(pd.DataFrame({"emotion": EMOTION_LABELS,
                      "positives": pos_counts.astype(int),
                      "pos_weight": pos_weight_values.round(2)})
          .sort_values("pos_weight", ascending=False))


def weighted_bce(y_true, y_pred):
    """Binary cross-entropy on logits, weighted per label."""
    return tf.reduce_mean(tf.nn.weighted_cross_entropy_with_logits(
        labels=y_true, logits=y_pred, pos_weight=POS_WEIGHT))

         emotion  positives  pos_weight
10         trust        357   18.150000
9       surprise        361   17.940001
5           love        700    8.770000
7      pessimism        795    7.600000
1   anticipation        978    5.990000
3           fear       1242    4.510000
6       optimism       1984    2.450000
8        sadness       2008    2.410000
4            joy       2477    1.760000
0          anger       2544    1.690000
2        disgust       2602    1.630000

## 3.4 Data pipeline and model builders

In [28]:
def make_vectorizer(train_texts, max_tokens=MAX_TOKENS):
    """Adapted per track, so Track B's vocabulary includes description words."""
    vec = tf.keras.layers.TextVectorization(
        max_tokens=max_tokens, output_sequence_length=SEQUENCE_LENGTH,
        standardize=None)          # normalisation already done in the pipeline
    vec.adapt(train_texts.astype(str).values)
    return vec, len(vec.get_vocabulary())


def make_dataset(df, text_col, batch_size, shuffle=False):
    ds = tf.data.Dataset.from_tensor_slices((
        df[text_col].astype(str).values,
        df[EMOTION_LABELS].values.astype(np.float32)))
    if shuffle:
        ds = ds.shuffle(len(df), seed=SEED)
    return ds.batch(batch_size).prefetch(tf.data.AUTOTUNE)

In [29]:
def build_lstm(vectorizer, vocab_size, p):
    """Recurrent arm: two stacked BiLSTMs, tapering to the classification head."""
    inp = tf.keras.Input(shape=(), dtype=tf.string)
    x = vectorizer(inp)
    x = tf.keras.layers.Embedding(vocab_size, p["embed_dim"], mask_zero=True)(x)
    x = tf.keras.layers.Bidirectional(
        tf.keras.layers.LSTM(p["lstm_units"], return_sequences=True,
                             dropout=p["dropout"]))(x)
    x = tf.keras.layers.Bidirectional(
        tf.keras.layers.LSTM(p["lstm_units"] // 2, dropout=p["dropout"]))(x)
    x = tf.keras.layers.Dropout(p["dropout"])(x)
    out = tf.keras.layers.Dense(len(EMOTION_LABELS))(x)   # raw logits
    m = tf.keras.Model(inp, out)
    m.compile(optimizer=tf.keras.optimizers.Adam(p["lr"]), loss=weighted_bce)
    return m


def build_transformer(vectorizer, vocab_size, p):
    """Attention arm: one Transformer encoder block, trained from scratch."""
    inp = tf.keras.Input(shape=(), dtype=tf.string)
    x = vectorizer(inp)
    x = tf.keras.layers.Embedding(vocab_size, p["embed_dim"], mask_zero=True)(x)
    attn = tf.keras.layers.MultiHeadAttention(
        num_heads=p["num_heads"], key_dim=p["key_dim"])(x, x)
    x = tf.keras.layers.LayerNormalization()(tf.keras.layers.Add()([x, attn]))
    ff = tf.keras.layers.Dense(p["ff_dim"], activation="relu")(x)
    ff = tf.keras.layers.Dropout(p["dropout"])(ff)
    x = tf.keras.layers.LayerNormalization()(
        tf.keras.layers.Add()([x, tf.keras.layers.Dense(p["embed_dim"])(ff)]))
    x = tf.keras.layers.GlobalAveragePooling1D()(x)
    x = tf.keras.layers.Dropout(p["dropout"])(x)
    out = tf.keras.layers.Dense(len(EMOTION_LABELS))(x)   # raw logits
    m = tf.keras.Model(inp, out)
    m.compile(optimizer=tf.keras.optimizers.Adam(p["lr"]), loss=weighted_bce)
    return m

## 3.5 Prediction and threshold selection

The models emit **raw logits**, so the sigmoid is applied here. Keeping the
conventional 0.5 cut would systematically disadvantage rare labels under a
weighted loss, so the threshold is swept on the development split and the value
maximising Micro-F1 is adopted — applied identically in all four conditions, so it
cannot favour one track over the other.

In [30]:
def predict(model, ds, label_df, threshold=0.5):
    probs = tf.nn.sigmoid(model.predict(ds, verbose=0)).numpy()
    preds = (probs >= threshold).astype(int)
    return label_df[EMOTION_LABELS].values.astype(int), preds, probs


def best_threshold(y_true, y_prob):
    """Sweep 0.10 -> 0.55 and keep the value that maximises Micro-F1."""
    best_t, best_f1 = 0.5, 0.0
    for t in np.arange(0.1, 0.6, 0.05):
        f1 = f1_score(y_true, (y_prob >= t).astype(int),
                      average="micro", zero_division=0)
        if f1 > best_f1:
            best_f1, best_t = f1, float(t)
    return round(best_t, 2), best_f1

## 3.6 Hyper-parameter grids

In [31]:
LSTM_PARAM_GRID = [
    {"name": "cfg1", "embed_dim": 128, "lstm_units": 128, "lr": 1e-3, "dropout": 0.2, "batch_size": 64},
    {"name": "cfg2", "embed_dim": 256, "lstm_units": 256, "lr": 5e-4, "dropout": 0.3, "batch_size": 32},
    {"name": "cfg3", "embed_dim": 128, "lstm_units": 64,  "lr": 2e-3, "dropout": 0.1, "batch_size": 64},
]

TRANSFORMER_PARAM_GRID = [
    {"name": "cfg1", "embed_dim": 128, "num_heads": 4, "key_dim": 32, "ff_dim": 256, "lr": 1e-3, "dropout": 0.2, "batch_size": 64},
    {"name": "cfg2", "embed_dim": 256, "num_heads": 8, "key_dim": 32, "ff_dim": 512, "lr": 5e-4, "dropout": 0.3, "batch_size": 32},
    {"name": "cfg3", "embed_dim": 128, "num_heads": 2, "key_dim": 64, "ff_dim": 256, "lr": 2e-3, "dropout": 0.1, "batch_size": 64},
]

# cfg1 is a moderate baseline; cfg2 raises capacity while lowering the learning
# rate; cfg3 reduces capacity while raising it. The same budget is spent on all
# four conditions so the comparison stays fair.
print("configurations per condition:", len(LSTM_PARAM_GRID))

configurations per condition: 3

## 3.7 Two-phase training

**Phase 1** trains each configuration briefly and keeps the one with the best
development Micro-F1. **Phase 2** retrains that winner for longer. Early stopping
with best-weight restoration is active in both, so the evaluated model is always
the one at minimum validation loss rather than the one at the final epoch.

In [32]:
def search(build_fn, param_grid, text_col, epochs):
    """Phase 1 - returns (per-config results, best params)."""
    rows, best_score, best_params = [], -1, None

    for params in param_grid:
        print(f"    {params['name']}: lr={params['lr']} embed={params['embed_dim']} "
              f"batch={params['batch_size']}", flush=True)
        tf.keras.backend.clear_session()
        vec, vocab = make_vectorizer(train_df[text_col])
        model = build_fn(vec, vocab, params)
        model.fit(make_dataset(train_df, text_col, params["batch_size"], shuffle=True),
                  validation_data=make_dataset(dev_df, text_col, params["batch_size"]),
                  epochs=epochs, verbose=0,
                  callbacks=[tf.keras.callbacks.EarlyStopping(
                      monitor="val_loss", patience=2, restore_best_weights=True)])

        val_ds = make_dataset(dev_df, text_col, params["batch_size"])
        y_true, _, y_prob = predict(model, val_ds, dev_df)
        thr, _ = best_threshold(y_true, y_prob)
        _, y_pred, _ = predict(model, val_ds, dev_df, thr)

        micro = f1_score(y_true, y_pred, average="micro", zero_division=0)
        macro = f1_score(y_true, y_pred, average="macro", zero_division=0)
        rows.append({"config": params["name"],
                     "micro_f1": round(micro * 100, 2),
                     "macro_f1": round(macro * 100, 2),
                     "label_accuracy": round((y_true == y_pred).mean() * 100, 2),
                     "threshold": thr})
        print(f"      -> Micro-F1 {micro * 100:.2f}%")

        if micro > best_score:
            best_score, best_params = micro, params

    return pd.DataFrame(rows), best_params

In [33]:
tuning_log, thresholds, best_configs = [], {}, {}

for model_name, build_fn, grid in [
    ("LSTM", build_lstm, LSTM_PARAM_GRID),
    ("BERT", build_transformer, TRANSFORMER_PARAM_GRID),   # file name kept; see note
]:
    label = "BiLSTM" if model_name == "LSTM" else "Transformer"
    print(f"\n{'=' * 62}\n  {label}\n{'=' * 62}")

    for track_key, text_col, track_label in TRACKS:
        print(f"\n--- {label} | {track_label} ---")

        print("  Phase 1: hyper-parameter search")
        search_df, best_params = search(build_fn, grid, text_col, SEARCH_EPOCHS)
        search_df["model"], search_df["track"] = model_name, track_label
        tuning_log.append(search_df)
        display(search_df)
        print(f"  best config: {best_params['name']}")

        print("  Phase 2: final training")
        tf.keras.backend.clear_session()
        vec, vocab = make_vectorizer(train_df[text_col])
        model = build_fn(vec, vocab, best_params)
        model.fit(make_dataset(train_df, text_col, best_params["batch_size"], shuffle=True),
                  validation_data=make_dataset(dev_df, text_col, best_params["batch_size"]),
                  epochs=FINAL_EPOCHS, verbose=1,
                  callbacks=[tf.keras.callbacks.EarlyStopping(
                      monitor="val_loss", patience=3, restore_best_weights=True)])

        val_ds = make_dataset(dev_df, text_col, best_params["batch_size"])
        y_true, _, y_prob = predict(model, val_ds, dev_df)
        thr, micro = best_threshold(y_true, y_prob)

        key = f"{model_name}_{track_key}"
        thresholds[key] = thr
        best_configs[key] = best_params
        model.save(MODELS / f"{model_name.lower()}_{track_key}.keras")

        print(f"  saved {MODELS / f'{model_name.lower()}_{track_key}.keras'}")
        print(f"  threshold {thr:.2f} | dev Micro-F1 {micro * 100:.2f}%")

==============================================================
  BiLSTM
==============================================================

--- BiLSTM | Without Emoji ---
  Phase 1: hyper-parameter search
    cfg1: lr=0.001 embed=128 batch=64

      -> Micro-F1 52.31%
    cfg2: lr=0.0005 embed=256 batch=32

      -> Micro-F1 54.49%
    cfg3: lr=0.002 embed=128 batch=64

      -> Micro-F1 54.66%

  config  micro_f1  macro_f1  label_accuracy  threshold model          track
0   cfg1     52.31     46.39           73.15       0.55  LSTM  Without Emoji
1   cfg2     54.49     48.88           75.71       0.55  LSTM  Without Emoji
2   cfg3     54.66     49.06           75.64       0.55  LSTM  Without Emoji

  best config: cfg3
  Phase 2: final training

Epoch 1/10

  1/107 ━━━━━━━━━━━━━━━━━━━━ 17:54 10s/step - loss: 1.1094

  2/107 ━━━━━━━━━━━━━━━━━━━━ 32s 314ms/step - loss: 1.1145

  3/107 ━━━━━━━━━━━━━━━━━━━━ 31s 306ms/step - loss: 1.1117

  4/107 ━━━━━━━━━━━━━━━━━━━━ 31s 306ms/step - loss: 1.1099

  5/107 ━━━━━━━━━━━━━━━━━━━━ 31s 309ms/step - loss: 1.1091

  6/107 ━━━━━━━━━━━━━━━━━━━━ 31s 316ms/step - loss: 1.1081

  7/107 ━━━━━━━━━━━━━━━━━━━━ 31s 315ms/step - loss: 1.1081

  8/107 ━━━━━━━━━━━━━━━━━━━━ 31s 315ms/step - loss: 1.1086

  9/107 ━━━━━━━━━━━━━━━━━━━━ 30s 313ms/step - loss: 1.1093

 10/107 ━━━━━━━━━━━━━━━━━━━━ 30s 311ms/step - loss: 1.1102

 11/107 ━━━━━━━━━━━━━━━━━━━━ 29s 310ms/step - loss: 1.1107

 12/107 ━━━━━━━━━━━━━━━━━━━━ 29s 309ms/step - loss: 1.1110

 13/107 ━━━━━━━━━━━━━━━━━━━━ 28s 307ms/step - loss: 1.1107

 14/107 ━━━━━━━━━━━━━━━━━━━━ 28s 306ms/step - loss: 1.1103

 15/107 ━━━━━━━━━━━━━━━━━━━━ 28s 306ms/step - loss: 1.1100

 16/107 ━━━━━━━━━━━━━━━━━━━━ 27s 305ms/step - loss: 1.1099

 17/107 ━━━━━━━━━━━━━━━━━━━━ 27s 305ms/step - loss: 1.1094

 18/107 ━━━━━━━━━━━━━━━━━━━━ 27s 304ms/step - loss: 1.1089

 19/107 ━━━━━━━━━━━━━━━━━━━━ 26s 304ms/step - loss: 1.1082

 20/107 ━━━━━━━━━━━━━━━━━━━━ 26s 303ms/step - loss: 1.1075

 21/107 ━━━━━━━━━━━━━━━━━━━━ 26s 303ms/step - loss: 1.1069

 22/107 ━━━━━━━━━━━━━━━━━━━━ 25s 302ms/step - loss: 1.1062

 23/107 ━━━━━━━━━━━━━━━━━━━━ 25s 302ms/step - loss: 1.1055

 24/107 ━━━━━━━━━━━━━━━━━━━━ 25s 302ms/step - loss: 1.1048

 25/107 ━━━━━━━━━━━━━━━━━━━━ 24s 301ms/step - loss: 1.1043

 26/107 ━━━━━━━━━━━━━━━━━━━━ 24s 301ms/step - loss: 1.1038

 27/107 ━━━━━━━━━━━━━━━━━━━━ 24s 301ms/step - loss: 1.1035

 28/107 ━━━━━━━━━━━━━━━━━━━━ 23s 301ms/step - loss: 1.1030

 29/107 ━━━━━━━━━━━━━━━━━━━━ 23s 301ms/step - loss: 1.1024

 30/107 ━━━━━━━━━━━━━━━━━━━━ 23s 302ms/step - loss: 1.1020

 31/107 ━━━━━━━━━━━━━━━━━━━━ 22s 302ms/step - loss: 1.1015

 32/107 ━━━━━━━━━━━━━━━━━━━━ 22s 303ms/step - loss: 1.1011

 33/107 ━━━━━━━━━━━━━━━━━━━━ 22s 303ms/step - loss: 1.1006

 34/107 ━━━━━━━━━━━━━━━━━━━━ 22s 303ms/step - loss: 1.1001

 35/107 ━━━━━━━━━━━━━━━━━━━━ 21s 302ms/step - loss: 1.0996

 36/107 ━━━━━━━━━━━━━━━━━━━━ 21s 302ms/step - loss: 1.0991

 37/107 ━━━━━━━━━━━━━━━━━━━━ 21s 302ms/step - loss: 1.0985

 38/107 ━━━━━━━━━━━━━━━━━━━━ 20s 302ms/step - loss: 1.0979

 39/107 ━━━━━━━━━━━━━━━━━━━━ 20s 303ms/step - loss: 1.0972

 40/107 ━━━━━━━━━━━━━━━━━━━━ 20s 303ms/step - loss: 1.0965

 41/107 ━━━━━━━━━━━━━━━━━━━━ 20s 303ms/step - loss: 1.0957

 42/107 ━━━━━━━━━━━━━━━━━━━━ 19s 303ms/step - loss: 1.0950

 43/107 ━━━━━━━━━━━━━━━━━━━━ 19s 303ms/step - loss: 1.0942

 44/107 ━━━━━━━━━━━━━━━━━━━━ 19s 304ms/step - loss: 1.0935

 45/107 ━━━━━━━━━━━━━━━━━━━━ 18s 304ms/step - loss: 1.0927

 46/107 ━━━━━━━━━━━━━━━━━━━━ 18s 303ms/step - loss: 1.0919

 47/107 ━━━━━━━━━━━━━━━━━━━━ 18s 304ms/step - loss: 1.0913

 48/107 ━━━━━━━━━━━━━━━━━━━━ 17s 304ms/step - loss: 1.0906

 49/107 ━━━━━━━━━━━━━━━━━━━━ 17s 304ms/step - loss: 1.0899

 50/107 ━━━━━━━━━━━━━━━━━━━━ 17s 305ms/step - loss: 1.0892

 51/107 ━━━━━━━━━━━━━━━━━━━━ 17s 305ms/step - loss: 1.0886

 52/107 ━━━━━━━━━━━━━━━━━━━━ 16s 304ms/step - loss: 1.0879

 53/107 ━━━━━━━━━━━━━━━━━━━━ 16s 305ms/step - loss: 1.0873

 54/107 ━━━━━━━━━━━━━━━━━━━━ 16s 305ms/step - loss: 1.0867

 55/107 ━━━━━━━━━━━━━━━━━━━━ 15s 305ms/step - loss: 1.0861

 56/107 ━━━━━━━━━━━━━━━━━━━━ 15s 305ms/step - loss: 1.0855

 57/107 ━━━━━━━━━━━━━━━━━━━━ 15s 305ms/step - loss: 1.0849

 58/107 ━━━━━━━━━━━━━━━━━━━━ 14s 305ms/step - loss: 1.0844

 59/107 ━━━━━━━━━━━━━━━━━━━━ 14s 305ms/step - loss: 1.0838

 60/107 ━━━━━━━━━━━━━━━━━━━━ 14s 305ms/step - loss: 1.0833

 61/107 ━━━━━━━━━━━━━━━━━━━━ 14s 305ms/step - loss: 1.0827

 62/107 ━━━━━━━━━━━━━━━━━━━━ 13s 305ms/step - loss: 1.0821

 63/107 ━━━━━━━━━━━━━━━━━━━━ 13s 306ms/step - loss: 1.0816

 64/107 ━━━━━━━━━━━━━━━━━━━━ 13s 306ms/step - loss: 1.0810

 65/107 ━━━━━━━━━━━━━━━━━━━━ 12s 305ms/step - loss: 1.0804

 66/107 ━━━━━━━━━━━━━━━━━━━━ 12s 305ms/step - loss: 1.0798

 67/107 ━━━━━━━━━━━━━━━━━━━━ 12s 305ms/step - loss: 1.0792

 68/107 ━━━━━━━━━━━━━━━━━━━━ 11s 305ms/step - loss: 1.0787

 69/107 ━━━━━━━━━━━━━━━━━━━━ 11s 305ms/step - loss: 1.0781

 70/107 ━━━━━━━━━━━━━━━━━━━━ 11s 305ms/step - loss: 1.0775

 71/107 ━━━━━━━━━━━━━━━━━━━━ 10s 305ms/step - loss: 1.0769

 72/107 ━━━━━━━━━━━━━━━━━━━━ 10s 306ms/step - loss: 1.0763

 73/107 ━━━━━━━━━━━━━━━━━━━━ 10s 306ms/step - loss: 1.0757

 74/107 ━━━━━━━━━━━━━━━━━━━━ 10s 306ms/step - loss: 1.0752

 75/107 ━━━━━━━━━━━━━━━━━━━━ 9s 306ms/step - loss: 1.0747

 76/107 ━━━━━━━━━━━━━━━━━━━━ 9s 306ms/step - loss: 1.0742

 77/107 ━━━━━━━━━━━━━━━━━━━━ 9s 306ms/step - loss: 1.0737

 78/107 ━━━━━━━━━━━━━━━━━━━━ 8s 306ms/step - loss: 1.0732

 79/107 ━━━━━━━━━━━━━━━━━━━━ 8s 306ms/step - loss: 1.0727

 80/107 ━━━━━━━━━━━━━━━━━━━━ 8s 307ms/step - loss: 1.0722

 81/107 ━━━━━━━━━━━━━━━━━━━━ 7s 307ms/step - loss: 1.0717

 82/107 ━━━━━━━━━━━━━━━━━━━━ 7s 307ms/step - loss: 1.0712

 83/107 ━━━━━━━━━━━━━━━━━━━━ 7s 307ms/step - loss: 1.0707

 84/107 ━━━━━━━━━━━━━━━━━━━━ 7s 307ms/step - loss: 1.0702

 85/107 ━━━━━━━━━━━━━━━━━━━━ 6s 307ms/step - loss: 1.0697

 86/107 ━━━━━━━━━━━━━━━━━━━━ 6s 307ms/step - loss: 1.0692

 87/107 ━━━━━━━━━━━━━━━━━━━━ 6s 307ms/step - loss: 1.0687

 88/107 ━━━━━━━━━━━━━━━━━━━━ 5s 307ms/step - loss: 1.0682

 89/107 ━━━━━━━━━━━━━━━━━━━━ 5s 307ms/step - loss: 1.0677

 90/107 ━━━━━━━━━━━━━━━━━━━━ 5s 307ms/step - loss: 1.0672

 91/107 ━━━━━━━━━━━━━━━━━━━━ 4s 307ms/step - loss: 1.0668

 92/107 ━━━━━━━━━━━━━━━━━━━━ 4s 307ms/step - loss: 1.0663

 93/107 ━━━━━━━━━━━━━━━━━━━━ 4s 306ms/step - loss: 1.0658

 94/107 ━━━━━━━━━━━━━━━━━━━━ 3s 306ms/step - loss: 1.0653

 95/107 ━━━━━━━━━━━━━━━━━━━━ 3s 306ms/step - loss: 1.0647

 96/107 ━━━━━━━━━━━━━━━━━━━━ 3s 306ms/step - loss: 1.0642

 97/107 ━━━━━━━━━━━━━━━━━━━━ 3s 306ms/step - loss: 1.0637

 98/107 ━━━━━━━━━━━━━━━━━━━━ 2s 306ms/step - loss: 1.0632

 99/107 ━━━━━━━━━━━━━━━━━━━━ 2s 306ms/step - loss: 1.0627

100/107 ━━━━━━━━━━━━━━━━━━━━ 2s 306ms/step - loss: 1.0622

101/107 ━━━━━━━━━━━━━━━━━━━━ 1s 306ms/step - loss: 1.0616

102/107 ━━━━━━━━━━━━━━━━━━━━ 1s 306ms/step - loss: 1.0611

103/107 ━━━━━━━━━━━━━━━━━━━━ 1s 306ms/step - loss: 1.0606

104/107 ━━━━━━━━━━━━━━━━━━━━ 0s 306ms/step - loss: 1.0601

105/107 ━━━━━━━━━━━━━━━━━━━━ 0s 306ms/step - loss: 1.0596

106/107 ━━━━━━━━━━━━━━━━━━━━ 0s 306ms/step - loss: 1.0591

107/107 ━━━━━━━━━━━━━━━━━━━━ 0s 306ms/step - loss: 1.0586

107/107 ━━━━━━━━━━━━━━━━━━━━ 45s 326ms/step - loss: 1.0058 - val_loss: 0.9083

Epoch 2/10

  1/107 ━━━━━━━━━━━━━━━━━━━━ 35s 334ms/step - loss: 0.7755

  2/107 ━━━━━━━━━━━━━━━━━━━━ 32s 307ms/step - loss: 0.7880

  3/107 ━━━━━━━━━━━━━━━━━━━━ 31s 305ms/step - loss: 0.7948

  4/107 ━━━━━━━━━━━━━━━━━━━━ 31s 305ms/step - loss: 0.7995

  5/107 ━━━━━━━━━━━━━━━━━━━━ 31s 304ms/step - loss: 0.8040

  6/107 ━━━━━━━━━━━━━━━━━━━━ 30s 303ms/step - loss: 0.8060

  7/107 ━━━━━━━━━━━━━━━━━━━━ 30s 304ms/step - loss: 0.8073

  8/107 ━━━━━━━━━━━━━━━━━━━━ 30s 305ms/step - loss: 0.8076

  9/107 ━━━━━━━━━━━━━━━━━━━━ 29s 306ms/step - loss: 0.8078

 10/107 ━━━━━━━━━━━━━━━━━━━━ 29s 305ms/step - loss: 0.8081

 11/107 ━━━━━━━━━━━━━━━━━━━━ 29s 304ms/step - loss: 0.8081

 12/107 ━━━━━━━━━━━━━━━━━━━━ 28s 303ms/step - loss: 0.8077

 13/107 ━━━━━━━━━━━━━━━━━━━━ 28s 303ms/step - loss: 0.8072

 14/107 ━━━━━━━━━━━━━━━━━━━━ 28s 304ms/step - loss: 0.8069

 15/107 ━━━━━━━━━━━━━━━━━━━━ 27s 304ms/step - loss: 0.8065

 16/107 ━━━━━━━━━━━━━━━━━━━━ 27s 304ms/step - loss: 0.8062

 17/107 ━━━━━━━━━━━━━━━━━━━━ 27s 303ms/step - loss: 0.8060

 18/107 ━━━━━━━━━━━━━━━━━━━━ 26s 303ms/step - loss: 0.8056

 19/107 ━━━━━━━━━━━━━━━━━━━━ 26s 303ms/step - loss: 0.8052

 20/107 ━━━━━━━━━━━━━━━━━━━━ 26s 302ms/step - loss: 0.8047

 21/107 ━━━━━━━━━━━━━━━━━━━━ 25s 301ms/step - loss: 0.8043

 22/107 ━━━━━━━━━━━━━━━━━━━━ 25s 301ms/step - loss: 0.8041

 23/107 ━━━━━━━━━━━━━━━━━━━━ 25s 304ms/step - loss: 0.8040

 24/107 ━━━━━━━━━━━━━━━━━━━━ 25s 304ms/step - loss: 0.8039

 25/107 ━━━━━━━━━━━━━━━━━━━━ 24s 304ms/step - loss: 0.8039

 26/107 ━━━━━━━━━━━━━━━━━━━━ 24s 303ms/step - loss: 0.8038

 27/107 ━━━━━━━━━━━━━━━━━━━━ 24s 303ms/step - loss: 0.8038

 28/107 ━━━━━━━━━━━━━━━━━━━━ 23s 303ms/step - loss: 0.8037

 29/107 ━━━━━━━━━━━━━━━━━━━━ 23s 303ms/step - loss: 0.8035

 30/107 ━━━━━━━━━━━━━━━━━━━━ 23s 302ms/step - loss: 0.8033

 31/107 ━━━━━━━━━━━━━━━━━━━━ 22s 302ms/step - loss: 0.8031

 32/107 ━━━━━━━━━━━━━━━━━━━━ 22s 302ms/step - loss: 0.8028

 33/107 ━━━━━━━━━━━━━━━━━━━━ 22s 302ms/step - loss: 0.8026

 34/107 ━━━━━━━━━━━━━━━━━━━━ 22s 301ms/step - loss: 0.8024

 35/107 ━━━━━━━━━━━━━━━━━━━━ 21s 301ms/step - loss: 0.8021

 36/107 ━━━━━━━━━━━━━━━━━━━━ 21s 301ms/step - loss: 0.8018

 37/107 ━━━━━━━━━━━━━━━━━━━━ 21s 300ms/step - loss: 0.8017

 38/107 ━━━━━━━━━━━━━━━━━━━━ 20s 300ms/step - loss: 0.8015

 39/107 ━━━━━━━━━━━━━━━━━━━━ 20s 300ms/step - loss: 0.8013

 40/107 ━━━━━━━━━━━━━━━━━━━━ 20s 299ms/step - loss: 0.8011

 41/107 ━━━━━━━━━━━━━━━━━━━━ 19s 299ms/step - loss: 0.8009

 42/107 ━━━━━━━━━━━━━━━━━━━━ 19s 299ms/step - loss: 0.8007

 43/107 ━━━━━━━━━━━━━━━━━━━━ 19s 298ms/step - loss: 0.8004

 44/107 ━━━━━━━━━━━━━━━━━━━━ 18s 298ms/step - loss: 0.8002

 45/107 ━━━━━━━━━━━━━━━━━━━━ 18s 298ms/step - loss: 0.7999

 46/107 ━━━━━━━━━━━━━━━━━━━━ 18s 298ms/step - loss: 0.7997

 47/107 ━━━━━━━━━━━━━━━━━━━━ 17s 298ms/step - loss: 0.7994

 48/107 ━━━━━━━━━━━━━━━━━━━━ 17s 298ms/step - loss: 0.7991

 49/107 ━━━━━━━━━━━━━━━━━━━━ 17s 298ms/step - loss: 0.7989

 50/107 ━━━━━━━━━━━━━━━━━━━━ 16s 298ms/step - loss: 0.7987

 51/107 ━━━━━━━━━━━━━━━━━━━━ 16s 298ms/step - loss: 0.7985

 52/107 ━━━━━━━━━━━━━━━━━━━━ 16s 298ms/step - loss: 0.7982

 53/107 ━━━━━━━━━━━━━━━━━━━━ 16s 298ms/step - loss: 0.7980

 54/107 ━━━━━━━━━━━━━━━━━━━━ 15s 298ms/step - loss: 0.7977

 55/107 ━━━━━━━━━━━━━━━━━━━━ 15s 298ms/step - loss: 0.7975

 56/107 ━━━━━━━━━━━━━━━━━━━━ 15s 298ms/step - loss: 0.7973

 57/107 ━━━━━━━━━━━━━━━━━━━━ 14s 299ms/step - loss: 0.7971

 58/107 ━━━━━━━━━━━━━━━━━━━━ 14s 299ms/step - loss: 0.7969

 59/107 ━━━━━━━━━━━━━━━━━━━━ 14s 299ms/step - loss: 0.7967

 60/107 ━━━━━━━━━━━━━━━━━━━━ 14s 299ms/step - loss: 0.7965

 61/107 ━━━━━━━━━━━━━━━━━━━━ 13s 299ms/step - loss: 0.7963

 62/107 ━━━━━━━━━━━━━━━━━━━━ 13s 299ms/step - loss: 0.7961

 63/107 ━━━━━━━━━━━━━━━━━━━━ 13s 299ms/step - loss: 0.7960

 64/107 ━━━━━━━━━━━━━━━━━━━━ 12s 299ms/step - loss: 0.7958

 65/107 ━━━━━━━━━━━━━━━━━━━━ 12s 299ms/step - loss: 0.7956

 66/107 ━━━━━━━━━━━━━━━━━━━━ 12s 299ms/step - loss: 0.7954

 67/107 ━━━━━━━━━━━━━━━━━━━━ 11s 299ms/step - loss: 0.7952

 68/107 ━━━━━━━━━━━━━━━━━━━━ 11s 299ms/step - loss: 0.7950

 69/107 ━━━━━━━━━━━━━━━━━━━━ 11s 299ms/step - loss: 0.7948

 70/107 ━━━━━━━━━━━━━━━━━━━━ 11s 298ms/step - loss: 0.7946

 71/107 ━━━━━━━━━━━━━━━━━━━━ 10s 298ms/step - loss: 0.7944

 72/107 ━━━━━━━━━━━━━━━━━━━━ 10s 298ms/step - loss: 0.7942

 73/107 ━━━━━━━━━━━━━━━━━━━━ 10s 298ms/step - loss: 0.7940

 74/107 ━━━━━━━━━━━━━━━━━━━━ 9s 298ms/step - loss: 0.7938

 75/107 ━━━━━━━━━━━━━━━━━━━━ 9s 298ms/step - loss: 0.7936

 76/107 ━━━━━━━━━━━━━━━━━━━━ 9s 298ms/step - loss: 0.7934

 77/107 ━━━━━━━━━━━━━━━━━━━━ 8s 298ms/step - loss: 0.7933

 78/107 ━━━━━━━━━━━━━━━━━━━━ 8s 298ms/step - loss: 0.7931

 79/107 ━━━━━━━━━━━━━━━━━━━━ 8s 298ms/step - loss: 0.7930

 80/107 ━━━━━━━━━━━━━━━━━━━━ 8s 298ms/step - loss: 0.7928

 81/107 ━━━━━━━━━━━━━━━━━━━━ 7s 298ms/step - loss: 0.7927

 82/107 ━━━━━━━━━━━━━━━━━━━━ 7s 298ms/step - loss: 0.7926

 83/107 ━━━━━━━━━━━━━━━━━━━━ 7s 298ms/step - loss: 0.7924

 84/107 ━━━━━━━━━━━━━━━━━━━━ 6s 298ms/step - loss: 0.7923

 85/107 ━━━━━━━━━━━━━━━━━━━━ 6s 298ms/step - loss: 0.7921

 86/107 ━━━━━━━━━━━━━━━━━━━━ 6s 298ms/step - loss: 0.7920

 87/107 ━━━━━━━━━━━━━━━━━━━━ 5s 298ms/step - loss: 0.7919

 88/107 ━━━━━━━━━━━━━━━━━━━━ 5s 298ms/step - loss: 0.7918

 89/107 ━━━━━━━━━━━━━━━━━━━━ 5s 298ms/step - loss: 0.7917

 90/107 ━━━━━━━━━━━━━━━━━━━━ 5s 299ms/step - loss: 0.7916

 91/107 ━━━━━━━━━━━━━━━━━━━━ 4s 299ms/step - loss: 0.7915

 92/107 ━━━━━━━━━━━━━━━━━━━━ 4s 299ms/step - loss: 0.7914

 93/107 ━━━━━━━━━━━━━━━━━━━━ 4s 299ms/step - loss: 0.7913

 94/107 ━━━━━━━━━━━━━━━━━━━━ 3s 299ms/step - loss: 0.7912

 95/107 ━━━━━━━━━━━━━━━━━━━━ 3s 299ms/step - loss: 0.7911

 96/107 ━━━━━━━━━━━━━━━━━━━━ 3s 299ms/step - loss: 0.7910

 97/107 ━━━━━━━━━━━━━━━━━━━━ 2s 299ms/step - loss: 0.7909

 98/107 ━━━━━━━━━━━━━━━━━━━━ 2s 299ms/step - loss: 0.7908

 99/107 ━━━━━━━━━━━━━━━━━━━━ 2s 299ms/step - loss: 0.7907

100/107 ━━━━━━━━━━━━━━━━━━━━ 2s 299ms/step - loss: 0.7906

101/107 ━━━━━━━━━━━━━━━━━━━━ 1s 299ms/step - loss: 0.7905

102/107 ━━━━━━━━━━━━━━━━━━━━ 1s 299ms/step - loss: 0.7904

103/107 ━━━━━━━━━━━━━━━━━━━━ 1s 299ms/step - loss: 0.7903

104/107 ━━━━━━━━━━━━━━━━━━━━ 0s 299ms/step - loss: 0.7902

105/107 ━━━━━━━━━━━━━━━━━━━━ 0s 298ms/step - loss: 0.7901

106/107 ━━━━━━━━━━━━━━━━━━━━ 0s 298ms/step - loss: 0.7900

107/107 ━━━━━━━━━━━━━━━━━━━━ 0s 298ms/step - loss: 0.7899

107/107 ━━━━━━━━━━━━━━━━━━━━ 33s 310ms/step - loss: 0.7790 - val_loss: 0.8677

Epoch 3/10

  1/107 ━━━━━━━━━━━━━━━━━━━━ 33s 312ms/step - loss: 0.6031

  2/107 ━━━━━━━━━━━━━━━━━━━━ 30s 290ms/step - loss: 0.6161

  3/107 ━━━━━━━━━━━━━━━━━━━━ 30s 294ms/step - loss: 0.6111

  4/107 ━━━━━━━━━━━━━━━━━━━━ 30s 297ms/step - loss: 0.6058

  5/107 ━━━━━━━━━━━━━━━━━━━━ 30s 298ms/step - loss: 0.6062

  6/107 ━━━━━━━━━━━━━━━━━━━━ 29s 297ms/step - loss: 0.6073

  7/107 ━━━━━━━━━━━━━━━━━━━━ 29s 296ms/step - loss: 0.6075

  8/107 ━━━━━━━━━━━━━━━━━━━━ 29s 295ms/step - loss: 0.6076

  9/107 ━━━━━━━━━━━━━━━━━━━━ 28s 295ms/step - loss: 0.6092

 10/107 ━━━━━━━━━━━━━━━━━━━━ 28s 294ms/step - loss: 0.6105

 11/107 ━━━━━━━━━━━━━━━━━━━━ 28s 294ms/step - loss: 0.6119

 12/107 ━━━━━━━━━━━━━━━━━━━━ 28s 295ms/step - loss: 0.6130

 13/107 ━━━━━━━━━━━━━━━━━━━━ 28s 298ms/step - loss: 0.6137

 14/107 ━━━━━━━━━━━━━━━━━━━━ 27s 298ms/step - loss: 0.6144

 15/107 ━━━━━━━━━━━━━━━━━━━━ 27s 297ms/step - loss: 0.6149

 16/107 ━━━━━━━━━━━━━━━━━━━━ 27s 297ms/step - loss: 0.6152

 17/107 ━━━━━━━━━━━━━━━━━━━━ 26s 297ms/step - loss: 0.6153

 18/107 ━━━━━━━━━━━━━━━━━━━━ 26s 297ms/step - loss: 0.6153

 19/107 ━━━━━━━━━━━━━━━━━━━━ 26s 297ms/step - loss: 0.6156

 20/107 ━━━━━━━━━━━━━━━━━━━━ 25s 296ms/step - loss: 0.6159

 21/107 ━━━━━━━━━━━━━━━━━━━━ 25s 296ms/step - loss: 0.6162

 22/107 ━━━━━━━━━━━━━━━━━━━━ 25s 296ms/step - loss: 0.6165

 23/107 ━━━━━━━━━━━━━━━━━━━━ 24s 296ms/step - loss: 0.6169

 24/107 ━━━━━━━━━━━━━━━━━━━━ 24s 296ms/step - loss: 0.6174

 25/107 ━━━━━━━━━━━━━━━━━━━━ 24s 295ms/step - loss: 0.6177

 26/107 ━━━━━━━━━━━━━━━━━━━━ 23s 295ms/step - loss: 0.6179

 27/107 ━━━━━━━━━━━━━━━━━━━━ 23s 295ms/step - loss: 0.6181

 28/107 ━━━━━━━━━━━━━━━━━━━━ 23s 295ms/step - loss: 0.6181

 29/107 ━━━━━━━━━━━━━━━━━━━━ 22s 295ms/step - loss: 0.6181

 30/107 ━━━━━━━━━━━━━━━━━━━━ 22s 294ms/step - loss: 0.6180

 31/107 ━━━━━━━━━━━━━━━━━━━━ 22s 294ms/step - loss: 0.6180

 32/107 ━━━━━━━━━━━━━━━━━━━━ 22s 294ms/step - loss: 0.6178

 33/107 ━━━━━━━━━━━━━━━━━━━━ 21s 294ms/step - loss: 0.6177

 34/107 ━━━━━━━━━━━━━━━━━━━━ 21s 294ms/step - loss: 0.6175

 35/107 ━━━━━━━━━━━━━━━━━━━━ 21s 294ms/step - loss: 0.6174

 36/107 ━━━━━━━━━━━━━━━━━━━━ 20s 294ms/step - loss: 0.6173

 37/107 ━━━━━━━━━━━━━━━━━━━━ 20s 294ms/step - loss: 0.6172

 38/107 ━━━━━━━━━━━━━━━━━━━━ 20s 294ms/step - loss: 0.6171

 39/107 ━━━━━━━━━━━━━━━━━━━━ 20s 294ms/step - loss: 0.6170

 40/107 ━━━━━━━━━━━━━━━━━━━━ 19s 294ms/step - loss: 0.6170

 41/107 ━━━━━━━━━━━━━━━━━━━━ 19s 294ms/step - loss: 0.6170

 42/107 ━━━━━━━━━━━━━━━━━━━━ 19s 294ms/step - loss: 0.6170

 43/107 ━━━━━━━━━━━━━━━━━━━━ 18s 294ms/step - loss: 0.6170

 44/107 ━━━━━━━━━━━━━━━━━━━━ 18s 294ms/step - loss: 0.6170

 45/107 ━━━━━━━━━━━━━━━━━━━━ 18s 294ms/step - loss: 0.6169

 46/107 ━━━━━━━━━━━━━━━━━━━━ 17s 294ms/step - loss: 0.6169

 47/107 ━━━━━━━━━━━━━━━━━━━━ 17s 295ms/step - loss: 0.6169

 48/107 ━━━━━━━━━━━━━━━━━━━━ 17s 295ms/step - loss: 0.6168

 49/107 ━━━━━━━━━━━━━━━━━━━━ 17s 295ms/step - loss: 0.6167

 50/107 ━━━━━━━━━━━━━━━━━━━━ 16s 294ms/step - loss: 0.6166

 51/107 ━━━━━━━━━━━━━━━━━━━━ 16s 294ms/step - loss: 0.6164

 52/107 ━━━━━━━━━━━━━━━━━━━━ 16s 294ms/step - loss: 0.6162

 53/107 ━━━━━━━━━━━━━━━━━━━━ 15s 294ms/step - loss: 0.6160

 54/107 ━━━━━━━━━━━━━━━━━━━━ 15s 294ms/step - loss: 0.6159

 55/107 ━━━━━━━━━━━━━━━━━━━━ 15s 294ms/step - loss: 0.6157

 56/107 ━━━━━━━━━━━━━━━━━━━━ 14s 294ms/step - loss: 0.6154

 57/107 ━━━━━━━━━━━━━━━━━━━━ 14s 293ms/step - loss: 0.6152

 58/107 ━━━━━━━━━━━━━━━━━━━━ 14s 293ms/step - loss: 0.6150

 59/107 ━━━━━━━━━━━━━━━━━━━━ 14s 293ms/step - loss: 0.6148

 60/107 ━━━━━━━━━━━━━━━━━━━━ 13s 293ms/step - loss: 0.6147

 61/107 ━━━━━━━━━━━━━━━━━━━━ 13s 293ms/step - loss: 0.6145

 62/107 ━━━━━━━━━━━━━━━━━━━━ 13s 293ms/step - loss: 0.6144

 63/107 ━━━━━━━━━━━━━━━━━━━━ 12s 293ms/step - loss: 0.6143

 64/107 ━━━━━━━━━━━━━━━━━━━━ 12s 293ms/step - loss: 0.6142

 65/107 ━━━━━━━━━━━━━━━━━━━━ 12s 293ms/step - loss: 0.6141

 66/107 ━━━━━━━━━━━━━━━━━━━━ 12s 293ms/step - loss: 0.6140

 67/107 ━━━━━━━━━━━━━━━━━━━━ 11s 293ms/step - loss: 0.6139

 68/107 ━━━━━━━━━━━━━━━━━━━━ 11s 293ms/step - loss: 0.6137

 69/107 ━━━━━━━━━━━━━━━━━━━━ 11s 293ms/step - loss: 0.6136

 70/107 ━━━━━━━━━━━━━━━━━━━━ 10s 293ms/step - loss: 0.6135

 71/107 ━━━━━━━━━━━━━━━━━━━━ 10s 293ms/step - loss: 0.6134

 72/107 ━━━━━━━━━━━━━━━━━━━━ 10s 293ms/step - loss: 0.6133

 73/107 ━━━━━━━━━━━━━━━━━━━━ 9s 293ms/step - loss: 0.6133

 74/107 ━━━━━━━━━━━━━━━━━━━━ 9s 293ms/step - loss: 0.6132

 75/107 ━━━━━━━━━━━━━━━━━━━━ 9s 293ms/step - loss: 0.6132

 76/107 ━━━━━━━━━━━━━━━━━━━━ 9s 293ms/step - loss: 0.6131

 77/107 ━━━━━━━━━━━━━━━━━━━━ 8s 293ms/step - loss: 0.6131

 78/107 ━━━━━━━━━━━━━━━━━━━━ 8s 293ms/step - loss: 0.6131

 79/107 ━━━━━━━━━━━━━━━━━━━━ 8s 293ms/step - loss: 0.6130

 80/107 ━━━━━━━━━━━━━━━━━━━━ 7s 293ms/step - loss: 0.6130

 81/107 ━━━━━━━━━━━━━━━━━━━━ 7s 294ms/step - loss: 0.6129

 82/107 ━━━━━━━━━━━━━━━━━━━━ 7s 294ms/step - loss: 0.6129

 83/107 ━━━━━━━━━━━━━━━━━━━━ 7s 295ms/step - loss: 0.6128

 84/107 ━━━━━━━━━━━━━━━━━━━━ 6s 294ms/step - loss: 0.6127

 85/107 ━━━━━━━━━━━━━━━━━━━━ 6s 294ms/step - loss: 0.6127

 86/107 ━━━━━━━━━━━━━━━━━━━━ 6s 294ms/step - loss: 0.6126

 87/107 ━━━━━━━━━━━━━━━━━━━━ 5s 294ms/step - loss: 0.6125

 88/107 ━━━━━━━━━━━━━━━━━━━━ 5s 295ms/step - loss: 0.6125

 89/107 ━━━━━━━━━━━━━━━━━━━━ 5s 295ms/step - loss: 0.6124

 90/107 ━━━━━━━━━━━━━━━━━━━━ 5s 295ms/step - loss: 0.6124

 91/107 ━━━━━━━━━━━━━━━━━━━━ 4s 295ms/step - loss: 0.6123

 92/107 ━━━━━━━━━━━━━━━━━━━━ 4s 295ms/step - loss: 0.6123

 93/107 ━━━━━━━━━━━━━━━━━━━━ 4s 295ms/step - loss: 0.6122

 94/107 ━━━━━━━━━━━━━━━━━━━━ 3s 295ms/step - loss: 0.6122

 95/107 ━━━━━━━━━━━━━━━━━━━━ 3s 295ms/step - loss: 0.6122

 96/107 ━━━━━━━━━━━━━━━━━━━━ 3s 295ms/step - loss: 0.6121

 97/107 ━━━━━━━━━━━━━━━━━━━━ 2s 295ms/step - loss: 0.6121

 98/107 ━━━━━━━━━━━━━━━━━━━━ 2s 295ms/step - loss: 0.6120

 99/107 ━━━━━━━━━━━━━━━━━━━━ 2s 295ms/step - loss: 0.6120

100/107 ━━━━━━━━━━━━━━━━━━━━ 2s 295ms/step - loss: 0.6120

101/107 ━━━━━━━━━━━━━━━━━━━━ 1s 295ms/step - loss: 0.6120

102/107 ━━━━━━━━━━━━━━━━━━━━ 1s 294ms/step - loss: 0.6119

103/107 ━━━━━━━━━━━━━━━━━━━━ 1s 294ms/step - loss: 0.6119

104/107 ━━━━━━━━━━━━━━━━━━━━ 0s 294ms/step - loss: 0.6118

105/107 ━━━━━━━━━━━━━━━━━━━━ 0s 294ms/step - loss: 0.6118

106/107 ━━━━━━━━━━━━━━━━━━━━ 0s 294ms/step - loss: 0.6118

107/107 ━━━━━━━━━━━━━━━━━━━━ 0s 294ms/step - loss: 0.6118

107/107 ━━━━━━━━━━━━━━━━━━━━ 33s 306ms/step - loss: 0.6087 - val_loss: 0.9183

Epoch 4/10

  1/107 ━━━━━━━━━━━━━━━━━━━━ 31s 300ms/step - loss: 0.5375

  2/107 ━━━━━━━━━━━━━━━━━━━━ 30s 293ms/step - loss: 0.5190

  3/107 ━━━━━━━━━━━━━━━━━━━━ 31s 304ms/step - loss: 0.5110

  4/107 ━━━━━━━━━━━━━━━━━━━━ 31s 304ms/step - loss: 0.5086

  5/107 ━━━━━━━━━━━━━━━━━━━━ 30s 299ms/step - loss: 0.5071

  6/107 ━━━━━━━━━━━━━━━━━━━━ 29s 297ms/step - loss: 0.5067

  7/107 ━━━━━━━━━━━━━━━━━━━━ 29s 295ms/step - loss: 0.5059

  8/107 ━━━━━━━━━━━━━━━━━━━━ 29s 294ms/step - loss: 0.5054

  9/107 ━━━━━━━━━━━━━━━━━━━━ 28s 293ms/step - loss: 0.5044

 10/107 ━━━━━━━━━━━━━━━━━━━━ 28s 292ms/step - loss: 0.5033

 11/107 ━━━━━━━━━━━━━━━━━━━━ 27s 292ms/step - loss: 0.5026

 12/107 ━━━━━━━━━━━━━━━━━━━━ 27s 291ms/step - loss: 0.5017

 13/107 ━━━━━━━━━━━━━━━━━━━━ 27s 291ms/step - loss: 0.5006

 14/107 ━━━━━━━━━━━━━━━━━━━━ 27s 291ms/step - loss: 0.4999

 15/107 ━━━━━━━━━━━━━━━━━━━━ 26s 291ms/step - loss: 0.4995

 16/107 ━━━━━━━━━━━━━━━━━━━━ 26s 291ms/step - loss: 0.4993

 17/107 ━━━━━━━━━━━━━━━━━━━━ 26s 291ms/step - loss: 0.4991

 18/107 ━━━━━━━━━━━━━━━━━━━━ 25s 291ms/step - loss: 0.4989

 19/107 ━━━━━━━━━━━━━━━━━━━━ 25s 291ms/step - loss: 0.4985

 20/107 ━━━━━━━━━━━━━━━━━━━━ 25s 291ms/step - loss: 0.4982

 21/107 ━━━━━━━━━━━━━━━━━━━━ 24s 290ms/step - loss: 0.4978

 22/107 ━━━━━━━━━━━━━━━━━━━━ 24s 291ms/step - loss: 0.4975

 23/107 ━━━━━━━━━━━━━━━━━━━━ 24s 291ms/step - loss: 0.4973

 24/107 ━━━━━━━━━━━━━━━━━━━━ 24s 291ms/step - loss: 0.4970

 25/107 ━━━━━━━━━━━━━━━━━━━━ 23s 290ms/step - loss: 0.4967

 26/107 ━━━━━━━━━━━━━━━━━━━━ 23s 291ms/step - loss: 0.4963

 27/107 ━━━━━━━━━━━━━━━━━━━━ 23s 291ms/step - loss: 0.4960

 28/107 ━━━━━━━━━━━━━━━━━━━━ 22s 291ms/step - loss: 0.4956

 29/107 ━━━━━━━━━━━━━━━━━━━━ 22s 291ms/step - loss: 0.4953

 30/107 ━━━━━━━━━━━━━━━━━━━━ 22s 291ms/step - loss: 0.4950

 31/107 ━━━━━━━━━━━━━━━━━━━━ 22s 291ms/step - loss: 0.4947

 32/107 ━━━━━━━━━━━━━━━━━━━━ 21s 292ms/step - loss: 0.4944

 33/107 ━━━━━━━━━━━━━━━━━━━━ 21s 291ms/step - loss: 0.4939

 34/107 ━━━━━━━━━━━━━━━━━━━━ 21s 291ms/step - loss: 0.4936

 35/107 ━━━━━━━━━━━━━━━━━━━━ 20s 291ms/step - loss: 0.4934

 36/107 ━━━━━━━━━━━━━━━━━━━━ 20s 291ms/step - loss: 0.4932

 37/107 ━━━━━━━━━━━━━━━━━━━━ 20s 292ms/step - loss: 0.4930

 38/107 ━━━━━━━━━━━━━━━━━━━━ 20s 293ms/step - loss: 0.4927

 39/107 ━━━━━━━━━━━━━━━━━━━━ 19s 293ms/step - loss: 0.4925

 40/107 ━━━━━━━━━━━━━━━━━━━━ 19s 293ms/step - loss: 0.4923

 41/107 ━━━━━━━━━━━━━━━━━━━━ 19s 293ms/step - loss: 0.4922

 42/107 ━━━━━━━━━━━━━━━━━━━━ 19s 293ms/step - loss: 0.4920

 43/107 ━━━━━━━━━━━━━━━━━━━━ 18s 293ms/step - loss: 0.4919

 44/107 ━━━━━━━━━━━━━━━━━━━━ 18s 293ms/step - loss: 0.4918

 45/107 ━━━━━━━━━━━━━━━━━━━━ 18s 293ms/step - loss: 0.4917

 46/107 ━━━━━━━━━━━━━━━━━━━━ 17s 293ms/step - loss: 0.4915

 47/107 ━━━━━━━━━━━━━━━━━━━━ 17s 293ms/step - loss: 0.4914

 48/107 ━━━━━━━━━━━━━━━━━━━━ 17s 293ms/step - loss: 0.4913

 49/107 ━━━━━━━━━━━━━━━━━━━━ 16s 293ms/step - loss: 0.4912

 50/107 ━━━━━━━━━━━━━━━━━━━━ 16s 293ms/step - loss: 0.4910

 51/107 ━━━━━━━━━━━━━━━━━━━━ 16s 293ms/step - loss: 0.4909

 52/107 ━━━━━━━━━━━━━━━━━━━━ 16s 293ms/step - loss: 0.4908

 53/107 ━━━━━━━━━━━━━━━━━━━━ 15s 293ms/step - loss: 0.4907

 54/107 ━━━━━━━━━━━━━━━━━━━━ 15s 293ms/step - loss: 0.4906

 55/107 ━━━━━━━━━━━━━━━━━━━━ 15s 293ms/step - loss: 0.4905

 56/107 ━━━━━━━━━━━━━━━━━━━━ 14s 293ms/step - loss: 0.4904

 57/107 ━━━━━━━━━━━━━━━━━━━━ 14s 293ms/step - loss: 0.4903

 58/107 ━━━━━━━━━━━━━━━━━━━━ 14s 293ms/step - loss: 0.4901

 59/107 ━━━━━━━━━━━━━━━━━━━━ 14s 293ms/step - loss: 0.4900

 60/107 ━━━━━━━━━━━━━━━━━━━━ 13s 293ms/step - loss: 0.4899

 61/107 ━━━━━━━━━━━━━━━━━━━━ 13s 293ms/step - loss: 0.4898

 62/107 ━━━━━━━━━━━━━━━━━━━━ 13s 293ms/step - loss: 0.4898

 63/107 ━━━━━━━━━━━━━━━━━━━━ 12s 293ms/step - loss: 0.4897

 64/107 ━━━━━━━━━━━━━━━━━━━━ 12s 293ms/step - loss: 0.4897

 65/107 ━━━━━━━━━━━━━━━━━━━━ 12s 293ms/step - loss: 0.4896

 66/107 ━━━━━━━━━━━━━━━━━━━━ 12s 293ms/step - loss: 0.4896

 67/107 ━━━━━━━━━━━━━━━━━━━━ 11s 293ms/step - loss: 0.4895

 68/107 ━━━━━━━━━━━━━━━━━━━━ 11s 293ms/step - loss: 0.4895

 69/107 ━━━━━━━━━━━━━━━━━━━━ 11s 293ms/step - loss: 0.4895

 70/107 ━━━━━━━━━━━━━━━━━━━━ 10s 293ms/step - loss: 0.4894

 71/107 ━━━━━━━━━━━━━━━━━━━━ 10s 293ms/step - loss: 0.4894

 72/107 ━━━━━━━━━━━━━━━━━━━━ 10s 294ms/step - loss: 0.4894

 73/107 ━━━━━━━━━━━━━━━━━━━━ 10s 294ms/step - loss: 0.4893

 74/107 ━━━━━━━━━━━━━━━━━━━━ 9s 294ms/step - loss: 0.4893

 75/107 ━━━━━━━━━━━━━━━━━━━━ 9s 294ms/step - loss: 0.4893

 76/107 ━━━━━━━━━━━━━━━━━━━━ 9s 294ms/step - loss: 0.4893

 77/107 ━━━━━━━━━━━━━━━━━━━━ 8s 294ms/step - loss: 0.4893

 78/107 ━━━━━━━━━━━━━━━━━━━━ 8s 294ms/step - loss: 0.4893

 79/107 ━━━━━━━━━━━━━━━━━━━━ 8s 294ms/step - loss: 0.4893

 80/107 ━━━━━━━━━━━━━━━━━━━━ 7s 294ms/step - loss: 0.4893

 81/107 ━━━━━━━━━━━━━━━━━━━━ 7s 294ms/step - loss: 0.4893

 82/107 ━━━━━━━━━━━━━━━━━━━━ 7s 294ms/step - loss: 0.4893

 83/107 ━━━━━━━━━━━━━━━━━━━━ 7s 294ms/step - loss: 0.4893

 84/107 ━━━━━━━━━━━━━━━━━━━━ 6s 294ms/step - loss: 0.4893

 85/107 ━━━━━━━━━━━━━━━━━━━━ 6s 294ms/step - loss: 0.4893

 86/107 ━━━━━━━━━━━━━━━━━━━━ 6s 294ms/step - loss: 0.4893

 87/107 ━━━━━━━━━━━━━━━━━━━━ 5s 294ms/step - loss: 0.4893

 88/107 ━━━━━━━━━━━━━━━━━━━━ 5s 294ms/step - loss: 0.4894

 89/107 ━━━━━━━━━━━━━━━━━━━━ 5s 294ms/step - loss: 0.4894

 90/107 ━━━━━━━━━━━━━━━━━━━━ 4s 294ms/step - loss: 0.4894

 91/107 ━━━━━━━━━━━━━━━━━━━━ 4s 294ms/step - loss: 0.4894

 92/107 ━━━━━━━━━━━━━━━━━━━━ 4s 294ms/step - loss: 0.4894

 93/107 ━━━━━━━━━━━━━━━━━━━━ 4s 294ms/step - loss: 0.4894

 94/107 ━━━━━━━━━━━━━━━━━━━━ 3s 294ms/step - loss: 0.4894

 95/107 ━━━━━━━━━━━━━━━━━━━━ 3s 294ms/step - loss: 0.4894

 96/107 ━━━━━━━━━━━━━━━━━━━━ 3s 294ms/step - loss: 0.4894

 97/107 ━━━━━━━━━━━━━━━━━━━━ 2s 294ms/step - loss: 0.4894

 98/107 ━━━━━━━━━━━━━━━━━━━━ 2s 294ms/step - loss: 0.4894

 99/107 ━━━━━━━━━━━━━━━━━━━━ 2s 295ms/step - loss: 0.4894

100/107 ━━━━━━━━━━━━━━━━━━━━ 2s 295ms/step - loss: 0.4894

101/107 ━━━━━━━━━━━━━━━━━━━━ 1s 295ms/step - loss: 0.4895

102/107 ━━━━━━━━━━━━━━━━━━━━ 1s 295ms/step - loss: 0.4895

103/107 ━━━━━━━━━━━━━━━━━━━━ 1s 295ms/step - loss: 0.4895

104/107 ━━━━━━━━━━━━━━━━━━━━ 0s 295ms/step - loss: 0.4895

105/107 ━━━━━━━━━━━━━━━━━━━━ 0s 295ms/step - loss: 0.4895

106/107 ━━━━━━━━━━━━━━━━━━━━ 0s 295ms/step - loss: 0.4896

107/107 ━━━━━━━━━━━━━━━━━━━━ 0s 295ms/step - loss: 0.4896

107/107 ━━━━━━━━━━━━━━━━━━━━ 33s 307ms/step - loss: 0.4929 - val_loss: 1.0338

Epoch 5/10

  1/107 ━━━━━━━━━━━━━━━━━━━━ 33s 313ms/step - loss: 0.4154

  2/107 ━━━━━━━━━━━━━━━━━━━━ 30s 293ms/step - loss: 0.4089

  3/107 ━━━━━━━━━━━━━━━━━━━━ 30s 293ms/step - loss: 0.4138

  4/107 ━━━━━━━━━━━━━━━━━━━━ 30s 299ms/step - loss: 0.4179

  5/107 ━━━━━━━━━━━━━━━━━━━━ 30s 301ms/step - loss: 0.4197

  6/107 ━━━━━━━━━━━━━━━━━━━━ 30s 302ms/step - loss: 0.4211

  7/107 ━━━━━━━━━━━━━━━━━━━━ 30s 302ms/step - loss: 0.4217

  8/107 ━━━━━━━━━━━━━━━━━━━━ 30s 304ms/step - loss: 0.4216

  9/107 ━━━━━━━━━━━━━━━━━━━━ 29s 304ms/step - loss: 0.4208

 10/107 ━━━━━━━━━━━━━━━━━━━━ 29s 305ms/step - loss: 0.4199

 11/107 ━━━━━━━━━━━━━━━━━━━━ 29s 305ms/step - loss: 0.4187

 12/107 ━━━━━━━━━━━━━━━━━━━━ 28s 304ms/step - loss: 0.4179

 13/107 ━━━━━━━━━━━━━━━━━━━━ 28s 303ms/step - loss: 0.4171

 14/107 ━━━━━━━━━━━━━━━━━━━━ 28s 303ms/step - loss: 0.4165

 15/107 ━━━━━━━━━━━━━━━━━━━━ 27s 302ms/step - loss: 0.4158

 16/107 ━━━━━━━━━━━━━━━━━━━━ 27s 302ms/step - loss: 0.4153

 17/107 ━━━━━━━━━━━━━━━━━━━━ 27s 303ms/step - loss: 0.4151

 18/107 ━━━━━━━━━━━━━━━━━━━━ 26s 303ms/step - loss: 0.4149

 19/107 ━━━━━━━━━━━━━━━━━━━━ 26s 303ms/step - loss: 0.4149

 20/107 ━━━━━━━━━━━━━━━━━━━━ 26s 303ms/step - loss: 0.4149

 21/107 ━━━━━━━━━━━━━━━━━━━━ 26s 303ms/step - loss: 0.4149

 22/107 ━━━━━━━━━━━━━━━━━━━━ 25s 303ms/step - loss: 0.4147

 23/107 ━━━━━━━━━━━━━━━━━━━━ 25s 302ms/step - loss: 0.4145

 24/107 ━━━━━━━━━━━━━━━━━━━━ 25s 302ms/step - loss: 0.4143

 25/107 ━━━━━━━━━━━━━━━━━━━━ 24s 302ms/step - loss: 0.4142

 26/107 ━━━━━━━━━━━━━━━━━━━━ 24s 301ms/step - loss: 0.4140

 27/107 ━━━━━━━━━━━━━━━━━━━━ 24s 303ms/step - loss: 0.4138

 28/107 ━━━━━━━━━━━━━━━━━━━━ 23s 303ms/step - loss: 0.4136

 29/107 ━━━━━━━━━━━━━━━━━━━━ 23s 302ms/step - loss: 0.4135

 30/107 ━━━━━━━━━━━━━━━━━━━━ 23s 302ms/step - loss: 0.4134

 31/107 ━━━━━━━━━━━━━━━━━━━━ 22s 302ms/step - loss: 0.4133

 32/107 ━━━━━━━━━━━━━━━━━━━━ 22s 302ms/step - loss: 0.4131

 33/107 ━━━━━━━━━━━━━━━━━━━━ 22s 302ms/step - loss: 0.4129

 34/107 ━━━━━━━━━━━━━━━━━━━━ 22s 302ms/step - loss: 0.4128

 35/107 ━━━━━━━━━━━━━━━━━━━━ 21s 302ms/step - loss: 0.4126

 36/107 ━━━━━━━━━━━━━━━━━━━━ 21s 303ms/step - loss: 0.4124

 37/107 ━━━━━━━━━━━━━━━━━━━━ 21s 302ms/step - loss: 0.4122

 38/107 ━━━━━━━━━━━━━━━━━━━━ 20s 302ms/step - loss: 0.4120

 39/107 ━━━━━━━━━━━━━━━━━━━━ 20s 302ms/step - loss: 0.4118

 40/107 ━━━━━━━━━━━━━━━━━━━━ 20s 302ms/step - loss: 0.4116

 41/107 ━━━━━━━━━━━━━━━━━━━━ 19s 302ms/step - loss: 0.4114

 42/107 ━━━━━━━━━━━━━━━━━━━━ 19s 301ms/step - loss: 0.4111

 43/107 ━━━━━━━━━━━━━━━━━━━━ 19s 301ms/step - loss: 0.4109

 44/107 ━━━━━━━━━━━━━━━━━━━━ 18s 301ms/step - loss: 0.4106

 45/107 ━━━━━━━━━━━━━━━━━━━━ 18s 301ms/step - loss: 0.4104

 46/107 ━━━━━━━━━━━━━━━━━━━━ 18s 301ms/step - loss: 0.4103

 47/107 ━━━━━━━━━━━━━━━━━━━━ 18s 301ms/step - loss: 0.4102

 48/107 ━━━━━━━━━━━━━━━━━━━━ 17s 300ms/step - loss: 0.4100

 49/107 ━━━━━━━━━━━━━━━━━━━━ 17s 300ms/step - loss: 0.4099

 50/107 ━━━━━━━━━━━━━━━━━━━━ 17s 300ms/step - loss: 0.4098

 51/107 ━━━━━━━━━━━━━━━━━━━━ 16s 300ms/step - loss: 0.4097

 52/107 ━━━━━━━━━━━━━━━━━━━━ 16s 300ms/step - loss: 0.4096

 53/107 ━━━━━━━━━━━━━━━━━━━━ 16s 300ms/step - loss: 0.4095

 54/107 ━━━━━━━━━━━━━━━━━━━━ 15s 300ms/step - loss: 0.4094

 55/107 ━━━━━━━━━━━━━━━━━━━━ 15s 300ms/step - loss: 0.4093

 56/107 ━━━━━━━━━━━━━━━━━━━━ 15s 300ms/step - loss: 0.4092

 57/107 ━━━━━━━━━━━━━━━━━━━━ 15s 300ms/step - loss: 0.4091

 58/107 ━━━━━━━━━━━━━━━━━━━━ 14s 300ms/step - loss: 0.4090

 59/107 ━━━━━━━━━━━━━━━━━━━━ 14s 300ms/step - loss: 0.4089

 60/107 ━━━━━━━━━━━━━━━━━━━━ 14s 301ms/step - loss: 0.4088

 61/107 ━━━━━━━━━━━━━━━━━━━━ 13s 301ms/step - loss: 0.4088

 62/107 ━━━━━━━━━━━━━━━━━━━━ 13s 301ms/step - loss: 0.4087

 63/107 ━━━━━━━━━━━━━━━━━━━━ 13s 301ms/step - loss: 0.4087

 64/107 ━━━━━━━━━━━━━━━━━━━━ 12s 301ms/step - loss: 0.4086

 65/107 ━━━━━━━━━━━━━━━━━━━━ 12s 301ms/step - loss: 0.4086

 66/107 ━━━━━━━━━━━━━━━━━━━━ 12s 301ms/step - loss: 0.4086

 67/107 ━━━━━━━━━━━━━━━━━━━━ 12s 301ms/step - loss: 0.4086

 68/107 ━━━━━━━━━━━━━━━━━━━━ 11s 301ms/step - loss: 0.4085

 69/107 ━━━━━━━━━━━━━━━━━━━━ 11s 301ms/step - loss: 0.4085

 70/107 ━━━━━━━━━━━━━━━━━━━━ 11s 301ms/step - loss: 0.4085

 71/107 ━━━━━━━━━━━━━━━━━━━━ 10s 301ms/step - loss: 0.4085

 72/107 ━━━━━━━━━━━━━━━━━━━━ 10s 301ms/step - loss: 0.4085

 73/107 ━━━━━━━━━━━━━━━━━━━━ 10s 301ms/step - loss: 0.4085

 74/107 ━━━━━━━━━━━━━━━━━━━━ 9s 301ms/step - loss: 0.4086

 75/107 ━━━━━━━━━━━━━━━━━━━━ 9s 301ms/step - loss: 0.4086

 76/107 ━━━━━━━━━━━━━━━━━━━━ 9s 301ms/step - loss: 0.4087

 77/107 ━━━━━━━━━━━━━━━━━━━━ 9s 301ms/step - loss: 0.4087

 78/107 ━━━━━━━━━━━━━━━━━━━━ 8s 301ms/step - loss: 0.4088

 79/107 ━━━━━━━━━━━━━━━━━━━━ 8s 301ms/step - loss: 0.4088

 80/107 ━━━━━━━━━━━━━━━━━━━━ 8s 301ms/step - loss: 0.4088

 81/107 ━━━━━━━━━━━━━━━━━━━━ 7s 301ms/step - loss: 0.4089

 82/107 ━━━━━━━━━━━━━━━━━━━━ 7s 301ms/step - loss: 0.4089

 83/107 ━━━━━━━━━━━━━━━━━━━━ 7s 302ms/step - loss: 0.4090

 84/107 ━━━━━━━━━━━━━━━━━━━━ 6s 302ms/step - loss: 0.4090

 85/107 ━━━━━━━━━━━━━━━━━━━━ 6s 302ms/step - loss: 0.4091

 86/107 ━━━━━━━━━━━━━━━━━━━━ 6s 302ms/step - loss: 0.4091

 87/107 ━━━━━━━━━━━━━━━━━━━━ 6s 303ms/step - loss: 0.4092

 88/107 ━━━━━━━━━━━━━━━━━━━━ 5s 303ms/step - loss: 0.4092

 89/107 ━━━━━━━━━━━━━━━━━━━━ 5s 303ms/step - loss: 0.4093

 90/107 ━━━━━━━━━━━━━━━━━━━━ 5s 303ms/step - loss: 0.4093

 91/107 ━━━━━━━━━━━━━━━━━━━━ 4s 303ms/step - loss: 0.4094

 92/107 ━━━━━━━━━━━━━━━━━━━━ 4s 303ms/step - loss: 0.4094

 93/107 ━━━━━━━━━━━━━━━━━━━━ 4s 304ms/step - loss: 0.4094

 94/107 ━━━━━━━━━━━━━━━━━━━━ 3s 303ms/step - loss: 0.4095

 95/107 ━━━━━━━━━━━━━━━━━━━━ 3s 303ms/step - loss: 0.4095

 96/107 ━━━━━━━━━━━━━━━━━━━━ 3s 303ms/step - loss: 0.4096

 97/107 ━━━━━━━━━━━━━━━━━━━━ 3s 303ms/step - loss: 0.4096

 98/107 ━━━━━━━━━━━━━━━━━━━━ 2s 303ms/step - loss: 0.4097

 99/107 ━━━━━━━━━━━━━━━━━━━━ 2s 303ms/step - loss: 0.4097

100/107 ━━━━━━━━━━━━━━━━━━━━ 2s 303ms/step - loss: 0.4097

101/107 ━━━━━━━━━━━━━━━━━━━━ 1s 303ms/step - loss: 0.4098

102/107 ━━━━━━━━━━━━━━━━━━━━ 1s 303ms/step - loss: 0.4098

103/107 ━━━━━━━━━━━━━━━━━━━━ 1s 303ms/step - loss: 0.4099

104/107 ━━━━━━━━━━━━━━━━━━━━ 0s 303ms/step - loss: 0.4099

105/107 ━━━━━━━━━━━━━━━━━━━━ 0s 302ms/step - loss: 0.4099

106/107 ━━━━━━━━━━━━━━━━━━━━ 0s 302ms/step - loss: 0.4100

107/107 ━━━━━━━━━━━━━━━━━━━━ 0s 302ms/step - loss: 0.4100

107/107 ━━━━━━━━━━━━━━━━━━━━ 33s 312ms/step - loss: 0.4145 - val_loss: 1.2480

  saved /kaggle/working/models/lstm_no_emoji.keras
  threshold 0.55 | dev Micro-F1 53.63%

--- BiLSTM | With Emoji ---
  Phase 1: hyper-parameter search
    cfg1: lr=0.001 embed=128 batch=64

      -> Micro-F1 51.42%
    cfg2: lr=0.0005 embed=256 batch=32

      -> Micro-F1 53.97%
    cfg3: lr=0.002 embed=128 batch=64

      -> Micro-F1 54.17%

  config  micro_f1  macro_f1  label_accuracy  threshold model       track
0   cfg1     51.42     45.61           73.06       0.55  LSTM  With Emoji
1   cfg2     53.97     48.03           74.75       0.55  LSTM  With Emoji
2   cfg3     54.17     48.60           74.54       0.55  LSTM  With Emoji

  best config: cfg3
  Phase 2: final training

Epoch 1/10

  1/107 ━━━━━━━━━━━━━━━━━━━━ 18:03 10s/step - loss: 1.1099

  2/107 ━━━━━━━━━━━━━━━━━━━━ 33s 321ms/step - loss: 1.1151

  3/107 ━━━━━━━━━━━━━━━━━━━━ 33s 318ms/step - loss: 1.1122

  4/107 ━━━━━━━━━━━━━━━━━━━━ 32s 317ms/step - loss: 1.1102

  5/107 ━━━━━━━━━━━━━━━━━━━━ 31s 311ms/step - loss: 1.1094

  6/107 ━━━━━━━━━━━━━━━━━━━━ 31s 307ms/step - loss: 1.1085

  7/107 ━━━━━━━━━━━━━━━━━━━━ 30s 306ms/step - loss: 1.1084

  8/107 ━━━━━━━━━━━━━━━━━━━━ 30s 303ms/step - loss: 1.1089

  9/107 ━━━━━━━━━━━━━━━━━━━━ 29s 302ms/step - loss: 1.1096

 10/107 ━━━━━━━━━━━━━━━━━━━━ 29s 302ms/step - loss: 1.1105

 11/107 ━━━━━━━━━━━━━━━━━━━━ 28s 302ms/step - loss: 1.1111

 12/107 ━━━━━━━━━━━━━━━━━━━━ 28s 301ms/step - loss: 1.1114

 13/107 ━━━━━━━━━━━━━━━━━━━━ 28s 301ms/step - loss: 1.1111

 14/107 ━━━━━━━━━━━━━━━━━━━━ 27s 300ms/step - loss: 1.1107

 15/107 ━━━━━━━━━━━━━━━━━━━━ 27s 300ms/step - loss: 1.1104

 16/107 ━━━━━━━━━━━━━━━━━━━━ 27s 299ms/step - loss: 1.1103

 17/107 ━━━━━━━━━━━━━━━━━━━━ 26s 300ms/step - loss: 1.1098

 18/107 ━━━━━━━━━━━━━━━━━━━━ 26s 300ms/step - loss: 1.1093

 19/107 ━━━━━━━━━━━━━━━━━━━━ 26s 301ms/step - loss: 1.1087

 20/107 ━━━━━━━━━━━━━━━━━━━━ 26s 302ms/step - loss: 1.1080

 21/107 ━━━━━━━━━━━━━━━━━━━━ 25s 302ms/step - loss: 1.1074

 22/107 ━━━━━━━━━━━━━━━━━━━━ 25s 302ms/step - loss: 1.1067

 23/107 ━━━━━━━━━━━━━━━━━━━━ 25s 303ms/step - loss: 1.1061

 24/107 ━━━━━━━━━━━━━━━━━━━━ 25s 303ms/step - loss: 1.1054

 25/107 ━━━━━━━━━━━━━━━━━━━━ 24s 303ms/step - loss: 1.1049

 26/107 ━━━━━━━━━━━━━━━━━━━━ 24s 305ms/step - loss: 1.1044

 27/107 ━━━━━━━━━━━━━━━━━━━━ 24s 305ms/step - loss: 1.1041

 28/107 ━━━━━━━━━━━━━━━━━━━━ 24s 305ms/step - loss: 1.1038

 29/107 ━━━━━━━━━━━━━━━━━━━━ 23s 305ms/step - loss: 1.1033

 30/107 ━━━━━━━━━━━━━━━━━━━━ 23s 305ms/step - loss: 1.1028

 31/107 ━━━━━━━━━━━━━━━━━━━━ 23s 304ms/step - loss: 1.1024

 32/107 ━━━━━━━━━━━━━━━━━━━━ 22s 305ms/step - loss: 1.1020

 33/107 ━━━━━━━━━━━━━━━━━━━━ 22s 305ms/step - loss: 1.1016

 34/107 ━━━━━━━━━━━━━━━━━━━━ 22s 305ms/step - loss: 1.1011

 35/107 ━━━━━━━━━━━━━━━━━━━━ 21s 305ms/step - loss: 1.1007

 36/107 ━━━━━━━━━━━━━━━━━━━━ 21s 304ms/step - loss: 1.1002

 37/107 ━━━━━━━━━━━━━━━━━━━━ 21s 305ms/step - loss: 1.0997

 38/107 ━━━━━━━━━━━━━━━━━━━━ 21s 305ms/step - loss: 1.0992

 39/107 ━━━━━━━━━━━━━━━━━━━━ 20s 304ms/step - loss: 1.0985

 40/107 ━━━━━━━━━━━━━━━━━━━━ 20s 304ms/step - loss: 1.0979

 41/107 ━━━━━━━━━━━━━━━━━━━━ 20s 304ms/step - loss: 1.0971

 42/107 ━━━━━━━━━━━━━━━━━━━━ 19s 304ms/step - loss: 1.0964

 43/107 ━━━━━━━━━━━━━━━━━━━━ 19s 305ms/step - loss: 1.0957

 44/107 ━━━━━━━━━━━━━━━━━━━━ 19s 304ms/step - loss: 1.0950

 45/107 ━━━━━━━━━━━━━━━━━━━━ 18s 304ms/step - loss: 1.0943

 46/107 ━━━━━━━━━━━━━━━━━━━━ 18s 304ms/step - loss: 1.0935

 47/107 ━━━━━━━━━━━━━━━━━━━━ 18s 304ms/step - loss: 1.0928

 48/107 ━━━━━━━━━━━━━━━━━━━━ 17s 304ms/step - loss: 1.0921

 49/107 ━━━━━━━━━━━━━━━━━━━━ 17s 304ms/step - loss: 1.0914

 50/107 ━━━━━━━━━━━━━━━━━━━━ 17s 304ms/step - loss: 1.0907

 51/107 ━━━━━━━━━━━━━━━━━━━━ 17s 305ms/step - loss: 1.0901

 52/107 ━━━━━━━━━━━━━━━━━━━━ 16s 305ms/step - loss: 1.0894

 53/107 ━━━━━━━━━━━━━━━━━━━━ 16s 304ms/step - loss: 1.0888

 54/107 ━━━━━━━━━━━━━━━━━━━━ 16s 304ms/step - loss: 1.0882

 55/107 ━━━━━━━━━━━━━━━━━━━━ 15s 304ms/step - loss: 1.0876

 56/107 ━━━━━━━━━━━━━━━━━━━━ 15s 304ms/step - loss: 1.0870

 57/107 ━━━━━━━━━━━━━━━━━━━━ 15s 304ms/step - loss: 1.0864

 58/107 ━━━━━━━━━━━━━━━━━━━━ 14s 304ms/step - loss: 1.0859

 59/107 ━━━━━━━━━━━━━━━━━━━━ 14s 305ms/step - loss: 1.0853

 60/107 ━━━━━━━━━━━━━━━━━━━━ 14s 304ms/step - loss: 1.0847

 61/107 ━━━━━━━━━━━━━━━━━━━━ 14s 304ms/step - loss: 1.0841

 62/107 ━━━━━━━━━━━━━━━━━━━━ 13s 305ms/step - loss: 1.0836

 63/107 ━━━━━━━━━━━━━━━━━━━━ 13s 305ms/step - loss: 1.0830

 64/107 ━━━━━━━━━━━━━━━━━━━━ 13s 306ms/step - loss: 1.0824

 65/107 ━━━━━━━━━━━━━━━━━━━━ 12s 306ms/step - loss: 1.0818

 66/107 ━━━━━━━━━━━━━━━━━━━━ 12s 306ms/step - loss: 1.0812

 67/107 ━━━━━━━━━━━━━━━━━━━━ 12s 306ms/step - loss: 1.0806

 68/107 ━━━━━━━━━━━━━━━━━━━━ 11s 306ms/step - loss: 1.0800

 69/107 ━━━━━━━━━━━━━━━━━━━━ 11s 306ms/step - loss: 1.0794

 70/107 ━━━━━━━━━━━━━━━━━━━━ 11s 307ms/step - loss: 1.0788

 71/107 ━━━━━━━━━━━━━━━━━━━━ 11s 307ms/step - loss: 1.0783

 72/107 ━━━━━━━━━━━━━━━━━━━━ 10s 308ms/step - loss: 1.0777

 73/107 ━━━━━━━━━━━━━━━━━━━━ 10s 309ms/step - loss: 1.0771

 74/107 ━━━━━━━━━━━━━━━━━━━━ 10s 309ms/step - loss: 1.0765

 75/107 ━━━━━━━━━━━━━━━━━━━━ 9s 310ms/step - loss: 1.0760

 76/107 ━━━━━━━━━━━━━━━━━━━━ 9s 310ms/step - loss: 1.0754

 77/107 ━━━━━━━━━━━━━━━━━━━━ 9s 311ms/step - loss: 1.0749

 78/107 ━━━━━━━━━━━━━━━━━━━━ 9s 311ms/step - loss: 1.0744

 79/107 ━━━━━━━━━━━━━━━━━━━━ 8s 311ms/step - loss: 1.0738

 80/107 ━━━━━━━━━━━━━━━━━━━━ 8s 311ms/step - loss: 1.0733

 81/107 ━━━━━━━━━━━━━━━━━━━━ 8s 311ms/step - loss: 1.0728

 82/107 ━━━━━━━━━━━━━━━━━━━━ 7s 312ms/step - loss: 1.0723

 83/107 ━━━━━━━━━━━━━━━━━━━━ 7s 312ms/step - loss: 1.0717

 84/107 ━━━━━━━━━━━━━━━━━━━━ 7s 312ms/step - loss: 1.0712

 85/107 ━━━━━━━━━━━━━━━━━━━━ 6s 312ms/step - loss: 1.0707

 86/107 ━━━━━━━━━━━━━━━━━━━━ 6s 312ms/step - loss: 1.0702

 87/107 ━━━━━━━━━━━━━━━━━━━━ 6s 312ms/step - loss: 1.0697

 88/107 ━━━━━━━━━━━━━━━━━━━━ 5s 312ms/step - loss: 1.0692

 89/107 ━━━━━━━━━━━━━━━━━━━━ 5s 313ms/step - loss: 1.0686

 90/107 ━━━━━━━━━━━━━━━━━━━━ 5s 313ms/step - loss: 1.0681

 91/107 ━━━━━━━━━━━━━━━━━━━━ 5s 313ms/step - loss: 1.0676

 92/107 ━━━━━━━━━━━━━━━━━━━━ 4s 312ms/step - loss: 1.0671

 93/107 ━━━━━━━━━━━━━━━━━━━━ 4s 312ms/step - loss: 1.0666

 94/107 ━━━━━━━━━━━━━━━━━━━━ 4s 312ms/step - loss: 1.0660

 95/107 ━━━━━━━━━━━━━━━━━━━━ 3s 312ms/step - loss: 1.0655

 96/107 ━━━━━━━━━━━━━━━━━━━━ 3s 312ms/step - loss: 1.0650

 97/107 ━━━━━━━━━━━━━━━━━━━━ 3s 312ms/step - loss: 1.0644

 98/107 ━━━━━━━━━━━━━━━━━━━━ 2s 311ms/step - loss: 1.0639

 99/107 ━━━━━━━━━━━━━━━━━━━━ 2s 311ms/step - loss: 1.0633

100/107 ━━━━━━━━━━━━━━━━━━━━ 2s 311ms/step - loss: 1.0628

101/107 ━━━━━━━━━━━━━━━━━━━━ 1s 311ms/step - loss: 1.0623

102/107 ━━━━━━━━━━━━━━━━━━━━ 1s 311ms/step - loss: 1.0617

103/107 ━━━━━━━━━━━━━━━━━━━━ 1s 311ms/step - loss: 1.0612

104/107 ━━━━━━━━━━━━━━━━━━━━ 0s 311ms/step - loss: 1.0607

105/107 ━━━━━━━━━━━━━━━━━━━━ 0s 311ms/step - loss: 1.0601

106/107 ━━━━━━━━━━━━━━━━━━━━ 0s 311ms/step - loss: 1.0596

107/107 ━━━━━━━━━━━━━━━━━━━━ 0s 311ms/step - loss: 1.0591

107/107 ━━━━━━━━━━━━━━━━━━━━ 45s 331ms/step - loss: 1.0047 - val_loss: 0.9039

Epoch 2/10

  1/107 ━━━━━━━━━━━━━━━━━━━━ 35s 337ms/step - loss: 0.7911

  2/107 ━━━━━━━━━━━━━━━━━━━━ 31s 303ms/step - loss: 0.8095

  3/107 ━━━━━━━━━━━━━━━━━━━━ 31s 304ms/step - loss: 0.8151

  4/107 ━━━━━━━━━━━━━━━━━━━━ 31s 303ms/step - loss: 0.8191

  5/107 ━━━━━━━━━━━━━━━━━━━━ 31s 305ms/step - loss: 0.8215

  6/107 ━━━━━━━━━━━━━━━━━━━━ 30s 305ms/step - loss: 0.8222

  7/107 ━━━━━━━━━━━━━━━━━━━━ 30s 305ms/step - loss: 0.8222

  8/107 ━━━━━━━━━━━━━━━━━━━━ 31s 313ms/step - loss: 0.8217

  9/107 ━━━━━━━━━━━━━━━━━━━━ 30s 312ms/step - loss: 0.8209

 10/107 ━━━━━━━━━━━━━━━━━━━━ 30s 313ms/step - loss: 0.8204

 11/107 ━━━━━━━━━━━━━━━━━━━━ 29s 312ms/step - loss: 0.8200

 12/107 ━━━━━━━━━━━━━━━━━━━━ 29s 311ms/step - loss: 0.8194

 13/107 ━━━━━━━━━━━━━━━━━━━━ 29s 310ms/step - loss: 0.8187

 14/107 ━━━━━━━━━━━━━━━━━━━━ 28s 310ms/step - loss: 0.8180

 15/107 ━━━━━━━━━━━━━━━━━━━━ 28s 310ms/step - loss: 0.8170

 16/107 ━━━━━━━━━━━━━━━━━━━━ 28s 309ms/step - loss: 0.8163

 17/107 ━━━━━━━━━━━━━━━━━━━━ 27s 308ms/step - loss: 0.8156

 18/107 ━━━━━━━━━━━━━━━━━━━━ 27s 308ms/step - loss: 0.8148

 19/107 ━━━━━━━━━━━━━━━━━━━━ 27s 308ms/step - loss: 0.8140

 20/107 ━━━━━━━━━━━━━━━━━━━━ 26s 308ms/step - loss: 0.8130

 21/107 ━━━━━━━━━━━━━━━━━━━━ 26s 309ms/step - loss: 0.8122

 22/107 ━━━━━━━━━━━━━━━━━━━━ 26s 309ms/step - loss: 0.8116

 23/107 ━━━━━━━━━━━━━━━━━━━━ 26s 310ms/step - loss: 0.8112

 24/107 ━━━━━━━━━━━━━━━━━━━━ 25s 312ms/step - loss: 0.8107

 25/107 ━━━━━━━━━━━━━━━━━━━━ 25s 313ms/step - loss: 0.8103

 26/107 ━━━━━━━━━━━━━━━━━━━━ 25s 313ms/step - loss: 0.8099

 27/107 ━━━━━━━━━━━━━━━━━━━━ 25s 313ms/step - loss: 0.8095

 28/107 ━━━━━━━━━━━━━━━━━━━━ 24s 313ms/step - loss: 0.8091

 29/107 ━━━━━━━━━━━━━━━━━━━━ 24s 312ms/step - loss: 0.8085

 30/107 ━━━━━━━━━━━━━━━━━━━━ 24s 312ms/step - loss: 0.8079

 31/107 ━━━━━━━━━━━━━━━━━━━━ 23s 312ms/step - loss: 0.8073

 32/107 ━━━━━━━━━━━━━━━━━━━━ 23s 311ms/step - loss: 0.8066

 33/107 ━━━━━━━━━━━━━━━━━━━━ 22s 311ms/step - loss: 0.8060

 34/107 ━━━━━━━━━━━━━━━━━━━━ 22s 310ms/step - loss: 0.8054

 35/107 ━━━━━━━━━━━━━━━━━━━━ 22s 310ms/step - loss: 0.8047

 36/107 ━━━━━━━━━━━━━━━━━━━━ 21s 310ms/step - loss: 0.8041

 37/107 ━━━━━━━━━━━━━━━━━━━━ 21s 309ms/step - loss: 0.8036

 38/107 ━━━━━━━━━━━━━━━━━━━━ 21s 309ms/step - loss: 0.8030

 39/107 ━━━━━━━━━━━━━━━━━━━━ 21s 309ms/step - loss: 0.8025

 40/107 ━━━━━━━━━━━━━━━━━━━━ 20s 310ms/step - loss: 0.8020

 41/107 ━━━━━━━━━━━━━━━━━━━━ 20s 310ms/step - loss: 0.8016

 42/107 ━━━━━━━━━━━━━━━━━━━━ 20s 309ms/step - loss: 0.8011

 43/107 ━━━━━━━━━━━━━━━━━━━━ 19s 309ms/step - loss: 0.8006

 44/107 ━━━━━━━━━━━━━━━━━━━━ 19s 309ms/step - loss: 0.8001

 45/107 ━━━━━━━━━━━━━━━━━━━━ 19s 310ms/step - loss: 0.7996

 46/107 ━━━━━━━━━━━━━━━━━━━━ 18s 309ms/step - loss: 0.7991

 47/107 ━━━━━━━━━━━━━━━━━━━━ 18s 309ms/step - loss: 0.7987

 48/107 ━━━━━━━━━━━━━━━━━━━━ 18s 309ms/step - loss: 0.7982

 49/107 ━━━━━━━━━━━━━━━━━━━━ 17s 308ms/step - loss: 0.7978

 50/107 ━━━━━━━━━━━━━━━━━━━━ 17s 308ms/step - loss: 0.7974

 51/107 ━━━━━━━━━━━━━━━━━━━━ 17s 308ms/step - loss: 0.7970

 52/107 ━━━━━━━━━━━━━━━━━━━━ 16s 307ms/step - loss: 0.7965

 53/107 ━━━━━━━━━━━━━━━━━━━━ 16s 307ms/step - loss: 0.7961

 54/107 ━━━━━━━━━━━━━━━━━━━━ 16s 307ms/step - loss: 0.7957

 55/107 ━━━━━━━━━━━━━━━━━━━━ 15s 307ms/step - loss: 0.7953

 56/107 ━━━━━━━━━━━━━━━━━━━━ 15s 307ms/step - loss: 0.7949

 57/107 ━━━━━━━━━━━━━━━━━━━━ 15s 307ms/step - loss: 0.7945

 58/107 ━━━━━━━━━━━━━━━━━━━━ 15s 306ms/step - loss: 0.7941

 59/107 ━━━━━━━━━━━━━━━━━━━━ 14s 306ms/step - loss: 0.7938

 60/107 ━━━━━━━━━━━━━━━━━━━━ 14s 306ms/step - loss: 0.7934

 61/107 ━━━━━━━━━━━━━━━━━━━━ 14s 306ms/step - loss: 0.7930

 62/107 ━━━━━━━━━━━━━━━━━━━━ 13s 306ms/step - loss: 0.7927

 63/107 ━━━━━━━━━━━━━━━━━━━━ 13s 306ms/step - loss: 0.7923

 64/107 ━━━━━━━━━━━━━━━━━━━━ 13s 306ms/step - loss: 0.7920

 65/107 ━━━━━━━━━━━━━━━━━━━━ 12s 306ms/step - loss: 0.7916

 66/107 ━━━━━━━━━━━━━━━━━━━━ 12s 306ms/step - loss: 0.7913

 67/107 ━━━━━━━━━━━━━━━━━━━━ 12s 306ms/step - loss: 0.7909

 68/107 ━━━━━━━━━━━━━━━━━━━━ 11s 306ms/step - loss: 0.7906

 69/107 ━━━━━━━━━━━━━━━━━━━━ 11s 306ms/step - loss: 0.7902

 70/107 ━━━━━━━━━━━━━━━━━━━━ 11s 306ms/step - loss: 0.7899

 71/107 ━━━━━━━━━━━━━━━━━━━━ 11s 306ms/step - loss: 0.7895

 72/107 ━━━━━━━━━━━━━━━━━━━━ 10s 306ms/step - loss: 0.7892

 73/107 ━━━━━━━━━━━━━━━━━━━━ 10s 306ms/step - loss: 0.7889

 74/107 ━━━━━━━━━━━━━━━━━━━━ 10s 306ms/step - loss: 0.7885

 75/107 ━━━━━━━━━━━━━━━━━━━━ 9s 306ms/step - loss: 0.7882

 76/107 ━━━━━━━━━━━━━━━━━━━━ 9s 306ms/step - loss: 0.7879

 77/107 ━━━━━━━━━━━━━━━━━━━━ 9s 306ms/step - loss: 0.7876

 78/107 ━━━━━━━━━━━━━━━━━━━━ 8s 306ms/step - loss: 0.7873

 79/107 ━━━━━━━━━━━━━━━━━━━━ 8s 306ms/step - loss: 0.7870

 80/107 ━━━━━━━━━━━━━━━━━━━━ 8s 306ms/step - loss: 0.7867

 81/107 ━━━━━━━━━━━━━━━━━━━━ 7s 305ms/step - loss: 0.7865

 82/107 ━━━━━━━━━━━━━━━━━━━━ 7s 305ms/step - loss: 0.7862

 83/107 ━━━━━━━━━━━━━━━━━━━━ 7s 305ms/step - loss: 0.7859

 84/107 ━━━━━━━━━━━━━━━━━━━━ 7s 305ms/step - loss: 0.7857

 85/107 ━━━━━━━━━━━━━━━━━━━━ 6s 305ms/step - loss: 0.7854

 86/107 ━━━━━━━━━━━━━━━━━━━━ 6s 305ms/step - loss: 0.7852

 87/107 ━━━━━━━━━━━━━━━━━━━━ 6s 305ms/step - loss: 0.7849

 88/107 ━━━━━━━━━━━━━━━━━━━━ 5s 305ms/step - loss: 0.7847

 89/107 ━━━━━━━━━━━━━━━━━━━━ 5s 304ms/step - loss: 0.7845

 90/107 ━━━━━━━━━━━━━━━━━━━━ 5s 304ms/step - loss: 0.7843

 91/107 ━━━━━━━━━━━━━━━━━━━━ 4s 304ms/step - loss: 0.7841

 92/107 ━━━━━━━━━━━━━━━━━━━━ 4s 304ms/step - loss: 0.7839

 93/107 ━━━━━━━━━━━━━━━━━━━━ 4s 304ms/step - loss: 0.7837

 94/107 ━━━━━━━━━━━━━━━━━━━━ 3s 304ms/step - loss: 0.7835

 95/107 ━━━━━━━━━━━━━━━━━━━━ 3s 304ms/step - loss: 0.7833

 96/107 ━━━━━━━━━━━━━━━━━━━━ 3s 304ms/step - loss: 0.7831

 97/107 ━━━━━━━━━━━━━━━━━━━━ 3s 304ms/step - loss: 0.7829

 98/107 ━━━━━━━━━━━━━━━━━━━━ 2s 303ms/step - loss: 0.7827

 99/107 ━━━━━━━━━━━━━━━━━━━━ 2s 303ms/step - loss: 0.7825

100/107 ━━━━━━━━━━━━━━━━━━━━ 2s 303ms/step - loss: 0.7824

101/107 ━━━━━━━━━━━━━━━━━━━━ 1s 303ms/step - loss: 0.7822

102/107 ━━━━━━━━━━━━━━━━━━━━ 1s 303ms/step - loss: 0.7820

103/107 ━━━━━━━━━━━━━━━━━━━━ 1s 303ms/step - loss: 0.7818

104/107 ━━━━━━━━━━━━━━━━━━━━ 0s 303ms/step - loss: 0.7816

105/107 ━━━━━━━━━━━━━━━━━━━━ 0s 303ms/step - loss: 0.7814

106/107 ━━━━━━━━━━━━━━━━━━━━ 0s 303ms/step - loss: 0.7812

107/107 ━━━━━━━━━━━━━━━━━━━━ 0s 303ms/step - loss: 0.7810

107/107 ━━━━━━━━━━━━━━━━━━━━ 34s 314ms/step - loss: 0.7615 - val_loss: 0.8657

Epoch 3/10

  1/107 ━━━━━━━━━━━━━━━━━━━━ 34s 325ms/step - loss: 0.6012

  2/107 ━━━━━━━━━━━━━━━━━━━━ 32s 307ms/step - loss: 0.5928

  3/107 ━━━━━━━━━━━━━━━━━━━━ 32s 312ms/step - loss: 0.5874

  4/107 ━━━━━━━━━━━━━━━━━━━━ 31s 310ms/step - loss: 0.5849

  5/107 ━━━━━━━━━━━━━━━━━━━━ 31s 309ms/step - loss: 0.5870

  6/107 ━━━━━━━━━━━━━━━━━━━━ 31s 308ms/step - loss: 0.5886

  7/107 ━━━━━━━━━━━━━━━━━━━━ 30s 309ms/step - loss: 0.5887

  8/107 ━━━━━━━━━━━━━━━━━━━━ 30s 307ms/step - loss: 0.5888

  9/107 ━━━━━━━━━━━━━━━━━━━━ 30s 307ms/step - loss: 0.5906

 10/107 ━━━━━━━━━━━━━━━━━━━━ 29s 306ms/step - loss: 0.5918

 11/107 ━━━━━━━━━━━━━━━━━━━━ 29s 306ms/step - loss: 0.5929

 12/107 ━━━━━━━━━━━━━━━━━━━━ 29s 306ms/step - loss: 0.5937

 13/107 ━━━━━━━━━━━━━━━━━━━━ 28s 307ms/step - loss: 0.5939

 14/107 ━━━━━━━━━━━━━━━━━━━━ 28s 308ms/step - loss: 0.5942

 15/107 ━━━━━━━━━━━━━━━━━━━━ 28s 307ms/step - loss: 0.5942

 16/107 ━━━━━━━━━━━━━━━━━━━━ 27s 306ms/step - loss: 0.5940

 17/107 ━━━━━━━━━━━━━━━━━━━━ 27s 305ms/step - loss: 0.5937

 18/107 ━━━━━━━━━━━━━━━━━━━━ 27s 304ms/step - loss: 0.5933

 19/107 ━━━━━━━━━━━━━━━━━━━━ 26s 304ms/step - loss: 0.5933

 20/107 ━━━━━━━━━━━━━━━━━━━━ 26s 303ms/step - loss: 0.5932

 21/107 ━━━━━━━━━━━━━━━━━━━━ 26s 303ms/step - loss: 0.5932

 22/107 ━━━━━━━━━━━━━━━━━━━━ 25s 302ms/step - loss: 0.5930

 23/107 ━━━━━━━━━━━━━━━━━━━━ 25s 302ms/step - loss: 0.5930

 24/107 ━━━━━━━━━━━━━━━━━━━━ 25s 302ms/step - loss: 0.5930

 25/107 ━━━━━━━━━━━━━━━━━━━━ 24s 301ms/step - loss: 0.5929

 26/107 ━━━━━━━━━━━━━━━━━━━━ 24s 301ms/step - loss: 0.5927

 27/107 ━━━━━━━━━━━━━━━━━━━━ 24s 300ms/step - loss: 0.5925

 28/107 ━━━━━━━━━━━━━━━━━━━━ 23s 300ms/step - loss: 0.5923

 29/107 ━━━━━━━━━━━━━━━━━━━━ 23s 301ms/step - loss: 0.5921

 30/107 ━━━━━━━━━━━━━━━━━━━━ 23s 302ms/step - loss: 0.5919

 31/107 ━━━━━━━━━━━━━━━━━━━━ 22s 301ms/step - loss: 0.5916

 32/107 ━━━━━━━━━━━━━━━━━━━━ 22s 301ms/step - loss: 0.5913

 33/107 ━━━━━━━━━━━━━━━━━━━━ 22s 301ms/step - loss: 0.5910

 34/107 ━━━━━━━━━━━━━━━━━━━━ 21s 301ms/step - loss: 0.5906

 35/107 ━━━━━━━━━━━━━━━━━━━━ 21s 301ms/step - loss: 0.5903

 36/107 ━━━━━━━━━━━━━━━━━━━━ 21s 301ms/step - loss: 0.5901

 37/107 ━━━━━━━━━━━━━━━━━━━━ 21s 301ms/step - loss: 0.5899

 38/107 ━━━━━━━━━━━━━━━━━━━━ 20s 301ms/step - loss: 0.5897

 39/107 ━━━━━━━━━━━━━━━━━━━━ 20s 300ms/step - loss: 0.5894

 40/107 ━━━━━━━━━━━━━━━━━━━━ 20s 301ms/step - loss: 0.5893

 41/107 ━━━━━━━━━━━━━━━━━━━━ 19s 300ms/step - loss: 0.5891

 42/107 ━━━━━━━━━━━━━━━━━━━━ 19s 300ms/step - loss: 0.5889

 43/107 ━━━━━━━━━━━━━━━━━━━━ 19s 300ms/step - loss: 0.5887

 44/107 ━━━━━━━━━━━━━━━━━━━━ 18s 300ms/step - loss: 0.5885

 45/107 ━━━━━━━━━━━━━━━━━━━━ 18s 300ms/step - loss: 0.5883

 46/107 ━━━━━━━━━━━━━━━━━━━━ 18s 300ms/step - loss: 0.5881

 47/107 ━━━━━━━━━━━━━━━━━━━━ 17s 300ms/step - loss: 0.5879

 48/107 ━━━━━━━━━━━━━━━━━━━━ 17s 300ms/step - loss: 0.5878

 49/107 ━━━━━━━━━━━━━━━━━━━━ 17s 299ms/step - loss: 0.5875

 50/107 ━━━━━━━━━━━━━━━━━━━━ 17s 299ms/step - loss: 0.5873

 51/107 ━━━━━━━━━━━━━━━━━━━━ 16s 299ms/step - loss: 0.5870

 52/107 ━━━━━━━━━━━━━━━━━━━━ 16s 299ms/step - loss: 0.5867

 53/107 ━━━━━━━━━━━━━━━━━━━━ 16s 299ms/step - loss: 0.5864

 54/107 ━━━━━━━━━━━━━━━━━━━━ 15s 299ms/step - loss: 0.5861

 55/107 ━━━━━━━━━━━━━━━━━━━━ 15s 299ms/step - loss: 0.5858

 56/107 ━━━━━━━━━━━━━━━━━━━━ 15s 299ms/step - loss: 0.5855

 57/107 ━━━━━━━━━━━━━━━━━━━━ 14s 299ms/step - loss: 0.5852

 58/107 ━━━━━━━━━━━━━━━━━━━━ 14s 299ms/step - loss: 0.5849

 59/107 ━━━━━━━━━━━━━━━━━━━━ 14s 299ms/step - loss: 0.5846

 60/107 ━━━━━━━━━━━━━━━━━━━━ 14s 299ms/step - loss: 0.5844

 61/107 ━━━━━━━━━━━━━━━━━━━━ 13s 299ms/step - loss: 0.5842

 62/107 ━━━━━━━━━━━━━━━━━━━━ 13s 299ms/step - loss: 0.5840

 63/107 ━━━━━━━━━━━━━━━━━━━━ 13s 300ms/step - loss: 0.5838

 64/107 ━━━━━━━━━━━━━━━━━━━━ 12s 300ms/step - loss: 0.5836

 65/107 ━━━━━━━━━━━━━━━━━━━━ 12s 300ms/step - loss: 0.5835

 66/107 ━━━━━━━━━━━━━━━━━━━━ 12s 300ms/step - loss: 0.5833

 67/107 ━━━━━━━━━━━━━━━━━━━━ 11s 300ms/step - loss: 0.5831

 68/107 ━━━━━━━━━━━━━━━━━━━━ 11s 300ms/step - loss: 0.5829

 69/107 ━━━━━━━━━━━━━━━━━━━━ 11s 299ms/step - loss: 0.5828

 70/107 ━━━━━━━━━━━━━━━━━━━━ 11s 299ms/step - loss: 0.5826

 71/107 ━━━━━━━━━━━━━━━━━━━━ 10s 299ms/step - loss: 0.5825

 72/107 ━━━━━━━━━━━━━━━━━━━━ 10s 299ms/step - loss: 0.5824

 73/107 ━━━━━━━━━━━━━━━━━━━━ 10s 299ms/step - loss: 0.5822

 74/107 ━━━━━━━━━━━━━━━━━━━━ 9s 299ms/step - loss: 0.5821

 75/107 ━━━━━━━━━━━━━━━━━━━━ 9s 299ms/step - loss: 0.5820

 76/107 ━━━━━━━━━━━━━━━━━━━━ 9s 299ms/step - loss: 0.5819

 77/107 ━━━━━━━━━━━━━━━━━━━━ 8s 299ms/step - loss: 0.5818

 78/107 ━━━━━━━━━━━━━━━━━━━━ 8s 299ms/step - loss: 0.5817

 79/107 ━━━━━━━━━━━━━━━━━━━━ 8s 299ms/step - loss: 0.5816

 80/107 ━━━━━━━━━━━━━━━━━━━━ 8s 299ms/step - loss: 0.5815

 81/107 ━━━━━━━━━━━━━━━━━━━━ 7s 299ms/step - loss: 0.5814

 82/107 ━━━━━━━━━━━━━━━━━━━━ 7s 299ms/step - loss: 0.5814

 83/107 ━━━━━━━━━━━━━━━━━━━━ 7s 298ms/step - loss: 0.5812

 84/107 ━━━━━━━━━━━━━━━━━━━━ 6s 298ms/step - loss: 0.5811

 85/107 ━━━━━━━━━━━━━━━━━━━━ 6s 298ms/step - loss: 0.5810

 86/107 ━━━━━━━━━━━━━━━━━━━━ 6s 298ms/step - loss: 0.5809

 87/107 ━━━━━━━━━━━━━━━━━━━━ 5s 298ms/step - loss: 0.5809

 88/107 ━━━━━━━━━━━━━━━━━━━━ 5s 298ms/step - loss: 0.5808

 89/107 ━━━━━━━━━━━━━━━━━━━━ 5s 298ms/step - loss: 0.5807

 90/107 ━━━━━━━━━━━━━━━━━━━━ 5s 298ms/step - loss: 0.5806

 91/107 ━━━━━━━━━━━━━━━━━━━━ 4s 298ms/step - loss: 0.5806

 92/107 ━━━━━━━━━━━━━━━━━━━━ 4s 297ms/step - loss: 0.5805

 93/107 ━━━━━━━━━━━━━━━━━━━━ 4s 297ms/step - loss: 0.5804

 94/107 ━━━━━━━━━━━━━━━━━━━━ 3s 297ms/step - loss: 0.5804

 95/107 ━━━━━━━━━━━━━━━━━━━━ 3s 297ms/step - loss: 0.5803

 96/107 ━━━━━━━━━━━━━━━━━━━━ 3s 297ms/step - loss: 0.5803

 97/107 ━━━━━━━━━━━━━━━━━━━━ 2s 298ms/step - loss: 0.5802

 98/107 ━━━━━━━━━━━━━━━━━━━━ 2s 298ms/step - loss: 0.5802

 99/107 ━━━━━━━━━━━━━━━━━━━━ 2s 298ms/step - loss: 0.5801

100/107 ━━━━━━━━━━━━━━━━━━━━ 2s 298ms/step - loss: 0.5801

101/107 ━━━━━━━━━━━━━━━━━━━━ 1s 298ms/step - loss: 0.5800

102/107 ━━━━━━━━━━━━━━━━━━━━ 1s 298ms/step - loss: 0.5800

103/107 ━━━━━━━━━━━━━━━━━━━━ 1s 298ms/step - loss: 0.5800

104/107 ━━━━━━━━━━━━━━━━━━━━ 0s 298ms/step - loss: 0.5799

105/107 ━━━━━━━━━━━━━━━━━━━━ 0s 298ms/step - loss: 0.5799

106/107 ━━━━━━━━━━━━━━━━━━━━ 0s 298ms/step - loss: 0.5798

107/107 ━━━━━━━━━━━━━━━━━━━━ 0s 298ms/step - loss: 0.5798

107/107 ━━━━━━━━━━━━━━━━━━━━ 33s 308ms/step - loss: 0.5761 - val_loss: 0.9496

Epoch 4/10

  1/107 ━━━━━━━━━━━━━━━━━━━━ 31s 300ms/step - loss: 0.5039

  2/107 ━━━━━━━━━━━━━━━━━━━━ 30s 288ms/step - loss: 0.4896

  3/107 ━━━━━━━━━━━━━━━━━━━━ 30s 290ms/step - loss: 0.4821

  4/107 ━━━━━━━━━━━━━━━━━━━━ 29s 290ms/step - loss: 0.4799

  5/107 ━━━━━━━━━━━━━━━━━━━━ 29s 291ms/step - loss: 0.4790

  6/107 ━━━━━━━━━━━━━━━━━━━━ 29s 291ms/step - loss: 0.4795

  7/107 ━━━━━━━━━━━━━━━━━━━━ 29s 291ms/step - loss: 0.4800

  8/107 ━━━━━━━━━━━━━━━━━━━━ 28s 292ms/step - loss: 0.4802

  9/107 ━━━━━━━━━━━━━━━━━━━━ 28s 291ms/step - loss: 0.4797

 10/107 ━━━━━━━━━━━━━━━━━━━━ 28s 291ms/step - loss: 0.4796

 11/107 ━━━━━━━━━━━━━━━━━━━━ 27s 291ms/step - loss: 0.4795

 12/107 ━━━━━━━━━━━━━━━━━━━━ 27s 291ms/step - loss: 0.4795

 13/107 ━━━━━━━━━━━━━━━━━━━━ 27s 291ms/step - loss: 0.4793

 14/107 ━━━━━━━━━━━━━━━━━━━━ 27s 292ms/step - loss: 0.4793

 15/107 ━━━━━━━━━━━━━━━━━━━━ 26s 292ms/step - loss: 0.4796

 16/107 ━━━━━━━━━━━━━━━━━━━━ 26s 292ms/step - loss: 0.4801

 17/107 ━━━━━━━━━━━━━━━━━━━━ 26s 292ms/step - loss: 0.4802

 18/107 ━━━━━━━━━━━━━━━━━━━━ 25s 292ms/step - loss: 0.4803

 19/107 ━━━━━━━━━━━━━━━━━━━━ 25s 293ms/step - loss: 0.4802

 20/107 ━━━━━━━━━━━━━━━━━━━━ 25s 296ms/step - loss: 0.4801

 21/107 ━━━━━━━━━━━━━━━━━━━━ 25s 296ms/step - loss: 0.4800

 22/107 ━━━━━━━━━━━━━━━━━━━━ 25s 296ms/step - loss: 0.4799

 23/107 ━━━━━━━━━━━━━━━━━━━━ 24s 296ms/step - loss: 0.4799

 24/107 ━━━━━━━━━━━━━━━━━━━━ 24s 296ms/step - loss: 0.4796

 25/107 ━━━━━━━━━━━━━━━━━━━━ 24s 296ms/step - loss: 0.4793

 26/107 ━━━━━━━━━━━━━━━━━━━━ 23s 295ms/step - loss: 0.4789

 27/107 ━━━━━━━━━━━━━━━━━━━━ 23s 296ms/step - loss: 0.4785

 28/107 ━━━━━━━━━━━━━━━━━━━━ 23s 296ms/step - loss: 0.4781

 29/107 ━━━━━━━━━━━━━━━━━━━━ 23s 296ms/step - loss: 0.4776

 30/107 ━━━━━━━━━━━━━━━━━━━━ 22s 296ms/step - loss: 0.4772

 31/107 ━━━━━━━━━━━━━━━━━━━━ 22s 296ms/step - loss: 0.4768

 32/107 ━━━━━━━━━━━━━━━━━━━━ 22s 296ms/step - loss: 0.4764

 33/107 ━━━━━━━━━━━━━━━━━━━━ 21s 296ms/step - loss: 0.4759

 34/107 ━━━━━━━━━━━━━━━━━━━━ 21s 296ms/step - loss: 0.4755

 35/107 ━━━━━━━━━━━━━━━━━━━━ 21s 296ms/step - loss: 0.4752

 36/107 ━━━━━━━━━━━━━━━━━━━━ 21s 296ms/step - loss: 0.4749

 37/107 ━━━━━━━━━━━━━━━━━━━━ 20s 296ms/step - loss: 0.4746

 38/107 ━━━━━━━━━━━━━━━━━━━━ 20s 297ms/step - loss: 0.4743

 39/107 ━━━━━━━━━━━━━━━━━━━━ 20s 297ms/step - loss: 0.4740

 40/107 ━━━━━━━━━━━━━━━━━━━━ 19s 297ms/step - loss: 0.4738

 41/107 ━━━━━━━━━━━━━━━━━━━━ 19s 297ms/step - loss: 0.4736

 42/107 ━━━━━━━━━━━━━━━━━━━━ 19s 297ms/step - loss: 0.4734

 43/107 ━━━━━━━━━━━━━━━━━━━━ 19s 297ms/step - loss: 0.4732

 44/107 ━━━━━━━━━━━━━━━━━━━━ 18s 297ms/step - loss: 0.4730

 45/107 ━━━━━━━━━━━━━━━━━━━━ 18s 297ms/step - loss: 0.4728

 46/107 ━━━━━━━━━━━━━━━━━━━━ 18s 297ms/step - loss: 0.4726

 47/107 ━━━━━━━━━━━━━━━━━━━━ 17s 297ms/step - loss: 0.4724

 48/107 ━━━━━━━━━━━━━━━━━━━━ 17s 297ms/step - loss: 0.4721

 49/107 ━━━━━━━━━━━━━━━━━━━━ 17s 297ms/step - loss: 0.4719

 50/107 ━━━━━━━━━━━━━━━━━━━━ 16s 297ms/step - loss: 0.4717

 51/107 ━━━━━━━━━━━━━━━━━━━━ 16s 297ms/step - loss: 0.4715

 52/107 ━━━━━━━━━━━━━━━━━━━━ 16s 297ms/step - loss: 0.4712

 53/107 ━━━━━━━━━━━━━━━━━━━━ 16s 298ms/step - loss: 0.4710

 54/107 ━━━━━━━━━━━━━━━━━━━━ 15s 298ms/step - loss: 0.4708

 55/107 ━━━━━━━━━━━━━━━━━━━━ 15s 298ms/step - loss: 0.4706

 56/107 ━━━━━━━━━━━━━━━━━━━━ 15s 298ms/step - loss: 0.4704

 57/107 ━━━━━━━━━━━━━━━━━━━━ 14s 298ms/step - loss: 0.4702

 58/107 ━━━━━━━━━━━━━━━━━━━━ 14s 298ms/step - loss: 0.4701

 59/107 ━━━━━━━━━━━━━━━━━━━━ 14s 298ms/step - loss: 0.4699

 60/107 ━━━━━━━━━━━━━━━━━━━━ 14s 298ms/step - loss: 0.4698

 61/107 ━━━━━━━━━━━━━━━━━━━━ 13s 298ms/step - loss: 0.4697

 62/107 ━━━━━━━━━━━━━━━━━━━━ 13s 298ms/step - loss: 0.4696

 63/107 ━━━━━━━━━━━━━━━━━━━━ 13s 298ms/step - loss: 0.4695

 64/107 ━━━━━━━━━━━━━━━━━━━━ 12s 298ms/step - loss: 0.4694

 65/107 ━━━━━━━━━━━━━━━━━━━━ 12s 298ms/step - loss: 0.4693

 66/107 ━━━━━━━━━━━━━━━━━━━━ 12s 298ms/step - loss: 0.4693

 67/107 ━━━━━━━━━━━━━━━━━━━━ 11s 298ms/step - loss: 0.4692

 68/107 ━━━━━━━━━━━━━━━━━━━━ 11s 298ms/step - loss: 0.4692

 69/107 ━━━━━━━━━━━━━━━━━━━━ 11s 298ms/step - loss: 0.4691

 70/107 ━━━━━━━━━━━━━━━━━━━━ 11s 298ms/step - loss: 0.4690

 71/107 ━━━━━━━━━━━━━━━━━━━━ 10s 298ms/step - loss: 0.4690

 72/107 ━━━━━━━━━━━━━━━━━━━━ 10s 298ms/step - loss: 0.4690

 73/107 ━━━━━━━━━━━━━━━━━━━━ 10s 297ms/step - loss: 0.4689

 74/107 ━━━━━━━━━━━━━━━━━━━━ 9s 297ms/step - loss: 0.4689

 75/107 ━━━━━━━━━━━━━━━━━━━━ 9s 297ms/step - loss: 0.4689

 76/107 ━━━━━━━━━━━━━━━━━━━━ 9s 297ms/step - loss: 0.4688

 77/107 ━━━━━━━━━━━━━━━━━━━━ 8s 297ms/step - loss: 0.4688

 78/107 ━━━━━━━━━━━━━━━━━━━━ 8s 297ms/step - loss: 0.4688

 79/107 ━━━━━━━━━━━━━━━━━━━━ 8s 297ms/step - loss: 0.4688

 80/107 ━━━━━━━━━━━━━━━━━━━━ 8s 297ms/step - loss: 0.4688

 81/107 ━━━━━━━━━━━━━━━━━━━━ 7s 297ms/step - loss: 0.4688

 82/107 ━━━━━━━━━━━━━━━━━━━━ 7s 297ms/step - loss: 0.4688

 83/107 ━━━━━━━━━━━━━━━━━━━━ 7s 297ms/step - loss: 0.4688

 84/107 ━━━━━━━━━━━━━━━━━━━━ 6s 297ms/step - loss: 0.4688

 85/107 ━━━━━━━━━━━━━━━━━━━━ 6s 297ms/step - loss: 0.4688

 86/107 ━━━━━━━━━━━━━━━━━━━━ 6s 297ms/step - loss: 0.4688

 87/107 ━━━━━━━━━━━━━━━━━━━━ 5s 297ms/step - loss: 0.4688

 88/107 ━━━━━━━━━━━━━━━━━━━━ 5s 297ms/step - loss: 0.4688

 89/107 ━━━━━━━━━━━━━━━━━━━━ 5s 297ms/step - loss: 0.4688

 90/107 ━━━━━━━━━━━━━━━━━━━━ 5s 297ms/step - loss: 0.4687

 91/107 ━━━━━━━━━━━━━━━━━━━━ 4s 297ms/step - loss: 0.4687

 92/107 ━━━━━━━━━━━━━━━━━━━━ 4s 297ms/step - loss: 0.4687

 93/107 ━━━━━━━━━━━━━━━━━━━━ 4s 297ms/step - loss: 0.4687

 94/107 ━━━━━━━━━━━━━━━━━━━━ 3s 297ms/step - loss: 0.4687

 95/107 ━━━━━━━━━━━━━━━━━━━━ 3s 297ms/step - loss: 0.4687

 96/107 ━━━━━━━━━━━━━━━━━━━━ 3s 297ms/step - loss: 0.4687

 97/107 ━━━━━━━━━━━━━━━━━━━━ 2s 297ms/step - loss: 0.4687

 98/107 ━━━━━━━━━━━━━━━━━━━━ 2s 297ms/step - loss: 0.4687

 99/107 ━━━━━━━━━━━━━━━━━━━━ 2s 297ms/step - loss: 0.4687

100/107 ━━━━━━━━━━━━━━━━━━━━ 2s 297ms/step - loss: 0.4687

101/107 ━━━━━━━━━━━━━━━━━━━━ 1s 297ms/step - loss: 0.4687

102/107 ━━━━━━━━━━━━━━━━━━━━ 1s 297ms/step - loss: 0.4687

103/107 ━━━━━━━━━━━━━━━━━━━━ 1s 297ms/step - loss: 0.4687

104/107 ━━━━━━━━━━━━━━━━━━━━ 0s 297ms/step - loss: 0.4687

105/107 ━━━━━━━━━━━━━━━━━━━━ 0s 297ms/step - loss: 0.4687

106/107 ━━━━━━━━━━━━━━━━━━━━ 0s 297ms/step - loss: 0.4687

107/107 ━━━━━━━━━━━━━━━━━━━━ 0s 297ms/step - loss: 0.4688

107/107 ━━━━━━━━━━━━━━━━━━━━ 33s 309ms/step - loss: 0.4712 - val_loss: 1.1027

Epoch 5/10

  1/107 ━━━━━━━━━━━━━━━━━━━━ 32s 310ms/step - loss: 0.4116

  2/107 ━━━━━━━━━━━━━━━━━━━━ 32s 309ms/step - loss: 0.4106

  3/107 ━━━━━━━━━━━━━━━━━━━━ 31s 300ms/step - loss: 0.4114

  4/107 ━━━━━━━━━━━━━━━━━━━━ 30s 296ms/step - loss: 0.4140

  5/107 ━━━━━━━━━━━━━━━━━━━━ 30s 295ms/step - loss: 0.4146

  6/107 ━━━━━━━━━━━━━━━━━━━━ 29s 295ms/step - loss: 0.4139

  7/107 ━━━━━━━━━━━━━━━━━━━━ 29s 295ms/step - loss: 0.4133

  8/107 ━━━━━━━━━━━━━━━━━━━━ 29s 296ms/step - loss: 0.4130

  9/107 ━━━━━━━━━━━━━━━━━━━━ 29s 296ms/step - loss: 0.4119

 10/107 ━━━━━━━━━━━━━━━━━━━━ 29s 303ms/step - loss: 0.4106

 11/107 ━━━━━━━━━━━━━━━━━━━━ 29s 302ms/step - loss: 0.4091

 12/107 ━━━━━━━━━━━━━━━━━━━━ 28s 301ms/step - loss: 0.4081

 13/107 ━━━━━━━━━━━━━━━━━━━━ 28s 301ms/step - loss: 0.4076

 14/107 ━━━━━━━━━━━━━━━━━━━━ 27s 300ms/step - loss: 0.4073

 15/107 ━━━━━━━━━━━━━━━━━━━━ 27s 299ms/step - loss: 0.4070

 16/107 ━━━━━━━━━━━━━━━━━━━━ 27s 299ms/step - loss: 0.4067

 17/107 ━━━━━━━━━━━━━━━━━━━━ 26s 298ms/step - loss: 0.4068

 18/107 ━━━━━━━━━━━━━━━━━━━━ 26s 299ms/step - loss: 0.4069

 19/107 ━━━━━━━━━━━━━━━━━━━━ 26s 299ms/step - loss: 0.4070

 20/107 ━━━━━━━━━━━━━━━━━━━━ 25s 299ms/step - loss: 0.4069

 21/107 ━━━━━━━━━━━━━━━━━━━━ 25s 298ms/step - loss: 0.4068

 22/107 ━━━━━━━━━━━━━━━━━━━━ 25s 298ms/step - loss: 0.4066

 23/107 ━━━━━━━━━━━━━━━━━━━━ 25s 298ms/step - loss: 0.4064

 24/107 ━━━━━━━━━━━━━━━━━━━━ 24s 298ms/step - loss: 0.4062

 25/107 ━━━━━━━━━━━━━━━━━━━━ 24s 299ms/step - loss: 0.4060

 26/107 ━━━━━━━━━━━━━━━━━━━━ 24s 299ms/step - loss: 0.4058

 27/107 ━━━━━━━━━━━━━━━━━━━━ 23s 299ms/step - loss: 0.4057

 28/107 ━━━━━━━━━━━━━━━━━━━━ 23s 299ms/step - loss: 0.4056

 29/107 ━━━━━━━━━━━━━━━━━━━━ 23s 299ms/step - loss: 0.4055

 30/107 ━━━━━━━━━━━━━━━━━━━━ 22s 299ms/step - loss: 0.4054

 31/107 ━━━━━━━━━━━━━━━━━━━━ 22s 298ms/step - loss: 0.4054

 32/107 ━━━━━━━━━━━━━━━━━━━━ 22s 298ms/step - loss: 0.4054

 33/107 ━━━━━━━━━━━━━━━━━━━━ 22s 298ms/step - loss: 0.4053

 34/107 ━━━━━━━━━━━━━━━━━━━━ 21s 298ms/step - loss: 0.4052

 35/107 ━━━━━━━━━━━━━━━━━━━━ 21s 298ms/step - loss: 0.4051

 36/107 ━━━━━━━━━━━━━━━━━━━━ 21s 298ms/step - loss: 0.4049

 37/107 ━━━━━━━━━━━━━━━━━━━━ 20s 298ms/step - loss: 0.4048

 38/107 ━━━━━━━━━━━━━━━━━━━━ 20s 298ms/step - loss: 0.4047

 39/107 ━━━━━━━━━━━━━━━━━━━━ 20s 298ms/step - loss: 0.4045

 40/107 ━━━━━━━━━━━━━━━━━━━━ 19s 298ms/step - loss: 0.4044

 41/107 ━━━━━━━━━━━━━━━━━━━━ 19s 298ms/step - loss: 0.4042

 42/107 ━━━━━━━━━━━━━━━━━━━━ 19s 298ms/step - loss: 0.4040

 43/107 ━━━━━━━━━━━━━━━━━━━━ 19s 299ms/step - loss: 0.4038

 44/107 ━━━━━━━━━━━━━━━━━━━━ 18s 299ms/step - loss: 0.4036

 45/107 ━━━━━━━━━━━━━━━━━━━━ 18s 299ms/step - loss: 0.4034

 46/107 ━━━━━━━━━━━━━━━━━━━━ 18s 299ms/step - loss: 0.4033

 47/107 ━━━━━━━━━━━━━━━━━━━━ 17s 298ms/step - loss: 0.4032

 48/107 ━━━━━━━━━━━━━━━━━━━━ 17s 299ms/step - loss: 0.4030

 49/107 ━━━━━━━━━━━━━━━━━━━━ 17s 299ms/step - loss: 0.4030

 50/107 ━━━━━━━━━━━━━━━━━━━━ 17s 299ms/step - loss: 0.4029

 51/107 ━━━━━━━━━━━━━━━━━━━━ 16s 299ms/step - loss: 0.4029

 52/107 ━━━━━━━━━━━━━━━━━━━━ 16s 298ms/step - loss: 0.4029

 53/107 ━━━━━━━━━━━━━━━━━━━━ 16s 298ms/step - loss: 0.4029

 54/107 ━━━━━━━━━━━━━━━━━━━━ 15s 298ms/step - loss: 0.4028

 55/107 ━━━━━━━━━━━━━━━━━━━━ 15s 298ms/step - loss: 0.4028

 56/107 ━━━━━━━━━━━━━━━━━━━━ 15s 298ms/step - loss: 0.4027

 57/107 ━━━━━━━━━━━━━━━━━━━━ 14s 298ms/step - loss: 0.4027

 58/107 ━━━━━━━━━━━━━━━━━━━━ 14s 298ms/step - loss: 0.4026

 59/107 ━━━━━━━━━━━━━━━━━━━━ 14s 298ms/step - loss: 0.4026

 60/107 ━━━━━━━━━━━━━━━━━━━━ 14s 298ms/step - loss: 0.4026

 61/107 ━━━━━━━━━━━━━━━━━━━━ 13s 298ms/step - loss: 0.4026

 62/107 ━━━━━━━━━━━━━━━━━━━━ 13s 298ms/step - loss: 0.4026

 63/107 ━━━━━━━━━━━━━━━━━━━━ 13s 298ms/step - loss: 0.4026

 64/107 ━━━━━━━━━━━━━━━━━━━━ 12s 298ms/step - loss: 0.4025

 65/107 ━━━━━━━━━━━━━━━━━━━━ 12s 297ms/step - loss: 0.4025

 66/107 ━━━━━━━━━━━━━━━━━━━━ 12s 297ms/step - loss: 0.4025

 67/107 ━━━━━━━━━━━━━━━━━━━━ 11s 297ms/step - loss: 0.4025

 68/107 ━━━━━━━━━━━━━━━━━━━━ 11s 297ms/step - loss: 0.4025

 69/107 ━━━━━━━━━━━━━━━━━━━━ 11s 297ms/step - loss: 0.4026

 70/107 ━━━━━━━━━━━━━━━━━━━━ 10s 297ms/step - loss: 0.4026

 71/107 ━━━━━━━━━━━━━━━━━━━━ 10s 297ms/step - loss: 0.4026

 72/107 ━━━━━━━━━━━━━━━━━━━━ 10s 297ms/step - loss: 0.4026

 73/107 ━━━━━━━━━━━━━━━━━━━━ 10s 297ms/step - loss: 0.4026

 74/107 ━━━━━━━━━━━━━━━━━━━━ 9s 297ms/step - loss: 0.4027

 75/107 ━━━━━━━━━━━━━━━━━━━━ 9s 297ms/step - loss: 0.4028

 76/107 ━━━━━━━━━━━━━━━━━━━━ 9s 297ms/step - loss: 0.4028

 77/107 ━━━━━━━━━━━━━━━━━━━━ 8s 298ms/step - loss: 0.4029

 78/107 ━━━━━━━━━━━━━━━━━━━━ 8s 298ms/step - loss: 0.4029

 79/107 ━━━━━━━━━━━━━━━━━━━━ 8s 298ms/step - loss: 0.4030

 80/107 ━━━━━━━━━━━━━━━━━━━━ 8s 298ms/step - loss: 0.4030

 81/107 ━━━━━━━━━━━━━━━━━━━━ 7s 298ms/step - loss: 0.4031

 82/107 ━━━━━━━━━━━━━━━━━━━━ 7s 298ms/step - loss: 0.4032

 83/107 ━━━━━━━━━━━━━━━━━━━━ 7s 298ms/step - loss: 0.4032

 84/107 ━━━━━━━━━━━━━━━━━━━━ 6s 298ms/step - loss: 0.4033

 85/107 ━━━━━━━━━━━━━━━━━━━━ 6s 298ms/step - loss: 0.4034

 86/107 ━━━━━━━━━━━━━━━━━━━━ 6s 298ms/step - loss: 0.4034

 87/107 ━━━━━━━━━━━━━━━━━━━━ 5s 298ms/step - loss: 0.4035

 88/107 ━━━━━━━━━━━━━━━━━━━━ 5s 298ms/step - loss: 0.4035

 89/107 ━━━━━━━━━━━━━━━━━━━━ 5s 297ms/step - loss: 0.4036

 90/107 ━━━━━━━━━━━━━━━━━━━━ 5s 297ms/step - loss: 0.4036

 91/107 ━━━━━━━━━━━━━━━━━━━━ 4s 297ms/step - loss: 0.4037

 92/107 ━━━━━━━━━━━━━━━━━━━━ 4s 297ms/step - loss: 0.4038

 93/107 ━━━━━━━━━━━━━━━━━━━━ 4s 297ms/step - loss: 0.4038

 94/107 ━━━━━━━━━━━━━━━━━━━━ 3s 297ms/step - loss: 0.4039

 95/107 ━━━━━━━━━━━━━━━━━━━━ 3s 297ms/step - loss: 0.4039

 96/107 ━━━━━━━━━━━━━━━━━━━━ 3s 297ms/step - loss: 0.4040

 97/107 ━━━━━━━━━━━━━━━━━━━━ 2s 297ms/step - loss: 0.4040

 98/107 ━━━━━━━━━━━━━━━━━━━━ 2s 297ms/step - loss: 0.4041

 99/107 ━━━━━━━━━━━━━━━━━━━━ 2s 297ms/step - loss: 0.4041

100/107 ━━━━━━━━━━━━━━━━━━━━ 2s 297ms/step - loss: 0.4041

101/107 ━━━━━━━━━━━━━━━━━━━━ 1s 297ms/step - loss: 0.4042

102/107 ━━━━━━━━━━━━━━━━━━━━ 1s 297ms/step - loss: 0.4042

103/107 ━━━━━━━━━━━━━━━━━━━━ 1s 297ms/step - loss: 0.4043

104/107 ━━━━━━━━━━━━━━━━━━━━ 0s 297ms/step - loss: 0.4043

105/107 ━━━━━━━━━━━━━━━━━━━━ 0s 296ms/step - loss: 0.4043

106/107 ━━━━━━━━━━━━━━━━━━━━ 0s 296ms/step - loss: 0.4044

107/107 ━━━━━━━━━━━━━━━━━━━━ 0s 296ms/step - loss: 0.4044

107/107 ━━━━━━━━━━━━━━━━━━━━ 33s 308ms/step - loss: 0.4076 - val_loss: 1.2345

  saved /kaggle/working/models/lstm_with_emoji.keras
  threshold 0.55 | dev Micro-F1 55.65%

==============================================================
  Transformer
==============================================================

--- Transformer | Without Emoji ---
  Phase 1: hyper-parameter search
    cfg1: lr=0.001 embed=128 batch=64

      -> Micro-F1 54.81%
    cfg2: lr=0.0005 embed=256 batch=32

      -> Micro-F1 49.38%
    cfg3: lr=0.002 embed=128 batch=64

      -> Micro-F1 47.43%

  config  micro_f1  macro_f1  label_accuracy  threshold model          track
0   cfg1     54.81     47.77           76.16       0.50  BERT  Without Emoji
1   cfg2     49.38     44.07           73.26       0.55  BERT  Without Emoji
2   cfg3     47.43     45.92           66.27       0.50  BERT  Without Emoji

  best config: cfg1
  Phase 2: final training

Epoch 1/10

  1/107 ━━━━━━━━━━━━━━━━━━━━ 7:43 4s/step - loss: 1.1616

  2/107 ━━━━━━━━━━━━━━━━━━━━ 33s 317ms/step - loss: 1.1619

  3/107 ━━━━━━━━━━━━━━━━━━━━ 32s 317ms/step - loss: 1.1557

  4/107 ━━━━━━━━━━━━━━━━━━━━ 32s 312ms/step - loss: 1.1560

  5/107 ━━━━━━━━━━━━━━━━━━━━ 32s 320ms/step - loss: 1.1575

  6/107 ━━━━━━━━━━━━━━━━━━━━ 32s 320ms/step - loss: 1.1571

  7/107 ━━━━━━━━━━━━━━━━━━━━ 31s 318ms/step - loss: 1.1579

  8/107 ━━━━━━━━━━━━━━━━━━━━ 31s 315ms/step - loss: 1.1585

  9/107 ━━━━━━━━━━━━━━━━━━━━ 30s 314ms/step - loss: 1.1588

 10/107 ━━━━━━━━━━━━━━━━━━━━ 30s 318ms/step - loss: 1.1589

 11/107 ━━━━━━━━━━━━━━━━━━━━ 30s 316ms/step - loss: 1.1588

 12/107 ━━━━━━━━━━━━━━━━━━━━ 29s 314ms/step - loss: 1.1586

 13/107 ━━━━━━━━━━━━━━━━━━━━ 29s 312ms/step - loss: 1.1581

 14/107 ━━━━━━━━━━━━━━━━━━━━ 29s 312ms/step - loss: 1.1576

 15/107 ━━━━━━━━━━━━━━━━━━━━ 28s 311ms/step - loss: 1.1570

 16/107 ━━━━━━━━━━━━━━━━━━━━ 28s 311ms/step - loss: 1.1564

 17/107 ━━━━━━━━━━━━━━━━━━━━ 28s 312ms/step - loss: 1.1552

 18/107 ━━━━━━━━━━━━━━━━━━━━ 27s 312ms/step - loss: 1.1540

 19/107 ━━━━━━━━━━━━━━━━━━━━ 27s 311ms/step - loss: 1.1526

 20/107 ━━━━━━━━━━━━━━━━━━━━ 26s 309ms/step - loss: 1.1511

 21/107 ━━━━━━━━━━━━━━━━━━━━ 26s 309ms/step - loss: 1.1498

 22/107 ━━━━━━━━━━━━━━━━━━━━ 26s 309ms/step - loss: 1.1483

 23/107 ━━━━━━━━━━━━━━━━━━━━ 25s 309ms/step - loss: 1.1467

 24/107 ━━━━━━━━━━━━━━━━━━━━ 25s 311ms/step - loss: 1.1452

 25/107 ━━━━━━━━━━━━━━━━━━━━ 25s 311ms/step - loss: 1.1439

 26/107 ━━━━━━━━━━━━━━━━━━━━ 25s 310ms/step - loss: 1.1426

 27/107 ━━━━━━━━━━━━━━━━━━━━ 24s 310ms/step - loss: 1.1416

 28/107 ━━━━━━━━━━━━━━━━━━━━ 24s 310ms/step - loss: 1.1405

 29/107 ━━━━━━━━━━━━━━━━━━━━ 24s 310ms/step - loss: 1.1394

 30/107 ━━━━━━━━━━━━━━━━━━━━ 23s 311ms/step - loss: 1.1383

 31/107 ━━━━━━━━━━━━━━━━━━━━ 23s 311ms/step - loss: 1.1373

 32/107 ━━━━━━━━━━━━━━━━━━━━ 23s 311ms/step - loss: 1.1363

 33/107 ━━━━━━━━━━━━━━━━━━━━ 22s 311ms/step - loss: 1.1352

 34/107 ━━━━━━━━━━━━━━━━━━━━ 22s 310ms/step - loss: 1.1342

 35/107 ━━━━━━━━━━━━━━━━━━━━ 22s 310ms/step - loss: 1.1333

 36/107 ━━━━━━━━━━━━━━━━━━━━ 22s 310ms/step - loss: 1.1324

 37/107 ━━━━━━━━━━━━━━━━━━━━ 21s 310ms/step - loss: 1.1314

 38/107 ━━━━━━━━━━━━━━━━━━━━ 21s 309ms/step - loss: 1.1304

 39/107 ━━━━━━━━━━━━━━━━━━━━ 20s 309ms/step - loss: 1.1294

 40/107 ━━━━━━━━━━━━━━━━━━━━ 20s 308ms/step - loss: 1.1284

 41/107 ━━━━━━━━━━━━━━━━━━━━ 20s 309ms/step - loss: 1.1273

 42/107 ━━━━━━━━━━━━━━━━━━━━ 20s 308ms/step - loss: 1.1263

 43/107 ━━━━━━━━━━━━━━━━━━━━ 19s 307ms/step - loss: 1.1253

 44/107 ━━━━━━━━━━━━━━━━━━━━ 19s 307ms/step - loss: 1.1243

 45/107 ━━━━━━━━━━━━━━━━━━━━ 19s 307ms/step - loss: 1.1233

 46/107 ━━━━━━━━━━━━━━━━━━━━ 18s 307ms/step - loss: 1.1223

 47/107 ━━━━━━━━━━━━━━━━━━━━ 18s 307ms/step - loss: 1.1214

 48/107 ━━━━━━━━━━━━━━━━━━━━ 18s 307ms/step - loss: 1.1205

 49/107 ━━━━━━━━━━━━━━━━━━━━ 17s 308ms/step - loss: 1.1195

 50/107 ━━━━━━━━━━━━━━━━━━━━ 17s 307ms/step - loss: 1.1186

 51/107 ━━━━━━━━━━━━━━━━━━━━ 17s 308ms/step - loss: 1.1177

 52/107 ━━━━━━━━━━━━━━━━━━━━ 16s 307ms/step - loss: 1.1168

 53/107 ━━━━━━━━━━━━━━━━━━━━ 16s 307ms/step - loss: 1.1160

 54/107 ━━━━━━━━━━━━━━━━━━━━ 16s 307ms/step - loss: 1.1151

 55/107 ━━━━━━━━━━━━━━━━━━━━ 15s 307ms/step - loss: 1.1143

 56/107 ━━━━━━━━━━━━━━━━━━━━ 15s 308ms/step - loss: 1.1135

 57/107 ━━━━━━━━━━━━━━━━━━━━ 15s 307ms/step - loss: 1.1127

 58/107 ━━━━━━━━━━━━━━━━━━━━ 15s 307ms/step - loss: 1.1119

 59/107 ━━━━━━━━━━━━━━━━━━━━ 14s 307ms/step - loss: 1.1112

 60/107 ━━━━━━━━━━━━━━━━━━━━ 14s 308ms/step - loss: 1.1104

 61/107 ━━━━━━━━━━━━━━━━━━━━ 14s 307ms/step - loss: 1.1096

 62/107 ━━━━━━━━━━━━━━━━━━━━ 13s 307ms/step - loss: 1.1088

 63/107 ━━━━━━━━━━━━━━━━━━━━ 13s 307ms/step - loss: 1.1081

 64/107 ━━━━━━━━━━━━━━━━━━━━ 13s 307ms/step - loss: 1.1073

 65/107 ━━━━━━━━━━━━━━━━━━━━ 12s 307ms/step - loss: 1.1065

 66/107 ━━━━━━━━━━━━━━━━━━━━ 12s 307ms/step - loss: 1.1057

 67/107 ━━━━━━━━━━━━━━━━━━━━ 12s 307ms/step - loss: 1.1049

 68/107 ━━━━━━━━━━━━━━━━━━━━ 11s 307ms/step - loss: 1.1042

 69/107 ━━━━━━━━━━━━━━━━━━━━ 11s 307ms/step - loss: 1.1034

 70/107 ━━━━━━━━━━━━━━━━━━━━ 11s 307ms/step - loss: 1.1026

 71/107 ━━━━━━━━━━━━━━━━━━━━ 11s 307ms/step - loss: 1.1019

 72/107 ━━━━━━━━━━━━━━━━━━━━ 10s 307ms/step - loss: 1.1011

 73/107 ━━━━━━━━━━━━━━━━━━━━ 10s 306ms/step - loss: 1.1004

 74/107 ━━━━━━━━━━━━━━━━━━━━ 10s 306ms/step - loss: 1.0997

 75/107 ━━━━━━━━━━━━━━━━━━━━ 9s 307ms/step - loss: 1.0990

 76/107 ━━━━━━━━━━━━━━━━━━━━ 9s 306ms/step - loss: 1.0983

 77/107 ━━━━━━━━━━━━━━━━━━━━ 9s 306ms/step - loss: 1.0976

 78/107 ━━━━━━━━━━━━━━━━━━━━ 8s 307ms/step - loss: 1.0970

 79/107 ━━━━━━━━━━━━━━━━━━━━ 8s 307ms/step - loss: 1.0963

 80/107 ━━━━━━━━━━━━━━━━━━━━ 8s 306ms/step - loss: 1.0957

 81/107 ━━━━━━━━━━━━━━━━━━━━ 7s 306ms/step - loss: 1.0951

 82/107 ━━━━━━━━━━━━━━━━━━━━ 7s 306ms/step - loss: 1.0944

 83/107 ━━━━━━━━━━━━━━━━━━━━ 7s 306ms/step - loss: 1.0938

 84/107 ━━━━━━━━━━━━━━━━━━━━ 7s 306ms/step - loss: 1.0932

 85/107 ━━━━━━━━━━━━━━━━━━━━ 6s 306ms/step - loss: 1.0926

 86/107 ━━━━━━━━━━━━━━━━━━━━ 6s 306ms/step - loss: 1.0920

 87/107 ━━━━━━━━━━━━━━━━━━━━ 6s 306ms/step - loss: 1.0914

 88/107 ━━━━━━━━━━━━━━━━━━━━ 5s 306ms/step - loss: 1.0908

 89/107 ━━━━━━━━━━━━━━━━━━━━ 5s 307ms/step - loss: 1.0902

 90/107 ━━━━━━━━━━━━━━━━━━━━ 5s 306ms/step - loss: 1.0896

 91/107 ━━━━━━━━━━━━━━━━━━━━ 4s 306ms/step - loss: 1.0890

 92/107 ━━━━━━━━━━━━━━━━━━━━ 4s 306ms/step - loss: 1.0884

 93/107 ━━━━━━━━━━━━━━━━━━━━ 4s 306ms/step - loss: 1.0878

 94/107 ━━━━━━━━━━━━━━━━━━━━ 3s 306ms/step - loss: 1.0872

 95/107 ━━━━━━━━━━━━━━━━━━━━ 3s 306ms/step - loss: 1.0866

 96/107 ━━━━━━━━━━━━━━━━━━━━ 3s 307ms/step - loss: 1.0860

 97/107 ━━━━━━━━━━━━━━━━━━━━ 3s 306ms/step - loss: 1.0854

 98/107 ━━━━━━━━━━━━━━━━━━━━ 2s 307ms/step - loss: 1.0848

 99/107 ━━━━━━━━━━━━━━━━━━━━ 2s 307ms/step - loss: 1.0842

100/107 ━━━━━━━━━━━━━━━━━━━━ 2s 307ms/step - loss: 1.0836

101/107 ━━━━━━━━━━━━━━━━━━━━ 1s 307ms/step - loss: 1.0829

102/107 ━━━━━━━━━━━━━━━━━━━━ 1s 307ms/step - loss: 1.0823

103/107 ━━━━━━━━━━━━━━━━━━━━ 1s 307ms/step - loss: 1.0817

104/107 ━━━━━━━━━━━━━━━━━━━━ 0s 307ms/step - loss: 1.0811

105/107 ━━━━━━━━━━━━━━━━━━━━ 0s 307ms/step - loss: 1.0805

106/107 ━━━━━━━━━━━━━━━━━━━━ 0s 307ms/step - loss: 1.0799

107/107 ━━━━━━━━━━━━━━━━━━━━ 0s 307ms/step - loss: 1.0793

107/107 ━━━━━━━━━━━━━━━━━━━━ 39s 323ms/step - loss: 1.0174 - val_loss: 0.9607

Epoch 2/10

  1/107 ━━━━━━━━━━━━━━━━━━━━ 32s 305ms/step - loss: 0.7671

  2/107 ━━━━━━━━━━━━━━━━━━━━ 31s 301ms/step - loss: 0.7591

  3/107 ━━━━━━━━━━━━━━━━━━━━ 31s 299ms/step - loss: 0.7567

  4/107 ━━━━━━━━━━━━━━━━━━━━ 30s 296ms/step - loss: 0.7547

  5/107 ━━━━━━━━━━━━━━━━━━━━ 29s 294ms/step - loss: 0.7555

  6/107 ━━━━━━━━━━━━━━━━━━━━ 29s 295ms/step - loss: 0.7554

  7/107 ━━━━━━━━━━━━━━━━━━━━ 29s 296ms/step - loss: 0.7538

  8/107 ━━━━━━━━━━━━━━━━━━━━ 29s 297ms/step - loss: 0.7520

  9/107 ━━━━━━━━━━━━━━━━━━━━ 29s 303ms/step - loss: 0.7500

 10/107 ━━━━━━━━━━━━━━━━━━━━ 29s 304ms/step - loss: 0.7482

 11/107 ━━━━━━━━━━━━━━━━━━━━ 29s 306ms/step - loss: 0.7468

 12/107 ━━━━━━━━━━━━━━━━━━━━ 29s 305ms/step - loss: 0.7453

 13/107 ━━━━━━━━━━━━━━━━━━━━ 28s 305ms/step - loss: 0.7437

 14/107 ━━━━━━━━━━━━━━━━━━━━ 28s 306ms/step - loss: 0.7425

 15/107 ━━━━━━━━━━━━━━━━━━━━ 28s 307ms/step - loss: 0.7411

 16/107 ━━━━━━━━━━━━━━━━━━━━ 27s 306ms/step - loss: 0.7400

 17/107 ━━━━━━━━━━━━━━━━━━━━ 27s 306ms/step - loss: 0.7389

 18/107 ━━━━━━━━━━━━━━━━━━━━ 27s 306ms/step - loss: 0.7376

 19/107 ━━━━━━━━━━━━━━━━━━━━ 26s 305ms/step - loss: 0.7364

 20/107 ━━━━━━━━━━━━━━━━━━━━ 26s 305ms/step - loss: 0.7351

 21/107 ━━━━━━━━━━━━━━━━━━━━ 26s 304ms/step - loss: 0.7340

 22/107 ━━━━━━━━━━━━━━━━━━━━ 25s 304ms/step - loss: 0.7330

 23/107 ━━━━━━━━━━━━━━━━━━━━ 25s 304ms/step - loss: 0.7321

 24/107 ━━━━━━━━━━━━━━━━━━━━ 25s 304ms/step - loss: 0.7313

 25/107 ━━━━━━━━━━━━━━━━━━━━ 24s 304ms/step - loss: 0.7305

 26/107 ━━━━━━━━━━━━━━━━━━━━ 24s 304ms/step - loss: 0.7298

 27/107 ━━━━━━━━━━━━━━━━━━━━ 24s 304ms/step - loss: 0.7289

 28/107 ━━━━━━━━━━━━━━━━━━━━ 24s 304ms/step - loss: 0.7282

 29/107 ━━━━━━━━━━━━━━━━━━━━ 23s 304ms/step - loss: 0.7273

 30/107 ━━━━━━━━━━━━━━━━━━━━ 23s 304ms/step - loss: 0.7265

 31/107 ━━━━━━━━━━━━━━━━━━━━ 23s 304ms/step - loss: 0.7257

 32/107 ━━━━━━━━━━━━━━━━━━━━ 22s 305ms/step - loss: 0.7248

 33/107 ━━━━━━━━━━━━━━━━━━━━ 22s 304ms/step - loss: 0.7240

 34/107 ━━━━━━━━━━━━━━━━━━━━ 22s 304ms/step - loss: 0.7232

 35/107 ━━━━━━━━━━━━━━━━━━━━ 21s 304ms/step - loss: 0.7224

 36/107 ━━━━━━━━━━━━━━━━━━━━ 21s 304ms/step - loss: 0.7216

 37/107 ━━━━━━━━━━━━━━━━━━━━ 21s 304ms/step - loss: 0.7209

 38/107 ━━━━━━━━━━━━━━━━━━━━ 20s 304ms/step - loss: 0.7202

 39/107 ━━━━━━━━━━━━━━━━━━━━ 20s 304ms/step - loss: 0.7195

 40/107 ━━━━━━━━━━━━━━━━━━━━ 20s 304ms/step - loss: 0.7189

 41/107 ━━━━━━━━━━━━━━━━━━━━ 20s 303ms/step - loss: 0.7183

 42/107 ━━━━━━━━━━━━━━━━━━━━ 19s 304ms/step - loss: 0.7177

 43/107 ━━━━━━━━━━━━━━━━━━━━ 19s 304ms/step - loss: 0.7170

 44/107 ━━━━━━━━━━━━━━━━━━━━ 19s 304ms/step - loss: 0.7164

 45/107 ━━━━━━━━━━━━━━━━━━━━ 18s 304ms/step - loss: 0.7158

 46/107 ━━━━━━━━━━━━━━━━━━━━ 18s 304ms/step - loss: 0.7153

 47/107 ━━━━━━━━━━━━━━━━━━━━ 18s 304ms/step - loss: 0.7147

 48/107 ━━━━━━━━━━━━━━━━━━━━ 17s 304ms/step - loss: 0.7142

 49/107 ━━━━━━━━━━━━━━━━━━━━ 17s 303ms/step - loss: 0.7138

 50/107 ━━━━━━━━━━━━━━━━━━━━ 17s 303ms/step - loss: 0.7133

 51/107 ━━━━━━━━━━━━━━━━━━━━ 16s 303ms/step - loss: 0.7129

 52/107 ━━━━━━━━━━━━━━━━━━━━ 16s 303ms/step - loss: 0.7124

 53/107 ━━━━━━━━━━━━━━━━━━━━ 16s 303ms/step - loss: 0.7119

 54/107 ━━━━━━━━━━━━━━━━━━━━ 16s 303ms/step - loss: 0.7114

 55/107 ━━━━━━━━━━━━━━━━━━━━ 15s 303ms/step - loss: 0.7109

 56/107 ━━━━━━━━━━━━━━━━━━━━ 15s 303ms/step - loss: 0.7105

 57/107 ━━━━━━━━━━━━━━━━━━━━ 15s 303ms/step - loss: 0.7100

 58/107 ━━━━━━━━━━━━━━━━━━━━ 14s 302ms/step - loss: 0.7096

 59/107 ━━━━━━━━━━━━━━━━━━━━ 14s 302ms/step - loss: 0.7092

 60/107 ━━━━━━━━━━━━━━━━━━━━ 14s 302ms/step - loss: 0.7088

 61/107 ━━━━━━━━━━━━━━━━━━━━ 13s 302ms/step - loss: 0.7084

 62/107 ━━━━━━━━━━━━━━━━━━━━ 13s 303ms/step - loss: 0.7080

 63/107 ━━━━━━━━━━━━━━━━━━━━ 13s 302ms/step - loss: 0.7076

 64/107 ━━━━━━━━━━━━━━━━━━━━ 13s 303ms/step - loss: 0.7073

 65/107 ━━━━━━━━━━━━━━━━━━━━ 12s 303ms/step - loss: 0.7069

 66/107 ━━━━━━━━━━━━━━━━━━━━ 12s 303ms/step - loss: 0.7065

 67/107 ━━━━━━━━━━━━━━━━━━━━ 12s 303ms/step - loss: 0.7061

 68/107 ━━━━━━━━━━━━━━━━━━━━ 11s 304ms/step - loss: 0.7057

 69/107 ━━━━━━━━━━━━━━━━━━━━ 11s 304ms/step - loss: 0.7053

 70/107 ━━━━━━━━━━━━━━━━━━━━ 11s 304ms/step - loss: 0.7049

 71/107 ━━━━━━━━━━━━━━━━━━━━ 10s 304ms/step - loss: 0.7045

 72/107 ━━━━━━━━━━━━━━━━━━━━ 10s 304ms/step - loss: 0.7041

 73/107 ━━━━━━━━━━━━━━━━━━━━ 10s 304ms/step - loss: 0.7037

 74/107 ━━━━━━━━━━━━━━━━━━━━ 10s 304ms/step - loss: 0.7033

 75/107 ━━━━━━━━━━━━━━━━━━━━ 9s 305ms/step - loss: 0.7030

 76/107 ━━━━━━━━━━━━━━━━━━━━ 9s 305ms/step - loss: 0.7026

 77/107 ━━━━━━━━━━━━━━━━━━━━ 9s 305ms/step - loss: 0.7023

 78/107 ━━━━━━━━━━━━━━━━━━━━ 8s 305ms/step - loss: 0.7019

 79/107 ━━━━━━━━━━━━━━━━━━━━ 8s 304ms/step - loss: 0.7016

 80/107 ━━━━━━━━━━━━━━━━━━━━ 8s 304ms/step - loss: 0.7013

 81/107 ━━━━━━━━━━━━━━━━━━━━ 7s 304ms/step - loss: 0.7010

 82/107 ━━━━━━━━━━━━━━━━━━━━ 7s 304ms/step - loss: 0.7007

 83/107 ━━━━━━━━━━━━━━━━━━━━ 7s 304ms/step - loss: 0.7004

 84/107 ━━━━━━━━━━━━━━━━━━━━ 6s 304ms/step - loss: 0.7001

 85/107 ━━━━━━━━━━━━━━━━━━━━ 6s 304ms/step - loss: 0.6998

 86/107 ━━━━━━━━━━━━━━━━━━━━ 6s 304ms/step - loss: 0.6996

 87/107 ━━━━━━━━━━━━━━━━━━━━ 6s 304ms/step - loss: 0.6993

 88/107 ━━━━━━━━━━━━━━━━━━━━ 5s 304ms/step - loss: 0.6991

 89/107 ━━━━━━━━━━━━━━━━━━━━ 5s 304ms/step - loss: 0.6989

 90/107 ━━━━━━━━━━━━━━━━━━━━ 5s 304ms/step - loss: 0.6986

 91/107 ━━━━━━━━━━━━━━━━━━━━ 4s 304ms/step - loss: 0.6984

 92/107 ━━━━━━━━━━━━━━━━━━━━ 4s 304ms/step - loss: 0.6982

 93/107 ━━━━━━━━━━━━━━━━━━━━ 4s 304ms/step - loss: 0.6980

 94/107 ━━━━━━━━━━━━━━━━━━━━ 3s 304ms/step - loss: 0.6978

 95/107 ━━━━━━━━━━━━━━━━━━━━ 3s 304ms/step - loss: 0.6976

 96/107 ━━━━━━━━━━━━━━━━━━━━ 3s 304ms/step - loss: 0.6974

 97/107 ━━━━━━━━━━━━━━━━━━━━ 3s 304ms/step - loss: 0.6972

 98/107 ━━━━━━━━━━━━━━━━━━━━ 2s 304ms/step - loss: 0.6971

 99/107 ━━━━━━━━━━━━━━━━━━━━ 2s 304ms/step - loss: 0.6969

100/107 ━━━━━━━━━━━━━━━━━━━━ 2s 304ms/step - loss: 0.6967

101/107 ━━━━━━━━━━━━━━━━━━━━ 1s 304ms/step - loss: 0.6965

102/107 ━━━━━━━━━━━━━━━━━━━━ 1s 304ms/step - loss: 0.6964

103/107 ━━━━━━━━━━━━━━━━━━━━ 1s 304ms/step - loss: 0.6962

104/107 ━━━━━━━━━━━━━━━━━━━━ 0s 304ms/step - loss: 0.6960

105/107 ━━━━━━━━━━━━━━━━━━━━ 0s 304ms/step - loss: 0.6959

106/107 ━━━━━━━━━━━━━━━━━━━━ 0s 304ms/step - loss: 0.6957

107/107 ━━━━━━━━━━━━━━━━━━━━ 0s 304ms/step - loss: 0.6955

107/107 ━━━━━━━━━━━━━━━━━━━━ 34s 317ms/step - loss: 0.6787 - val_loss: 0.9779

Epoch 3/10

  1/107 ━━━━━━━━━━━━━━━━━━━━ 36s 347ms/step - loss: 0.4518

  2/107 ━━━━━━━━━━━━━━━━━━━━ 33s 324ms/step - loss: 0.4653

  3/107 ━━━━━━━━━━━━━━━━━━━━ 33s 320ms/step - loss: 0.4631

  4/107 ━━━━━━━━━━━━━━━━━━━━ 33s 325ms/step - loss: 0.4601

  5/107 ━━━━━━━━━━━━━━━━━━━━ 33s 326ms/step - loss: 0.4621

  6/107 ━━━━━━━━━━━━━━━━━━━━ 32s 323ms/step - loss: 0.4634

  7/107 ━━━━━━━━━━━━━━━━━━━━ 32s 320ms/step - loss: 0.4634

  8/107 ━━━━━━━━━━━━━━━━━━━━ 31s 316ms/step - loss: 0.4632

  9/107 ━━━━━━━━━━━━━━━━━━━━ 30s 315ms/step - loss: 0.4644

 10/107 ━━━━━━━━━━━━━━━━━━━━ 30s 314ms/step - loss: 0.4656

 11/107 ━━━━━━━━━━━━━━━━━━━━ 30s 313ms/step - loss: 0.4669

 12/107 ━━━━━━━━━━━━━━━━━━━━ 29s 311ms/step - loss: 0.4680

 13/107 ━━━━━━━━━━━━━━━━━━━━ 29s 311ms/step - loss: 0.4686

 14/107 ━━━━━━━━━━━━━━━━━━━━ 29s 314ms/step - loss: 0.4691

 15/107 ━━━━━━━━━━━━━━━━━━━━ 28s 312ms/step - loss: 0.4696

 16/107 ━━━━━━━━━━━━━━━━━━━━ 28s 310ms/step - loss: 0.4699

 17/107 ━━━━━━━━━━━━━━━━━━━━ 27s 310ms/step - loss: 0.4701

 18/107 ━━━━━━━━━━━━━━━━━━━━ 27s 312ms/step - loss: 0.4701

 19/107 ━━━━━━━━━━━━━━━━━━━━ 27s 311ms/step - loss: 0.4705

 20/107 ━━━━━━━━━━━━━━━━━━━━ 27s 311ms/step - loss: 0.4707

 21/107 ━━━━━━━━━━━━━━━━━━━━ 26s 310ms/step - loss: 0.4709

 22/107 ━━━━━━━━━━━━━━━━━━━━ 26s 311ms/step - loss: 0.4710

 23/107 ━━━━━━━━━━━━━━━━━━━━ 26s 311ms/step - loss: 0.4712

 24/107 ━━━━━━━━━━━━━━━━━━━━ 25s 310ms/step - loss: 0.4712

 25/107 ━━━━━━━━━━━━━━━━━━━━ 25s 309ms/step - loss: 0.4713

 26/107 ━━━━━━━━━━━━━━━━━━━━ 25s 309ms/step - loss: 0.4713

 27/107 ━━━━━━━━━━━━━━━━━━━━ 24s 309ms/step - loss: 0.4713

 28/107 ━━━━━━━━━━━━━━━━━━━━ 24s 309ms/step - loss: 0.4713

 29/107 ━━━━━━━━━━━━━━━━━━━━ 24s 310ms/step - loss: 0.4712

 30/107 ━━━━━━━━━━━━━━━━━━━━ 23s 310ms/step - loss: 0.4710

 31/107 ━━━━━━━━━━━━━━━━━━━━ 23s 310ms/step - loss: 0.4708

 32/107 ━━━━━━━━━━━━━━━━━━━━ 23s 309ms/step - loss: 0.4706

 33/107 ━━━━━━━━━━━━━━━━━━━━ 22s 309ms/step - loss: 0.4704

 34/107 ━━━━━━━━━━━━━━━━━━━━ 22s 309ms/step - loss: 0.4702

 35/107 ━━━━━━━━━━━━━━━━━━━━ 22s 309ms/step - loss: 0.4700

 36/107 ━━━━━━━━━━━━━━━━━━━━ 21s 309ms/step - loss: 0.4698

 37/107 ━━━━━━━━━━━━━━━━━━━━ 21s 309ms/step - loss: 0.4696

 38/107 ━━━━━━━━━━━━━━━━━━━━ 21s 310ms/step - loss: 0.4694

 39/107 ━━━━━━━━━━━━━━━━━━━━ 21s 311ms/step - loss: 0.4692

 40/107 ━━━━━━━━━━━━━━━━━━━━ 20s 311ms/step - loss: 0.4691

 41/107 ━━━━━━━━━━━━━━━━━━━━ 20s 311ms/step - loss: 0.4690

 42/107 ━━━━━━━━━━━━━━━━━━━━ 20s 311ms/step - loss: 0.4689

 43/107 ━━━━━━━━━━━━━━━━━━━━ 19s 311ms/step - loss: 0.4687

 44/107 ━━━━━━━━━━━━━━━━━━━━ 19s 311ms/step - loss: 0.4686

 45/107 ━━━━━━━━━━━━━━━━━━━━ 19s 311ms/step - loss: 0.4685

 46/107 ━━━━━━━━━━━━━━━━━━━━ 18s 311ms/step - loss: 0.4684

 47/107 ━━━━━━━━━━━━━━━━━━━━ 18s 311ms/step - loss: 0.4683

 48/107 ━━━━━━━━━━━━━━━━━━━━ 18s 311ms/step - loss: 0.4681

 49/107 ━━━━━━━━━━━━━━━━━━━━ 18s 311ms/step - loss: 0.4680

 50/107 ━━━━━━━━━━━━━━━━━━━━ 17s 311ms/step - loss: 0.4679

 51/107 ━━━━━━━━━━━━━━━━━━━━ 17s 312ms/step - loss: 0.4677

 52/107 ━━━━━━━━━━━━━━━━━━━━ 17s 312ms/step - loss: 0.4675

 53/107 ━━━━━━━━━━━━━━━━━━━━ 16s 312ms/step - loss: 0.4673

 54/107 ━━━━━━━━━━━━━━━━━━━━ 16s 311ms/step - loss: 0.4671

 55/107 ━━━━━━━━━━━━━━━━━━━━ 16s 311ms/step - loss: 0.4670

 56/107 ━━━━━━━━━━━━━━━━━━━━ 15s 311ms/step - loss: 0.4668

 57/107 ━━━━━━━━━━━━━━━━━━━━ 15s 312ms/step - loss: 0.4666

 58/107 ━━━━━━━━━━━━━━━━━━━━ 15s 312ms/step - loss: 0.4665

 59/107 ━━━━━━━━━━━━━━━━━━━━ 15s 313ms/step - loss: 0.4663

 60/107 ━━━━━━━━━━━━━━━━━━━━ 14s 314ms/step - loss: 0.4662

 61/107 ━━━━━━━━━━━━━━━━━━━━ 14s 314ms/step - loss: 0.4661

 62/107 ━━━━━━━━━━━━━━━━━━━━ 14s 314ms/step - loss: 0.4661

 63/107 ━━━━━━━━━━━━━━━━━━━━ 13s 314ms/step - loss: 0.4660

 64/107 ━━━━━━━━━━━━━━━━━━━━ 13s 314ms/step - loss: 0.4660

 65/107 ━━━━━━━━━━━━━━━━━━━━ 13s 314ms/step - loss: 0.4659

 66/107 ━━━━━━━━━━━━━━━━━━━━ 12s 314ms/step - loss: 0.4658

 67/107 ━━━━━━━━━━━━━━━━━━━━ 12s 314ms/step - loss: 0.4658

 68/107 ━━━━━━━━━━━━━━━━━━━━ 12s 314ms/step - loss: 0.4657

 69/107 ━━━━━━━━━━━━━━━━━━━━ 11s 314ms/step - loss: 0.4657

 70/107 ━━━━━━━━━━━━━━━━━━━━ 11s 314ms/step - loss: 0.4657

 71/107 ━━━━━━━━━━━━━━━━━━━━ 11s 314ms/step - loss: 0.4656

 72/107 ━━━━━━━━━━━━━━━━━━━━ 11s 314ms/step - loss: 0.4656

 73/107 ━━━━━━━━━━━━━━━━━━━━ 10s 314ms/step - loss: 0.4656

 74/107 ━━━━━━━━━━━━━━━━━━━━ 10s 314ms/step - loss: 0.4655

 75/107 ━━━━━━━━━━━━━━━━━━━━ 10s 314ms/step - loss: 0.4655

 76/107 ━━━━━━━━━━━━━━━━━━━━ 9s 314ms/step - loss: 0.4655

 77/107 ━━━━━━━━━━━━━━━━━━━━ 9s 314ms/step - loss: 0.4655

 78/107 ━━━━━━━━━━━━━━━━━━━━ 9s 314ms/step - loss: 0.4655

 79/107 ━━━━━━━━━━━━━━━━━━━━ 8s 314ms/step - loss: 0.4655

 80/107 ━━━━━━━━━━━━━━━━━━━━ 8s 314ms/step - loss: 0.4655

 81/107 ━━━━━━━━━━━━━━━━━━━━ 8s 314ms/step - loss: 0.4655

 82/107 ━━━━━━━━━━━━━━━━━━━━ 7s 314ms/step - loss: 0.4656

 83/107 ━━━━━━━━━━━━━━━━━━━━ 7s 315ms/step - loss: 0.4656

 84/107 ━━━━━━━━━━━━━━━━━━━━ 7s 315ms/step - loss: 0.4656

 85/107 ━━━━━━━━━━━━━━━━━━━━ 6s 316ms/step - loss: 0.4656

 86/107 ━━━━━━━━━━━━━━━━━━━━ 6s 315ms/step - loss: 0.4656

 87/107 ━━━━━━━━━━━━━━━━━━━━ 6s 316ms/step - loss: 0.4657

 88/107 ━━━━━━━━━━━━━━━━━━━━ 5s 316ms/step - loss: 0.4657

 89/107 ━━━━━━━━━━━━━━━━━━━━ 5s 316ms/step - loss: 0.4657

 90/107 ━━━━━━━━━━━━━━━━━━━━ 5s 316ms/step - loss: 0.4658

 91/107 ━━━━━━━━━━━━━━━━━━━━ 5s 316ms/step - loss: 0.4658

 92/107 ━━━━━━━━━━━━━━━━━━━━ 4s 316ms/step - loss: 0.4659

 93/107 ━━━━━━━━━━━━━━━━━━━━ 4s 317ms/step - loss: 0.4659

 94/107 ━━━━━━━━━━━━━━━━━━━━ 4s 317ms/step - loss: 0.4659

 95/107 ━━━━━━━━━━━━━━━━━━━━ 3s 317ms/step - loss: 0.4660

 96/107 ━━━━━━━━━━━━━━━━━━━━ 3s 317ms/step - loss: 0.4660

 97/107 ━━━━━━━━━━━━━━━━━━━━ 3s 317ms/step - loss: 0.4661

 98/107 ━━━━━━━━━━━━━━━━━━━━ 2s 317ms/step - loss: 0.4661

 99/107 ━━━━━━━━━━━━━━━━━━━━ 2s 317ms/step - loss: 0.4662

100/107 ━━━━━━━━━━━━━━━━━━━━ 2s 317ms/step - loss: 0.4662

101/107 ━━━━━━━━━━━━━━━━━━━━ 1s 317ms/step - loss: 0.4663

102/107 ━━━━━━━━━━━━━━━━━━━━ 1s 317ms/step - loss: 0.4664

103/107 ━━━━━━━━━━━━━━━━━━━━ 1s 317ms/step - loss: 0.4664

104/107 ━━━━━━━━━━━━━━━━━━━━ 0s 317ms/step - loss: 0.4665

105/107 ━━━━━━━━━━━━━━━━━━━━ 0s 317ms/step - loss: 0.4665

106/107 ━━━━━━━━━━━━━━━━━━━━ 0s 316ms/step - loss: 0.4666

107/107 ━━━━━━━━━━━━━━━━━━━━ 0s 316ms/step - loss: 0.4667

107/107 ━━━━━━━━━━━━━━━━━━━━ 35s 329ms/step - loss: 0.4734 - val_loss: 1.1003

Epoch 4/10

  1/107 ━━━━━━━━━━━━━━━━━━━━ 34s 327ms/step - loss: 0.3634

  2/107 ━━━━━━━━━━━━━━━━━━━━ 31s 301ms/step - loss: 0.3491

  3/107 ━━━━━━━━━━━━━━━━━━━━ 31s 300ms/step - loss: 0.3409

  4/107 ━━━━━━━━━━━━━━━━━━━━ 30s 301ms/step - loss: 0.3388

  5/107 ━━━━━━━━━━━━━━━━━━━━ 30s 302ms/step - loss: 0.3370

  6/107 ━━━━━━━━━━━━━━━━━━━━ 30s 300ms/step - loss: 0.3363

  7/107 ━━━━━━━━━━━━━━━━━━━━ 30s 302ms/step - loss: 0.3358

  8/107 ━━━━━━━━━━━━━━━━━━━━ 29s 301ms/step - loss: 0.3358

  9/107 ━━━━━━━━━━━━━━━━━━━━ 29s 301ms/step - loss: 0.3353

 10/107 ━━━━━━━━━━━━━━━━━━━━ 29s 302ms/step - loss: 0.3345

 11/107 ━━━━━━━━━━━━━━━━━━━━ 29s 302ms/step - loss: 0.3339

 12/107 ━━━━━━━━━━━━━━━━━━━━ 29s 306ms/step - loss: 0.3333

 13/107 ━━━━━━━━━━━━━━━━━━━━ 28s 308ms/step - loss: 0.3328

 14/107 ━━━━━━━━━━━━━━━━━━━━ 28s 307ms/step - loss: 0.3325

 15/107 ━━━━━━━━━━━━━━━━━━━━ 28s 308ms/step - loss: 0.3322

 16/107 ━━━━━━━━━━━━━━━━━━━━ 27s 307ms/step - loss: 0.3323

 17/107 ━━━━━━━━━━━━━━━━━━━━ 27s 307ms/step - loss: 0.3324

 18/107 ━━━━━━━━━━━━━━━━━━━━ 27s 307ms/step - loss: 0.3325

 19/107 ━━━━━━━━━━━━━━━━━━━━ 26s 306ms/step - loss: 0.3324

 20/107 ━━━━━━━━━━━━━━━━━━━━ 26s 306ms/step - loss: 0.3324

 21/107 ━━━━━━━━━━━━━━━━━━━━ 26s 306ms/step - loss: 0.3323

 22/107 ━━━━━━━━━━━━━━━━━━━━ 26s 307ms/step - loss: 0.3323

 23/107 ━━━━━━━━━━━━━━━━━━━━ 25s 307ms/step - loss: 0.3324

 24/107 ━━━━━━━━━━━━━━━━━━━━ 25s 307ms/step - loss: 0.3324

 25/107 ━━━━━━━━━━━━━━━━━━━━ 25s 307ms/step - loss: 0.3324

 26/107 ━━━━━━━━━━━━━━━━━━━━ 24s 307ms/step - loss: 0.3325

 27/107 ━━━━━━━━━━━━━━━━━━━━ 24s 308ms/step - loss: 0.3325

 28/107 ━━━━━━━━━━━━━━━━━━━━ 24s 307ms/step - loss: 0.3324

 29/107 ━━━━━━━━━━━━━━━━━━━━ 23s 307ms/step - loss: 0.3324

 30/107 ━━━━━━━━━━━━━━━━━━━━ 23s 307ms/step - loss: 0.3323

 31/107 ━━━━━━━━━━━━━━━━━━━━ 23s 307ms/step - loss: 0.3322

 32/107 ━━━━━━━━━━━━━━━━━━━━ 23s 307ms/step - loss: 0.3320

 33/107 ━━━━━━━━━━━━━━━━━━━━ 22s 307ms/step - loss: 0.3319

 34/107 ━━━━━━━━━━━━━━━━━━━━ 22s 307ms/step - loss: 0.3318

 35/107 ━━━━━━━━━━━━━━━━━━━━ 22s 307ms/step - loss: 0.3317

 36/107 ━━━━━━━━━━━━━━━━━━━━ 21s 306ms/step - loss: 0.3316

 37/107 ━━━━━━━━━━━━━━━━━━━━ 21s 306ms/step - loss: 0.3315

 38/107 ━━━━━━━━━━━━━━━━━━━━ 21s 306ms/step - loss: 0.3314

 39/107 ━━━━━━━━━━━━━━━━━━━━ 20s 305ms/step - loss: 0.3312

 40/107 ━━━━━━━━━━━━━━━━━━━━ 20s 305ms/step - loss: 0.3312

 41/107 ━━━━━━━━━━━━━━━━━━━━ 20s 305ms/step - loss: 0.3312

 42/107 ━━━━━━━━━━━━━━━━━━━━ 19s 305ms/step - loss: 0.3311

 43/107 ━━━━━━━━━━━━━━━━━━━━ 19s 305ms/step - loss: 0.3312

 44/107 ━━━━━━━━━━━━━━━━━━━━ 19s 305ms/step - loss: 0.3312

 45/107 ━━━━━━━━━━━━━━━━━━━━ 18s 306ms/step - loss: 0.3311

 46/107 ━━━━━━━━━━━━━━━━━━━━ 18s 306ms/step - loss: 0.3311

 47/107 ━━━━━━━━━━━━━━━━━━━━ 18s 305ms/step - loss: 0.3311

 48/107 ━━━━━━━━━━━━━━━━━━━━ 18s 305ms/step - loss: 0.3311

 49/107 ━━━━━━━━━━━━━━━━━━━━ 17s 306ms/step - loss: 0.3311

 50/107 ━━━━━━━━━━━━━━━━━━━━ 17s 305ms/step - loss: 0.3311

 51/107 ━━━━━━━━━━━━━━━━━━━━ 17s 305ms/step - loss: 0.3311

 52/107 ━━━━━━━━━━━━━━━━━━━━ 16s 305ms/step - loss: 0.3311

 53/107 ━━━━━━━━━━━━━━━━━━━━ 16s 305ms/step - loss: 0.3311

 54/107 ━━━━━━━━━━━━━━━━━━━━ 16s 305ms/step - loss: 0.3312

 55/107 ━━━━━━━━━━━━━━━━━━━━ 15s 305ms/step - loss: 0.3312

 56/107 ━━━━━━━━━━━━━━━━━━━━ 15s 305ms/step - loss: 0.3313

 57/107 ━━━━━━━━━━━━━━━━━━━━ 15s 305ms/step - loss: 0.3313

 58/107 ━━━━━━━━━━━━━━━━━━━━ 14s 305ms/step - loss: 0.3313

 59/107 ━━━━━━━━━━━━━━━━━━━━ 14s 305ms/step - loss: 0.3314

 60/107 ━━━━━━━━━━━━━━━━━━━━ 14s 305ms/step - loss: 0.3315

 61/107 ━━━━━━━━━━━━━━━━━━━━ 14s 305ms/step - loss: 0.3315

 62/107 ━━━━━━━━━━━━━━━━━━━━ 13s 306ms/step - loss: 0.3316

 63/107 ━━━━━━━━━━━━━━━━━━━━ 13s 305ms/step - loss: 0.3317

 64/107 ━━━━━━━━━━━━━━━━━━━━ 13s 305ms/step - loss: 0.3318

 65/107 ━━━━━━━━━━━━━━━━━━━━ 12s 305ms/step - loss: 0.3319

 66/107 ━━━━━━━━━━━━━━━━━━━━ 12s 305ms/step - loss: 0.3320

 67/107 ━━━━━━━━━━━━━━━━━━━━ 12s 305ms/step - loss: 0.3321

 68/107 ━━━━━━━━━━━━━━━━━━━━ 11s 305ms/step - loss: 0.3322

 69/107 ━━━━━━━━━━━━━━━━━━━━ 11s 305ms/step - loss: 0.3323

 70/107 ━━━━━━━━━━━━━━━━━━━━ 11s 305ms/step - loss: 0.3325

 71/107 ━━━━━━━━━━━━━━━━━━━━ 10s 305ms/step - loss: 0.3326

 72/107 ━━━━━━━━━━━━━━━━━━━━ 10s 305ms/step - loss: 0.3326

 73/107 ━━━━━━━━━━━━━━━━━━━━ 10s 305ms/step - loss: 0.3327

 74/107 ━━━━━━━━━━━━━━━━━━━━ 10s 305ms/step - loss: 0.3328

 75/107 ━━━━━━━━━━━━━━━━━━━━ 9s 305ms/step - loss: 0.3330

 76/107 ━━━━━━━━━━━━━━━━━━━━ 9s 305ms/step - loss: 0.3331

 77/107 ━━━━━━━━━━━━━━━━━━━━ 9s 305ms/step - loss: 0.3332

 78/107 ━━━━━━━━━━━━━━━━━━━━ 8s 305ms/step - loss: 0.3333

 79/107 ━━━━━━━━━━━━━━━━━━━━ 8s 306ms/step - loss: 0.3334

 80/107 ━━━━━━━━━━━━━━━━━━━━ 8s 306ms/step - loss: 0.3335

 81/107 ━━━━━━━━━━━━━━━━━━━━ 7s 305ms/step - loss: 0.3336

 82/107 ━━━━━━━━━━━━━━━━━━━━ 7s 306ms/step - loss: 0.3338

 83/107 ━━━━━━━━━━━━━━━━━━━━ 7s 305ms/step - loss: 0.3339

 84/107 ━━━━━━━━━━━━━━━━━━━━ 7s 305ms/step - loss: 0.3340

 85/107 ━━━━━━━━━━━━━━━━━━━━ 6s 306ms/step - loss: 0.3342

 86/107 ━━━━━━━━━━━━━━━━━━━━ 6s 306ms/step - loss: 0.3343

 87/107 ━━━━━━━━━━━━━━━━━━━━ 6s 306ms/step - loss: 0.3345

 88/107 ━━━━━━━━━━━━━━━━━━━━ 5s 306ms/step - loss: 0.3346

 89/107 ━━━━━━━━━━━━━━━━━━━━ 5s 306ms/step - loss: 0.3347

 90/107 ━━━━━━━━━━━━━━━━━━━━ 5s 305ms/step - loss: 0.3349

 91/107 ━━━━━━━━━━━━━━━━━━━━ 4s 305ms/step - loss: 0.3350

 92/107 ━━━━━━━━━━━━━━━━━━━━ 4s 305ms/step - loss: 0.3351

 93/107 ━━━━━━━━━━━━━━━━━━━━ 4s 305ms/step - loss: 0.3353

 94/107 ━━━━━━━━━━━━━━━━━━━━ 3s 305ms/step - loss: 0.3354

 95/107 ━━━━━━━━━━━━━━━━━━━━ 3s 305ms/step - loss: 0.3355

 96/107 ━━━━━━━━━━━━━━━━━━━━ 3s 305ms/step - loss: 0.3356

 97/107 ━━━━━━━━━━━━━━━━━━━━ 3s 305ms/step - loss: 0.3357

 98/107 ━━━━━━━━━━━━━━━━━━━━ 2s 305ms/step - loss: 0.3358

 99/107 ━━━━━━━━━━━━━━━━━━━━ 2s 305ms/step - loss: 0.3359

100/107 ━━━━━━━━━━━━━━━━━━━━ 2s 305ms/step - loss: 0.3360

101/107 ━━━━━━━━━━━━━━━━━━━━ 1s 305ms/step - loss: 0.3362

102/107 ━━━━━━━━━━━━━━━━━━━━ 1s 305ms/step - loss: 0.3363

103/107 ━━━━━━━━━━━━━━━━━━━━ 1s 305ms/step - loss: 0.3364

104/107 ━━━━━━━━━━━━━━━━━━━━ 0s 304ms/step - loss: 0.3365

105/107 ━━━━━━━━━━━━━━━━━━━━ 0s 304ms/step - loss: 0.3366

106/107 ━━━━━━━━━━━━━━━━━━━━ 0s 304ms/step - loss: 0.3367

107/107 ━━━━━━━━━━━━━━━━━━━━ 0s 304ms/step - loss: 0.3368

107/107 ━━━━━━━━━━━━━━━━━━━━ 34s 317ms/step - loss: 0.3481 - val_loss: 1.3854

  saved /kaggle/working/models/bert_no_emoji.keras
  threshold 0.55 | dev Micro-F1 47.29%

--- Transformer | With Emoji ---
  Phase 1: hyper-parameter search
    cfg1: lr=0.001 embed=128 batch=64

      -> Micro-F1 47.85%
    cfg2: lr=0.0005 embed=256 batch=32

      -> Micro-F1 47.59%
    cfg3: lr=0.002 embed=128 batch=64

      -> Micro-F1 50.25%

  config  micro_f1  macro_f1  label_accuracy  threshold model       track
0   cfg1     47.85     44.42           70.32       0.55  BERT  With Emoji
1   cfg2     47.59     43.73           70.51       0.55  BERT  With Emoji
2   cfg3     50.25     46.70           72.88       0.55  BERT  With Emoji

  best config: cfg3
  Phase 2: final training

Epoch 1/10

  1/107 ━━━━━━━━━━━━━━━━━━━━ 7:33 4s/step - loss: 1.1920

  2/107 ━━━━━━━━━━━━━━━━━━━━ 30s 287ms/step - loss: 1.2103

  3/107 ━━━━━━━━━━━━━━━━━━━━ 29s 287ms/step - loss: 1.2106

  4/107 ━━━━━━━━━━━━━━━━━━━━ 30s 291ms/step - loss: 1.2098

  5/107 ━━━━━━━━━━━━━━━━━━━━ 29s 286ms/step - loss: 1.2044

  6/107 ━━━━━━━━━━━━━━━━━━━━ 28s 287ms/step - loss: 1.2016

  7/107 ━━━━━━━━━━━━━━━━━━━━ 28s 284ms/step - loss: 1.2021

  8/107 ━━━━━━━━━━━━━━━━━━━━ 27s 281ms/step - loss: 1.2027

  9/107 ━━━━━━━━━━━━━━━━━━━━ 28s 289ms/step - loss: 1.2020

 10/107 ━━━━━━━━━━━━━━━━━━━━ 27s 287ms/step - loss: 1.2015

 11/107 ━━━━━━━━━━━━━━━━━━━━ 27s 287ms/step - loss: 1.2007

 12/107 ━━━━━━━━━━━━━━━━━━━━ 27s 285ms/step - loss: 1.1996

 13/107 ━━━━━━━━━━━━━━━━━━━━ 26s 286ms/step - loss: 1.1978

 14/107 ━━━━━━━━━━━━━━━━━━━━ 26s 286ms/step - loss: 1.1955

 15/107 ━━━━━━━━━━━━━━━━━━━━ 26s 284ms/step - loss: 1.1937

 16/107 ━━━━━━━━━━━━━━━━━━━━ 25s 284ms/step - loss: 1.1920

 17/107 ━━━━━━━━━━━━━━━━━━━━ 25s 282ms/step - loss: 1.1899

 18/107 ━━━━━━━━━━━━━━━━━━━━ 25s 281ms/step - loss: 1.1877

 19/107 ━━━━━━━━━━━━━━━━━━━━ 24s 281ms/step - loss: 1.1854

 20/107 ━━━━━━━━━━━━━━━━━━━━ 24s 281ms/step - loss: 1.1830

 21/107 ━━━━━━━━━━━━━━━━━━━━ 24s 282ms/step - loss: 1.1806

 22/107 ━━━━━━━━━━━━━━━━━━━━ 24s 283ms/step - loss: 1.1781

 23/107 ━━━━━━━━━━━━━━━━━━━━ 23s 283ms/step - loss: 1.1756

 24/107 ━━━━━━━━━━━━━━━━━━━━ 23s 283ms/step - loss: 1.1732

 25/107 ━━━━━━━━━━━━━━━━━━━━ 23s 282ms/step - loss: 1.1709

 26/107 ━━━━━━━━━━━━━━━━━━━━ 22s 283ms/step - loss: 1.1687

 27/107 ━━━━━━━━━━━━━━━━━━━━ 22s 282ms/step - loss: 1.1665

 28/107 ━━━━━━━━━━━━━━━━━━━━ 22s 282ms/step - loss: 1.1643

 29/107 ━━━━━━━━━━━━━━━━━━━━ 21s 281ms/step - loss: 1.1620

 30/107 ━━━━━━━━━━━━━━━━━━━━ 21s 281ms/step - loss: 1.1599

 31/107 ━━━━━━━━━━━━━━━━━━━━ 21s 282ms/step - loss: 1.1578

 32/107 ━━━━━━━━━━━━━━━━━━━━ 21s 281ms/step - loss: 1.1557

 33/107 ━━━━━━━━━━━━━━━━━━━━ 20s 281ms/step - loss: 1.1536

 34/107 ━━━━━━━━━━━━━━━━━━━━ 20s 281ms/step - loss: 1.1515

 35/107 ━━━━━━━━━━━━━━━━━━━━ 20s 281ms/step - loss: 1.1495

 36/107 ━━━━━━━━━━━━━━━━━━━━ 19s 280ms/step - loss: 1.1475

 37/107 ━━━━━━━━━━━━━━━━━━━━ 19s 280ms/step - loss: 1.1456

 38/107 ━━━━━━━━━━━━━━━━━━━━ 19s 280ms/step - loss: 1.1436

 39/107 ━━━━━━━━━━━━━━━━━━━━ 19s 280ms/step - loss: 1.1417

 40/107 ━━━━━━━━━━━━━━━━━━━━ 18s 280ms/step - loss: 1.1397

 41/107 ━━━━━━━━━━━━━━━━━━━━ 18s 280ms/step - loss: 1.1378

 42/107 ━━━━━━━━━━━━━━━━━━━━ 18s 280ms/step - loss: 1.1359

 43/107 ━━━━━━━━━━━━━━━━━━━━ 17s 280ms/step - loss: 1.1341

 44/107 ━━━━━━━━━━━━━━━━━━━━ 17s 280ms/step - loss: 1.1323

 45/107 ━━━━━━━━━━━━━━━━━━━━ 17s 281ms/step - loss: 1.1305

 46/107 ━━━━━━━━━━━━━━━━━━━━ 17s 281ms/step - loss: 1.1287

 47/107 ━━━━━━━━━━━━━━━━━━━━ 16s 281ms/step - loss: 1.1270

 48/107 ━━━━━━━━━━━━━━━━━━━━ 16s 281ms/step - loss: 1.1253

 49/107 ━━━━━━━━━━━━━━━━━━━━ 16s 281ms/step - loss: 1.1236

 50/107 ━━━━━━━━━━━━━━━━━━━━ 16s 281ms/step - loss: 1.1220

 51/107 ━━━━━━━━━━━━━━━━━━━━ 15s 281ms/step - loss: 1.1204

 52/107 ━━━━━━━━━━━━━━━━━━━━ 15s 281ms/step - loss: 1.1189

 53/107 ━━━━━━━━━━━━━━━━━━━━ 15s 282ms/step - loss: 1.1174

 54/107 ━━━━━━━━━━━━━━━━━━━━ 14s 282ms/step - loss: 1.1160

 55/107 ━━━━━━━━━━━━━━━━━━━━ 14s 282ms/step - loss: 1.1146

 56/107 ━━━━━━━━━━━━━━━━━━━━ 14s 282ms/step - loss: 1.1132

 57/107 ━━━━━━━━━━━━━━━━━━━━ 14s 282ms/step - loss: 1.1119

 58/107 ━━━━━━━━━━━━━━━━━━━━ 13s 282ms/step - loss: 1.1106

 59/107 ━━━━━━━━━━━━━━━━━━━━ 13s 282ms/step - loss: 1.1093

 60/107 ━━━━━━━━━━━━━━━━━━━━ 13s 282ms/step - loss: 1.1080

 61/107 ━━━━━━━━━━━━━━━━━━━━ 12s 281ms/step - loss: 1.1067

 62/107 ━━━━━━━━━━━━━━━━━━━━ 12s 281ms/step - loss: 1.1055

 63/107 ━━━━━━━━━━━━━━━━━━━━ 12s 281ms/step - loss: 1.1043

 64/107 ━━━━━━━━━━━━━━━━━━━━ 12s 281ms/step - loss: 1.1030

 65/107 ━━━━━━━━━━━━━━━━━━━━ 11s 281ms/step - loss: 1.1018

 66/107 ━━━━━━━━━━━━━━━━━━━━ 11s 281ms/step - loss: 1.1006

 67/107 ━━━━━━━━━━━━━━━━━━━━ 11s 281ms/step - loss: 1.0993

 68/107 ━━━━━━━━━━━━━━━━━━━━ 10s 281ms/step - loss: 1.0982

 69/107 ━━━━━━━━━━━━━━━━━━━━ 10s 281ms/step - loss: 1.0971

 70/107 ━━━━━━━━━━━━━━━━━━━━ 10s 281ms/step - loss: 1.0959

 71/107 ━━━━━━━━━━━━━━━━━━━━ 10s 281ms/step - loss: 1.0948

 72/107 ━━━━━━━━━━━━━━━━━━━━ 9s 281ms/step - loss: 1.0937

 73/107 ━━━━━━━━━━━━━━━━━━━━ 9s 281ms/step - loss: 1.0926

 74/107 ━━━━━━━━━━━━━━━━━━━━ 9s 281ms/step - loss: 1.0915

 75/107 ━━━━━━━━━━━━━━━━━━━━ 8s 281ms/step - loss: 1.0905

 76/107 ━━━━━━━━━━━━━━━━━━━━ 8s 281ms/step - loss: 1.0895

 77/107 ━━━━━━━━━━━━━━━━━━━━ 8s 280ms/step - loss: 1.0885

 78/107 ━━━━━━━━━━━━━━━━━━━━ 8s 280ms/step - loss: 1.0876

 79/107 ━━━━━━━━━━━━━━━━━━━━ 7s 280ms/step - loss: 1.0866

 80/107 ━━━━━━━━━━━━━━━━━━━━ 7s 280ms/step - loss: 1.0857

 81/107 ━━━━━━━━━━━━━━━━━━━━ 7s 280ms/step - loss: 1.0847

 82/107 ━━━━━━━━━━━━━━━━━━━━ 7s 280ms/step - loss: 1.0838

 83/107 ━━━━━━━━━━━━━━━━━━━━ 6s 281ms/step - loss: 1.0829

 84/107 ━━━━━━━━━━━━━━━━━━━━ 6s 280ms/step - loss: 1.0820

 85/107 ━━━━━━━━━━━━━━━━━━━━ 6s 280ms/step - loss: 1.0811

 86/107 ━━━━━━━━━━━━━━━━━━━━ 5s 281ms/step - loss: 1.0802

 87/107 ━━━━━━━━━━━━━━━━━━━━ 5s 280ms/step - loss: 1.0794

 88/107 ━━━━━━━━━━━━━━━━━━━━ 5s 280ms/step - loss: 1.0785

 89/107 ━━━━━━━━━━━━━━━━━━━━ 5s 280ms/step - loss: 1.0777

 90/107 ━━━━━━━━━━━━━━━━━━━━ 4s 280ms/step - loss: 1.0768

 91/107 ━━━━━━━━━━━━━━━━━━━━ 4s 280ms/step - loss: 1.0760

 92/107 ━━━━━━━━━━━━━━━━━━━━ 4s 280ms/step - loss: 1.0751

 93/107 ━━━━━━━━━━━━━━━━━━━━ 3s 280ms/step - loss: 1.0743

 94/107 ━━━━━━━━━━━━━━━━━━━━ 3s 280ms/step - loss: 1.0735

 95/107 ━━━━━━━━━━━━━━━━━━━━ 3s 280ms/step - loss: 1.0726

 96/107 ━━━━━━━━━━━━━━━━━━━━ 3s 280ms/step - loss: 1.0718

 97/107 ━━━━━━━━━━━━━━━━━━━━ 2s 280ms/step - loss: 1.0710

 98/107 ━━━━━━━━━━━━━━━━━━━━ 2s 280ms/step - loss: 1.0702

 99/107 ━━━━━━━━━━━━━━━━━━━━ 2s 280ms/step - loss: 1.0694

100/107 ━━━━━━━━━━━━━━━━━━━━ 1s 279ms/step - loss: 1.0686

101/107 ━━━━━━━━━━━━━━━━━━━━ 1s 279ms/step - loss: 1.0677

102/107 ━━━━━━━━━━━━━━━━━━━━ 1s 279ms/step - loss: 1.0669

103/107 ━━━━━━━━━━━━━━━━━━━━ 1s 279ms/step - loss: 1.0661

104/107 ━━━━━━━━━━━━━━━━━━━━ 0s 279ms/step - loss: 1.0653

105/107 ━━━━━━━━━━━━━━━━━━━━ 0s 279ms/step - loss: 1.0646

106/107 ━━━━━━━━━━━━━━━━━━━━ 0s 279ms/step - loss: 1.0638

107/107 ━━━━━━━━━━━━━━━━━━━━ 0s 278ms/step - loss: 1.0630

107/107 ━━━━━━━━━━━━━━━━━━━━ 35s 294ms/step - loss: 0.9826 - val_loss: 0.9160

Epoch 2/10

  1/107 ━━━━━━━━━━━━━━━━━━━━ 35s 334ms/step - loss: 0.6761

  2/107 ━━━━━━━━━━━━━━━━━━━━ 29s 283ms/step - loss: 0.6732

  3/107 ━━━━━━━━━━━━━━━━━━━━ 29s 281ms/step - loss: 0.6736

  4/107 ━━━━━━━━━━━━━━━━━━━━ 30s 297ms/step - loss: 0.6728

  5/107 ━━━━━━━━━━━━━━━━━━━━ 29s 292ms/step - loss: 0.6725

  6/107 ━━━━━━━━━━━━━━━━━━━━ 29s 288ms/step - loss: 0.6707

  7/107 ━━━━━━━━━━━━━━━━━━━━ 28s 286ms/step - loss: 0.6682

  8/107 ━━━━━━━━━━━━━━━━━━━━ 28s 286ms/step - loss: 0.6657

  9/107 ━━━━━━━━━━━━━━━━━━━━ 27s 283ms/step - loss: 0.6632

 10/107 ━━━━━━━━━━━━━━━━━━━━ 27s 282ms/step - loss: 0.6608

 11/107 ━━━━━━━━━━━━━━━━━━━━ 26s 281ms/step - loss: 0.6590

 12/107 ━━━━━━━━━━━━━━━━━━━━ 26s 281ms/step - loss: 0.6572

 13/107 ━━━━━━━━━━━━━━━━━━━━ 26s 282ms/step - loss: 0.6552

 14/107 ━━━━━━━━━━━━━━━━━━━━ 26s 281ms/step - loss: 0.6534

 15/107 ━━━━━━━━━━━━━━━━━━━━ 25s 280ms/step - loss: 0.6515

 16/107 ━━━━━━━━━━━━━━━━━━━━ 25s 280ms/step - loss: 0.6496

 17/107 ━━━━━━━━━━━━━━━━━━━━ 25s 279ms/step - loss: 0.6478

 18/107 ━━━━━━━━━━━━━━━━━━━━ 24s 278ms/step - loss: 0.6459

 19/107 ━━━━━━━━━━━━━━━━━━━━ 24s 279ms/step - loss: 0.6442

 20/107 ━━━━━━━━━━━━━━━━━━━━ 24s 279ms/step - loss: 0.6425

 21/107 ━━━━━━━━━━━━━━━━━━━━ 24s 280ms/step - loss: 0.6409

 22/107 ━━━━━━━━━━━━━━━━━━━━ 23s 280ms/step - loss: 0.6395

 23/107 ━━━━━━━━━━━━━━━━━━━━ 23s 279ms/step - loss: 0.6383

 24/107 ━━━━━━━━━━━━━━━━━━━━ 23s 279ms/step - loss: 0.6371

 25/107 ━━━━━━━━━━━━━━━━━━━━ 22s 279ms/step - loss: 0.6360

 26/107 ━━━━━━━━━━━━━━━━━━━━ 22s 278ms/step - loss: 0.6351

 27/107 ━━━━━━━━━━━━━━━━━━━━ 22s 279ms/step - loss: 0.6341

 28/107 ━━━━━━━━━━━━━━━━━━━━ 22s 279ms/step - loss: 0.6332

 29/107 ━━━━━━━━━━━━━━━━━━━━ 21s 279ms/step - loss: 0.6322

 30/107 ━━━━━━━━━━━━━━━━━━━━ 21s 280ms/step - loss: 0.6312

 31/107 ━━━━━━━━━━━━━━━━━━━━ 21s 280ms/step - loss: 0.6303

 32/107 ━━━━━━━━━━━━━━━━━━━━ 20s 279ms/step - loss: 0.6293

 33/107 ━━━━━━━━━━━━━━━━━━━━ 20s 279ms/step - loss: 0.6285

 34/107 ━━━━━━━━━━━━━━━━━━━━ 20s 279ms/step - loss: 0.6276

 35/107 ━━━━━━━━━━━━━━━━━━━━ 20s 279ms/step - loss: 0.6267

 36/107 ━━━━━━━━━━━━━━━━━━━━ 19s 279ms/step - loss: 0.6259

 37/107 ━━━━━━━━━━━━━━━━━━━━ 19s 278ms/step - loss: 0.6251

 38/107 ━━━━━━━━━━━━━━━━━━━━ 19s 278ms/step - loss: 0.6243

 39/107 ━━━━━━━━━━━━━━━━━━━━ 18s 278ms/step - loss: 0.6236

 40/107 ━━━━━━━━━━━━━━━━━━━━ 18s 279ms/step - loss: 0.6229

 41/107 ━━━━━━━━━━━━━━━━━━━━ 18s 279ms/step - loss: 0.6223

 42/107 ━━━━━━━━━━━━━━━━━━━━ 18s 279ms/step - loss: 0.6216

 43/107 ━━━━━━━━━━━━━━━━━━━━ 17s 279ms/step - loss: 0.6210

 44/107 ━━━━━━━━━━━━━━━━━━━━ 17s 279ms/step - loss: 0.6203

 45/107 ━━━━━━━━━━━━━━━━━━━━ 17s 279ms/step - loss: 0.6197

 46/107 ━━━━━━━━━━━━━━━━━━━━ 17s 279ms/step - loss: 0.6191

 47/107 ━━━━━━━━━━━━━━━━━━━━ 16s 278ms/step - loss: 0.6185

 48/107 ━━━━━━━━━━━━━━━━━━━━ 16s 278ms/step - loss: 0.6180

 49/107 ━━━━━━━━━━━━━━━━━━━━ 16s 278ms/step - loss: 0.6175

 50/107 ━━━━━━━━━━━━━━━━━━━━ 15s 278ms/step - loss: 0.6170

 51/107 ━━━━━━━━━━━━━━━━━━━━ 15s 278ms/step - loss: 0.6166

 52/107 ━━━━━━━━━━━━━━━━━━━━ 15s 278ms/step - loss: 0.6162

 53/107 ━━━━━━━━━━━━━━━━━━━━ 15s 278ms/step - loss: 0.6157

 54/107 ━━━━━━━━━━━━━━━━━━━━ 14s 278ms/step - loss: 0.6153

 55/107 ━━━━━━━━━━━━━━━━━━━━ 14s 278ms/step - loss: 0.6149

 56/107 ━━━━━━━━━━━━━━━━━━━━ 14s 278ms/step - loss: 0.6146

 57/107 ━━━━━━━━━━━━━━━━━━━━ 13s 277ms/step - loss: 0.6142

 58/107 ━━━━━━━━━━━━━━━━━━━━ 13s 277ms/step - loss: 0.6139

 59/107 ━━━━━━━━━━━━━━━━━━━━ 13s 277ms/step - loss: 0.6135

 60/107 ━━━━━━━━━━━━━━━━━━━━ 13s 277ms/step - loss: 0.6132

 61/107 ━━━━━━━━━━━━━━━━━━━━ 12s 276ms/step - loss: 0.6129

 62/107 ━━━━━━━━━━━━━━━━━━━━ 12s 276ms/step - loss: 0.6126

 63/107 ━━━━━━━━━━━━━━━━━━━━ 12s 276ms/step - loss: 0.6123

 64/107 ━━━━━━━━━━━━━━━━━━━━ 11s 276ms/step - loss: 0.6120

 65/107 ━━━━━━━━━━━━━━━━━━━━ 11s 276ms/step - loss: 0.6117

 66/107 ━━━━━━━━━━━━━━━━━━━━ 11s 276ms/step - loss: 0.6114

 67/107 ━━━━━━━━━━━━━━━━━━━━ 11s 276ms/step - loss: 0.6111

 68/107 ━━━━━━━━━━━━━━━━━━━━ 10s 276ms/step - loss: 0.6107

 69/107 ━━━━━━━━━━━━━━━━━━━━ 10s 275ms/step - loss: 0.6104

 70/107 ━━━━━━━━━━━━━━━━━━━━ 10s 275ms/step - loss: 0.6101

 71/107 ━━━━━━━━━━━━━━━━━━━━ 9s 275ms/step - loss: 0.6098

 72/107 ━━━━━━━━━━━━━━━━━━━━ 9s 275ms/step - loss: 0.6095

 73/107 ━━━━━━━━━━━━━━━━━━━━ 9s 275ms/step - loss: 0.6093

 74/107 ━━━━━━━━━━━━━━━━━━━━ 9s 275ms/step - loss: 0.6090

 75/107 ━━━━━━━━━━━━━━━━━━━━ 8s 275ms/step - loss: 0.6087

 76/107 ━━━━━━━━━━━━━━━━━━━━ 8s 275ms/step - loss: 0.6084

 77/107 ━━━━━━━━━━━━━━━━━━━━ 8s 275ms/step - loss: 0.6082

 78/107 ━━━━━━━━━━━━━━━━━━━━ 7s 275ms/step - loss: 0.6079

 79/107 ━━━━━━━━━━━━━━━━━━━━ 7s 275ms/step - loss: 0.6077

 80/107 ━━━━━━━━━━━━━━━━━━━━ 7s 275ms/step - loss: 0.6075

 81/107 ━━━━━━━━━━━━━━━━━━━━ 7s 276ms/step - loss: 0.6073

 82/107 ━━━━━━━━━━━━━━━━━━━━ 6s 276ms/step - loss: 0.6071

 83/107 ━━━━━━━━━━━━━━━━━━━━ 6s 276ms/step - loss: 0.6069

 84/107 ━━━━━━━━━━━━━━━━━━━━ 6s 276ms/step - loss: 0.6067

 85/107 ━━━━━━━━━━━━━━━━━━━━ 6s 276ms/step - loss: 0.6065

 86/107 ━━━━━━━━━━━━━━━━━━━━ 5s 276ms/step - loss: 0.6064

 87/107 ━━━━━━━━━━━━━━━━━━━━ 5s 276ms/step - loss: 0.6062

 88/107 ━━━━━━━━━━━━━━━━━━━━ 5s 276ms/step - loss: 0.6061

 89/107 ━━━━━━━━━━━━━━━━━━━━ 4s 276ms/step - loss: 0.6059

 90/107 ━━━━━━━━━━━━━━━━━━━━ 4s 276ms/step - loss: 0.6058

 91/107 ━━━━━━━━━━━━━━━━━━━━ 4s 276ms/step - loss: 0.6056

 92/107 ━━━━━━━━━━━━━━━━━━━━ 4s 276ms/step - loss: 0.6055

 93/107 ━━━━━━━━━━━━━━━━━━━━ 3s 276ms/step - loss: 0.6054

 94/107 ━━━━━━━━━━━━━━━━━━━━ 3s 276ms/step - loss: 0.6053

 95/107 ━━━━━━━━━━━━━━━━━━━━ 3s 276ms/step - loss: 0.6052

 96/107 ━━━━━━━━━━━━━━━━━━━━ 3s 276ms/step - loss: 0.6051

 97/107 ━━━━━━━━━━━━━━━━━━━━ 2s 276ms/step - loss: 0.6050

 98/107 ━━━━━━━━━━━━━━━━━━━━ 2s 276ms/step - loss: 0.6049

 99/107 ━━━━━━━━━━━━━━━━━━━━ 2s 276ms/step - loss: 0.6049

100/107 ━━━━━━━━━━━━━━━━━━━━ 1s 276ms/step - loss: 0.6048

101/107 ━━━━━━━━━━━━━━━━━━━━ 1s 276ms/step - loss: 0.6047

102/107 ━━━━━━━━━━━━━━━━━━━━ 1s 276ms/step - loss: 0.6047

103/107 ━━━━━━━━━━━━━━━━━━━━ 1s 276ms/step - loss: 0.6046

104/107 ━━━━━━━━━━━━━━━━━━━━ 0s 276ms/step - loss: 0.6045

105/107 ━━━━━━━━━━━━━━━━━━━━ 0s 276ms/step - loss: 0.6045

106/107 ━━━━━━━━━━━━━━━━━━━━ 0s 276ms/step - loss: 0.6044

107/107 ━━━━━━━━━━━━━━━━━━━━ 0s 275ms/step - loss: 0.6043

107/107 ━━━━━━━━━━━━━━━━━━━━ 31s 287ms/step - loss: 0.5979 - val_loss: 1.0582

Epoch 3/10

  1/107 ━━━━━━━━━━━━━━━━━━━━ 34s 323ms/step - loss: 0.4087

  2/107 ━━━━━━━━━━━━━━━━━━━━ 27s 266ms/step - loss: 0.4107

  3/107 ━━━━━━━━━━━━━━━━━━━━ 29s 280ms/step - loss: 0.4065

  4/107 ━━━━━━━━━━━━━━━━━━━━ 27s 271ms/step - loss: 0.4035

  5/107 ━━━━━━━━━━━━━━━━━━━━ 27s 268ms/step - loss: 0.4049

  6/107 ━━━━━━━━━━━━━━━━━━━━ 27s 268ms/step - loss: 0.4044

  7/107 ━━━━━━━━━━━━━━━━━━━━ 26s 266ms/step - loss: 0.4036

  8/107 ━━━━━━━━━━━━━━━━━━━━ 26s 266ms/step - loss: 0.4027

  9/107 ━━━━━━━━━━━━━━━━━━━━ 26s 266ms/step - loss: 0.4034

 10/107 ━━━━━━━━━━━━━━━━━━━━ 25s 266ms/step - loss: 0.4042

 11/107 ━━━━━━━━━━━━━━━━━━━━ 25s 271ms/step - loss: 0.4051

 12/107 ━━━━━━━━━━━━━━━━━━━━ 25s 269ms/step - loss: 0.4061

 13/107 ━━━━━━━━━━━━━━━━━━━━ 25s 269ms/step - loss: 0.4065

 14/107 ━━━━━━━━━━━━━━━━━━━━ 25s 270ms/step - loss: 0.4067

 15/107 ━━━━━━━━━━━━━━━━━━━━ 24s 269ms/step - loss: 0.4067

 16/107 ━━━━━━━━━━━━━━━━━━━━ 24s 269ms/step - loss: 0.4065

 17/107 ━━━━━━━━━━━━━━━━━━━━ 24s 269ms/step - loss: 0.4062

 18/107 ━━━━━━━━━━━━━━━━━━━━ 23s 268ms/step - loss: 0.4059

 19/107 ━━━━━━━━━━━━━━━━━━━━ 23s 268ms/step - loss: 0.4058

 20/107 ━━━━━━━━━━━━━━━━━━━━ 23s 268ms/step - loss: 0.4057

 21/107 ━━━━━━━━━━━━━━━━━━━━ 23s 268ms/step - loss: 0.4056

 22/107 ━━━━━━━━━━━━━━━━━━━━ 22s 268ms/step - loss: 0.4054

 23/107 ━━━━━━━━━━━━━━━━━━━━ 22s 268ms/step - loss: 0.4052

 24/107 ━━━━━━━━━━━━━━━━━━━━ 22s 268ms/step - loss: 0.4049

 25/107 ━━━━━━━━━━━━━━━━━━━━ 22s 269ms/step - loss: 0.4047

 26/107 ━━━━━━━━━━━━━━━━━━━━ 21s 269ms/step - loss: 0.4044

 27/107 ━━━━━━━━━━━━━━━━━━━━ 21s 269ms/step - loss: 0.4042

 28/107 ━━━━━━━━━━━━━━━━━━━━ 21s 270ms/step - loss: 0.4039

 29/107 ━━━━━━━━━━━━━━━━━━━━ 21s 270ms/step - loss: 0.4037

 30/107 ━━━━━━━━━━━━━━━━━━━━ 20s 270ms/step - loss: 0.4034

 31/107 ━━━━━━━━━━━━━━━━━━━━ 20s 270ms/step - loss: 0.4031

 32/107 ━━━━━━━━━━━━━━━━━━━━ 20s 270ms/step - loss: 0.4028

 33/107 ━━━━━━━━━━━━━━━━━━━━ 20s 270ms/step - loss: 0.4025

 34/107 ━━━━━━━━━━━━━━━━━━━━ 19s 271ms/step - loss: 0.4022

 35/107 ━━━━━━━━━━━━━━━━━━━━ 19s 272ms/step - loss: 0.4020

 36/107 ━━━━━━━━━━━━━━━━━━━━ 19s 272ms/step - loss: 0.4017

 37/107 ━━━━━━━━━━━━━━━━━━━━ 19s 272ms/step - loss: 0.4014

 38/107 ━━━━━━━━━━━━━━━━━━━━ 18s 274ms/step - loss: 0.4012

 39/107 ━━━━━━━━━━━━━━━━━━━━ 18s 274ms/step - loss: 0.4009

 40/107 ━━━━━━━━━━━━━━━━━━━━ 18s 274ms/step - loss: 0.4007

 41/107 ━━━━━━━━━━━━━━━━━━━━ 18s 274ms/step - loss: 0.4005

 42/107 ━━━━━━━━━━━━━━━━━━━━ 17s 274ms/step - loss: 0.4004

 43/107 ━━━━━━━━━━━━━━━━━━━━ 17s 274ms/step - loss: 0.4002

 44/107 ━━━━━━━━━━━━━━━━━━━━ 17s 274ms/step - loss: 0.4000

 45/107 ━━━━━━━━━━━━━━━━━━━━ 16s 273ms/step - loss: 0.3998

 46/107 ━━━━━━━━━━━━━━━━━━━━ 16s 273ms/step - loss: 0.3996

 47/107 ━━━━━━━━━━━━━━━━━━━━ 16s 273ms/step - loss: 0.3995

 48/107 ━━━━━━━━━━━━━━━━━━━━ 16s 273ms/step - loss: 0.3993

 49/107 ━━━━━━━━━━━━━━━━━━━━ 15s 274ms/step - loss: 0.3991

 50/107 ━━━━━━━━━━━━━━━━━━━━ 15s 274ms/step - loss: 0.3989

 51/107 ━━━━━━━━━━━━━━━━━━━━ 15s 274ms/step - loss: 0.3987

 52/107 ━━━━━━━━━━━━━━━━━━━━ 15s 273ms/step - loss: 0.3985

 53/107 ━━━━━━━━━━━━━━━━━━━━ 14s 273ms/step - loss: 0.3983

 54/107 ━━━━━━━━━━━━━━━━━━━━ 14s 273ms/step - loss: 0.3980

 55/107 ━━━━━━━━━━━━━━━━━━━━ 14s 273ms/step - loss: 0.3978

 56/107 ━━━━━━━━━━━━━━━━━━━━ 13s 273ms/step - loss: 0.3976

 57/107 ━━━━━━━━━━━━━━━━━━━━ 13s 274ms/step - loss: 0.3974

 58/107 ━━━━━━━━━━━━━━━━━━━━ 13s 274ms/step - loss: 0.3972

 59/107 ━━━━━━━━━━━━━━━━━━━━ 13s 274ms/step - loss: 0.3970

 60/107 ━━━━━━━━━━━━━━━━━━━━ 12s 274ms/step - loss: 0.3968

 61/107 ━━━━━━━━━━━━━━━━━━━━ 12s 274ms/step - loss: 0.3967

 62/107 ━━━━━━━━━━━━━━━━━━━━ 12s 274ms/step - loss: 0.3966

 63/107 ━━━━━━━━━━━━━━━━━━━━ 12s 274ms/step - loss: 0.3965

 64/107 ━━━━━━━━━━━━━━━━━━━━ 11s 275ms/step - loss: 0.3964

 65/107 ━━━━━━━━━━━━━━━━━━━━ 11s 276ms/step - loss: 0.3963

 66/107 ━━━━━━━━━━━━━━━━━━━━ 11s 276ms/step - loss: 0.3963

 67/107 ━━━━━━━━━━━━━━━━━━━━ 11s 276ms/step - loss: 0.3962

 68/107 ━━━━━━━━━━━━━━━━━━━━ 10s 276ms/step - loss: 0.3962

 69/107 ━━━━━━━━━━━━━━━━━━━━ 10s 276ms/step - loss: 0.3961

 70/107 ━━━━━━━━━━━━━━━━━━━━ 10s 276ms/step - loss: 0.3961

 71/107 ━━━━━━━━━━━━━━━━━━━━ 9s 276ms/step - loss: 0.3961

 72/107 ━━━━━━━━━━━━━━━━━━━━ 9s 276ms/step - loss: 0.3961

 73/107 ━━━━━━━━━━━━━━━━━━━━ 9s 276ms/step - loss: 0.3961

 74/107 ━━━━━━━━━━━━━━━━━━━━ 9s 277ms/step - loss: 0.3961

 75/107 ━━━━━━━━━━━━━━━━━━━━ 8s 277ms/step - loss: 0.3961

 76/107 ━━━━━━━━━━━━━━━━━━━━ 8s 277ms/step - loss: 0.3961

 77/107 ━━━━━━━━━━━━━━━━━━━━ 8s 277ms/step - loss: 0.3961

 78/107 ━━━━━━━━━━━━━━━━━━━━ 8s 277ms/step - loss: 0.3961

 79/107 ━━━━━━━━━━━━━━━━━━━━ 7s 277ms/step - loss: 0.3961

 80/107 ━━━━━━━━━━━━━━━━━━━━ 7s 277ms/step - loss: 0.3961

 81/107 ━━━━━━━━━━━━━━━━━━━━ 7s 277ms/step - loss: 0.3962

 82/107 ━━━━━━━━━━━━━━━━━━━━ 6s 277ms/step - loss: 0.3962

 83/107 ━━━━━━━━━━━━━━━━━━━━ 6s 278ms/step - loss: 0.3962

 84/107 ━━━━━━━━━━━━━━━━━━━━ 6s 278ms/step - loss: 0.3962

 85/107 ━━━━━━━━━━━━━━━━━━━━ 6s 278ms/step - loss: 0.3963

 86/107 ━━━━━━━━━━━━━━━━━━━━ 5s 279ms/step - loss: 0.3963

 87/107 ━━━━━━━━━━━━━━━━━━━━ 5s 279ms/step - loss: 0.3964

 88/107 ━━━━━━━━━━━━━━━━━━━━ 5s 279ms/step - loss: 0.3965

 89/107 ━━━━━━━━━━━━━━━━━━━━ 5s 279ms/step - loss: 0.3966

 90/107 ━━━━━━━━━━━━━━━━━━━━ 4s 279ms/step - loss: 0.3966

 91/107 ━━━━━━━━━━━━━━━━━━━━ 4s 279ms/step - loss: 0.3967

 92/107 ━━━━━━━━━━━━━━━━━━━━ 4s 279ms/step - loss: 0.3968

 93/107 ━━━━━━━━━━━━━━━━━━━━ 3s 279ms/step - loss: 0.3969

 94/107 ━━━━━━━━━━━━━━━━━━━━ 3s 279ms/step - loss: 0.3969

 95/107 ━━━━━━━━━━━━━━━━━━━━ 3s 279ms/step - loss: 0.3970

 96/107 ━━━━━━━━━━━━━━━━━━━━ 3s 279ms/step - loss: 0.3971

 97/107 ━━━━━━━━━━━━━━━━━━━━ 2s 279ms/step - loss: 0.3972

 98/107 ━━━━━━━━━━━━━━━━━━━━ 2s 279ms/step - loss: 0.3973

 99/107 ━━━━━━━━━━━━━━━━━━━━ 2s 279ms/step - loss: 0.3974

100/107 ━━━━━━━━━━━━━━━━━━━━ 1s 279ms/step - loss: 0.3974

101/107 ━━━━━━━━━━━━━━━━━━━━ 1s 279ms/step - loss: 0.3975

102/107 ━━━━━━━━━━━━━━━━━━━━ 1s 279ms/step - loss: 0.3976

103/107 ━━━━━━━━━━━━━━━━━━━━ 1s 279ms/step - loss: 0.3977

104/107 ━━━━━━━━━━━━━━━━━━━━ 0s 279ms/step - loss: 0.3978

105/107 ━━━━━━━━━━━━━━━━━━━━ 0s 279ms/step - loss: 0.3979

106/107 ━━━━━━━━━━━━━━━━━━━━ 0s 279ms/step - loss: 0.3980

107/107 ━━━━━━━━━━━━━━━━━━━━ 0s 278ms/step - loss: 0.3982

107/107 ━━━━━━━━━━━━━━━━━━━━ 31s 291ms/step - loss: 0.4093 - val_loss: 1.2383

Epoch 4/10

  1/107 ━━━━━━━━━━━━━━━━━━━━ 30s 291ms/step - loss: 0.2990

  2/107 ━━━━━━━━━━━━━━━━━━━━ 28s 270ms/step - loss: 0.2877

  3/107 ━━━━━━━━━━━━━━━━━━━━ 27s 267ms/step - loss: 0.2846

  4/107 ━━━━━━━━━━━━━━━━━━━━ 27s 265ms/step - loss: 0.2850

  5/107 ━━━━━━━━━━━━━━━━━━━━ 27s 268ms/step - loss: 0.2840

  6/107 ━━━━━━━━━━━━━━━━━━━━ 27s 269ms/step - loss: 0.2852

  7/107 ━━━━━━━━━━━━━━━━━━━━ 26s 268ms/step - loss: 0.2863

  8/107 ━━━━━━━━━━━━━━━━━━━━ 26s 268ms/step - loss: 0.2872

  9/107 ━━━━━━━━━━━━━━━━━━━━ 26s 269ms/step - loss: 0.2873

 10/107 ━━━━━━━━━━━━━━━━━━━━ 26s 268ms/step - loss: 0.2868

 11/107 ━━━━━━━━━━━━━━━━━━━━ 25s 267ms/step - loss: 0.2864

 12/107 ━━━━━━━━━━━━━━━━━━━━ 25s 267ms/step - loss: 0.2858

 13/107 ━━━━━━━━━━━━━━━━━━━━ 25s 267ms/step - loss: 0.2853

 14/107 ━━━━━━━━━━━━━━━━━━━━ 24s 267ms/step - loss: 0.2847

 15/107 ━━━━━━━━━━━━━━━━━━━━ 24s 266ms/step - loss: 0.2841

 16/107 ━━━━━━━━━━━━━━━━━━━━ 24s 266ms/step - loss: 0.2837

 17/107 ━━━━━━━━━━━━━━━━━━━━ 23s 267ms/step - loss: 0.2834

 18/107 ━━━━━━━━━━━━━━━━━━━━ 23s 267ms/step - loss: 0.2830

 19/107 ━━━━━━━━━━━━━━━━━━━━ 23s 268ms/step - loss: 0.2825

 20/107 ━━━━━━━━━━━━━━━━━━━━ 23s 268ms/step - loss: 0.2819

 21/107 ━━━━━━━━━━━━━━━━━━━━ 23s 268ms/step - loss: 0.2814

 22/107 ━━━━━━━━━━━━━━━━━━━━ 22s 268ms/step - loss: 0.2809

 23/107 ━━━━━━━━━━━━━━━━━━━━ 22s 268ms/step - loss: 0.2806

 24/107 ━━━━━━━━━━━━━━━━━━━━ 22s 268ms/step - loss: 0.2801

 25/107 ━━━━━━━━━━━━━━━━━━━━ 22s 268ms/step - loss: 0.2797

 26/107 ━━━━━━━━━━━━━━━━━━━━ 21s 268ms/step - loss: 0.2793

 27/107 ━━━━━━━━━━━━━━━━━━━━ 21s 268ms/step - loss: 0.2789

 28/107 ━━━━━━━━━━━━━━━━━━━━ 21s 269ms/step - loss: 0.2784

 29/107 ━━━━━━━━━━━━━━━━━━━━ 21s 269ms/step - loss: 0.2779

 30/107 ━━━━━━━━━━━━━━━━━━━━ 20s 269ms/step - loss: 0.2777

 31/107 ━━━━━━━━━━━━━━━━━━━━ 20s 269ms/step - loss: 0.2773

 32/107 ━━━━━━━━━━━━━━━━━━━━ 20s 269ms/step - loss: 0.2770

 33/107 ━━━━━━━━━━━━━━━━━━━━ 19s 269ms/step - loss: 0.2766

 34/107 ━━━━━━━━━━━━━━━━━━━━ 19s 271ms/step - loss: 0.2763

 35/107 ━━━━━━━━━━━━━━━━━━━━ 19s 271ms/step - loss: 0.2760

 36/107 ━━━━━━━━━━━━━━━━━━━━ 19s 271ms/step - loss: 0.2758

 37/107 ━━━━━━━━━━━━━━━━━━━━ 18s 270ms/step - loss: 0.2755

 38/107 ━━━━━━━━━━━━━━━━━━━━ 18s 270ms/step - loss: 0.2753

 39/107 ━━━━━━━━━━━━━━━━━━━━ 18s 270ms/step - loss: 0.2752

 40/107 ━━━━━━━━━━━━━━━━━━━━ 18s 270ms/step - loss: 0.2751

 41/107 ━━━━━━━━━━━━━━━━━━━━ 17s 270ms/step - loss: 0.2750

 42/107 ━━━━━━━━━━━━━━━━━━━━ 17s 271ms/step - loss: 0.2750

 43/107 ━━━━━━━━━━━━━━━━━━━━ 17s 271ms/step - loss: 0.2749

 44/107 ━━━━━━━━━━━━━━━━━━━━ 17s 271ms/step - loss: 0.2749

 45/107 ━━━━━━━━━━━━━━━━━━━━ 16s 272ms/step - loss: 0.2748

 46/107 ━━━━━━━━━━━━━━━━━━━━ 16s 272ms/step - loss: 0.2748

 47/107 ━━━━━━━━━━━━━━━━━━━━ 16s 272ms/step - loss: 0.2747

 48/107 ━━━━━━━━━━━━━━━━━━━━ 16s 272ms/step - loss: 0.2746

 49/107 ━━━━━━━━━━━━━━━━━━━━ 15s 272ms/step - loss: 0.2745

 50/107 ━━━━━━━━━━━━━━━━━━━━ 15s 272ms/step - loss: 0.2744

 51/107 ━━━━━━━━━━━━━━━━━━━━ 15s 272ms/step - loss: 0.2744

 52/107 ━━━━━━━━━━━━━━━━━━━━ 14s 272ms/step - loss: 0.2743

 53/107 ━━━━━━━━━━━━━━━━━━━━ 14s 272ms/step - loss: 0.2743

 54/107 ━━━━━━━━━━━━━━━━━━━━ 14s 272ms/step - loss: 0.2742

 55/107 ━━━━━━━━━━━━━━━━━━━━ 14s 272ms/step - loss: 0.2742

 56/107 ━━━━━━━━━━━━━━━━━━━━ 13s 272ms/step - loss: 0.2742

 57/107 ━━━━━━━━━━━━━━━━━━━━ 13s 272ms/step - loss: 0.2741

 58/107 ━━━━━━━━━━━━━━━━━━━━ 13s 272ms/step - loss: 0.2741

 59/107 ━━━━━━━━━━━━━━━━━━━━ 13s 272ms/step - loss: 0.2741

 60/107 ━━━━━━━━━━━━━━━━━━━━ 12s 272ms/step - loss: 0.2741

 61/107 ━━━━━━━━━━━━━━━━━━━━ 12s 272ms/step - loss: 0.2742

 62/107 ━━━━━━━━━━━━━━━━━━━━ 12s 272ms/step - loss: 0.2742

 63/107 ━━━━━━━━━━━━━━━━━━━━ 11s 272ms/step - loss: 0.2743

 64/107 ━━━━━━━━━━━━━━━━━━━━ 11s 273ms/step - loss: 0.2744

 65/107 ━━━━━━━━━━━━━━━━━━━━ 11s 273ms/step - loss: 0.2745

 66/107 ━━━━━━━━━━━━━━━━━━━━ 11s 273ms/step - loss: 0.2746

 67/107 ━━━━━━━━━━━━━━━━━━━━ 10s 274ms/step - loss: 0.2747

 68/107 ━━━━━━━━━━━━━━━━━━━━ 10s 274ms/step - loss: 0.2748

 69/107 ━━━━━━━━━━━━━━━━━━━━ 10s 275ms/step - loss: 0.2749

 70/107 ━━━━━━━━━━━━━━━━━━━━ 10s 275ms/step - loss: 0.2749

 71/107 ━━━━━━━━━━━━━━━━━━━━ 9s 275ms/step - loss: 0.2750

 72/107 ━━━━━━━━━━━━━━━━━━━━ 9s 276ms/step - loss: 0.2751

 73/107 ━━━━━━━━━━━━━━━━━━━━ 9s 276ms/step - loss: 0.2752

 74/107 ━━━━━━━━━━━━━━━━━━━━ 9s 276ms/step - loss: 0.2753

 75/107 ━━━━━━━━━━━━━━━━━━━━ 8s 276ms/step - loss: 0.2754

 76/107 ━━━━━━━━━━━━━━━━━━━━ 8s 276ms/step - loss: 0.2755

 77/107 ━━━━━━━━━━━━━━━━━━━━ 8s 276ms/step - loss: 0.2756

 78/107 ━━━━━━━━━━━━━━━━━━━━ 8s 276ms/step - loss: 0.2757

 79/107 ━━━━━━━━━━━━━━━━━━━━ 7s 276ms/step - loss: 0.2758

 80/107 ━━━━━━━━━━━━━━━━━━━━ 7s 276ms/step - loss: 0.2759

 81/107 ━━━━━━━━━━━━━━━━━━━━ 7s 276ms/step - loss: 0.2761

 82/107 ━━━━━━━━━━━━━━━━━━━━ 6s 276ms/step - loss: 0.2762

 83/107 ━━━━━━━━━━━━━━━━━━━━ 6s 276ms/step - loss: 0.2763

 84/107 ━━━━━━━━━━━━━━━━━━━━ 6s 276ms/step - loss: 0.2765

 85/107 ━━━━━━━━━━━━━━━━━━━━ 6s 276ms/step - loss: 0.2766

 86/107 ━━━━━━━━━━━━━━━━━━━━ 5s 276ms/step - loss: 0.2768

 87/107 ━━━━━━━━━━━━━━━━━━━━ 5s 277ms/step - loss: 0.2769

 88/107 ━━━━━━━━━━━━━━━━━━━━ 5s 276ms/step - loss: 0.2771

 89/107 ━━━━━━━━━━━━━━━━━━━━ 4s 276ms/step - loss: 0.2772

 90/107 ━━━━━━━━━━━━━━━━━━━━ 4s 276ms/step - loss: 0.2774

 91/107 ━━━━━━━━━━━━━━━━━━━━ 4s 276ms/step - loss: 0.2775

 92/107 ━━━━━━━━━━━━━━━━━━━━ 4s 276ms/step - loss: 0.2776

 93/107 ━━━━━━━━━━━━━━━━━━━━ 3s 276ms/step - loss: 0.2778

 94/107 ━━━━━━━━━━━━━━━━━━━━ 3s 276ms/step - loss: 0.2779

 95/107 ━━━━━━━━━━━━━━━━━━━━ 3s 276ms/step - loss: 0.2780

 96/107 ━━━━━━━━━━━━━━━━━━━━ 3s 276ms/step - loss: 0.2782

 97/107 ━━━━━━━━━━━━━━━━━━━━ 2s 276ms/step - loss: 0.2783

 98/107 ━━━━━━━━━━━━━━━━━━━━ 2s 276ms/step - loss: 0.2784

 99/107 ━━━━━━━━━━━━━━━━━━━━ 2s 277ms/step - loss: 0.2786

100/107 ━━━━━━━━━━━━━━━━━━━━ 1s 276ms/step - loss: 0.2787

101/107 ━━━━━━━━━━━━━━━━━━━━ 1s 277ms/step - loss: 0.2788

102/107 ━━━━━━━━━━━━━━━━━━━━ 1s 277ms/step - loss: 0.2790

103/107 ━━━━━━━━━━━━━━━━━━━━ 1s 276ms/step - loss: 0.2791

104/107 ━━━━━━━━━━━━━━━━━━━━ 0s 276ms/step - loss: 0.2792

105/107 ━━━━━━━━━━━━━━━━━━━━ 0s 276ms/step - loss: 0.2793

106/107 ━━━━━━━━━━━━━━━━━━━━ 0s 277ms/step - loss: 0.2794

107/107 ━━━━━━━━━━━━━━━━━━━━ 0s 276ms/step - loss: 0.2795

107/107 ━━━━━━━━━━━━━━━━━━━━ 31s 288ms/step - loss: 0.2920 - val_loss: 1.5273

  saved /kaggle/working/models/bert_with_emoji.keras
  threshold 0.55 | dev Micro-F1 51.00%

## 3.8 Persist everything the later stages need

The original notebook computed the tuned thresholds but never wrote them to disk,
so they were lost when the kernel ended — and without them the served model falls
back to 0.5 and stops predicting rare emotions almost entirely. They are saved
here alongside the models.

In [34]:
(RESULTS / "thresholds.json").write_text(
    json.dumps(thresholds, indent=2), encoding="utf-8")
(RESULTS / "best_configs.json").write_text(
    json.dumps(best_configs, indent=2), encoding="utf-8")
pd.concat(tuning_log, ignore_index=True).to_csv(
    RESULTS / "hyperparameter_search.csv", index=False)

print("thresholds.json:")
print(json.dumps(thresholds, indent=2))
print("\nartefacts written:")
for p in sorted(MODELS.iterdir()):
    print(f"  models/{p.name:26s} {p.stat().st_size / 1e6:.1f} MB")
for name in ("thresholds.json", "best_configs.json", "hyperparameter_search.csv",
             "pipeline_fixture.json"):
    print(f"  results/{name}")

thresholds.json:
{
  "LSTM_no_emoji": 0.55,
  "LSTM_with_emoji": 0.55,
  "BERT_no_emoji": 0.55,
  "BERT_with_emoji": 0.55
}

artefacts written:
  models/bert_no_emoji.keras        19.7 MB
  models/bert_with_emoji.keras      19.8 MB
  models/lstm_no_emoji.keras        19.8 MB
  models/lstm_with_emoji.keras      19.9 MB
  results/thresholds.json
  results/best_configs.json
  results/hyperparameter_search.csv
  results/pipeline_fixture.json

## Summary

Four trained models, their tuned decision thresholds, the winning configurations
and the full search log are now on disk, together with the two processed corpora.

`04_evaluation.ipynb` scores them, and the Streamlit UI in `app/` serves them —
both read straight from these directories, so no copying is required.